// Code generated by tapir. DO NOT EDIT.

package meta

// One metric value returned by an insights read: the most recent value the
// platform reported for the metric.
type Insight struct {
	Name string `json:"name"`
	Period *string `json:"period"`
	Value InsightValue `json:"value"`
}
