// Code generated by tapir. DO NOT EDIT.

package meta

// A metric's value: most metrics report a number; breakdown metrics report
// an object of numbers per dimension (e.g. reactions by type). Metrics
// whose reported value fits neither shape — including a missing value —
// are dropped at fetch time; nothing raw is passed through.
type InsightValue = interface{}
