// Code generated by tapir. DO NOT EDIT.

package meta

// An Instagram post. All media URLs must be publicly reachable — Meta's
// servers fetch them. Video-backed media (reels, video stories, video
// carousel items) process asynchronously on Meta's side.
type InstagramPostContent struct {
	Media InstagramMedia `json:"media"`
	Caption *string `json:"caption"`
	// Instagram location id (from Meta's location search) to tag.
	LocationId *string `json:"location_id"`
	// Usernames invited as collaborators (public professional accounts).
	Collaborators []string `json:"collaborators"`
}
