// Code generated by tapir. DO NOT EDIT.

package meta

// One carousel item: exactly one of `image_url` / `video_url`.
type InstagramCarouselItem struct {
	ImageUrl *string `json:"image_url"`
	VideoUrl *string `json:"video_url"`
	UserTags []InstagramUserTag `json:"user_tags"`
}
