// Code generated by tapir. DO NOT EDIT.

package meta

type WhatsappTemplateDateTime struct {
	// Meta localizes only what it can parse; everything else renders verbatim,
	// so the hub always supplies the text it wants shown.
	FallbackValue string `json:"fallback_value"`
}
