// Code generated by tapir. DO NOT EDIT.

package meta

type WhatsappTemplateCurrency struct {
	// Rendered as-is if the recipient's locale is unsupported.
	FallbackValue string `json:"fallback_value"`
	// ISO 4217, e.g. `BRL`.
	Code string `json:"code"`
	// The amount multiplied by 1000 — Meta's integer money representation.
	Amount1000 int64 `json:"amount_1000"`
}
