// Code generated by tapir. DO NOT EDIT.

package meta

type WhatsappTemplateButtonSubType string

const (
	WhatsappTemplateButtonSubTypeQuickReply WhatsappTemplateButtonSubType = "quick_reply"
	WhatsappTemplateButtonSubTypeUrl WhatsappTemplateButtonSubType = "url"
	WhatsappTemplateButtonSubTypeCopyCode WhatsappTemplateButtonSubType = "copy_code"
)
