// Code generated by tapir. DO NOT EDIT.

package meta

// One substitution block of a template *send* — the values that fill an
// approved template's placeholders. Serializes straight to the Cloud API
// shape: Meta spells these lowercase already, so no boundary translation.
type WhatsappTemplateSendComponent = interface{}
