// Code generated by tapir. DO NOT EDIT.

package meta

// Where a template sits in Meta's review pipeline. Only `approved` is
// sendable.
type WhatsappTemplateStatus string

const (
	WhatsappTemplateStatusApproved WhatsappTemplateStatus = "approved"
	WhatsappTemplateStatusPending WhatsappTemplateStatus = "pending"
	WhatsappTemplateStatusRejected WhatsappTemplateStatus = "rejected"
	WhatsappTemplateStatusPaused WhatsappTemplateStatus = "paused"
	WhatsappTemplateStatusDisabled WhatsappTemplateStatus = "disabled"
	WhatsappTemplateStatusInAppeal WhatsappTemplateStatus = "in_appeal"
	WhatsappTemplateStatusPendingDeletion WhatsappTemplateStatus = "pending_deletion"
	WhatsappTemplateStatusUnknown WhatsappTemplateStatus = "unknown"
)
