// Code generated by tapir. DO NOT EDIT.

package meta

// One placeholder value. Media parameters carry a public URL, matching the
// rest of the send surface (the hub never sends media ids).
type WhatsappTemplateParameter = interface{}
