// Code generated by tapir. DO NOT EDIT.

package mailing

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type EmailQueueListQuery struct {
	Status *types.EmailQueueStatus `json:"status"`
	Limit *primitives.Number1_500 `json:"limit"`
}
