// Code generated by tapir. DO NOT EDIT.

package mailing

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type EmailQueueListQuery struct {
	Status *domain.EmailQueueStatus `json:"status"`
	Limit *primitives.Number1_500 `json:"limit"`
}
