// Code generated by tapi. DO NOT EDIT.

package call

import (
	__client "integro_sdk"
	__strings "strings"
	call "integro_sdk/types/call"
	database "integro_sdk/types/database"
)

// Answer Answer a ringing call, claiming it for the caller — who is then the only
// one that may carry its media. A second operator answering the same call
// gets "chamada já atendida".
//
// Requires `SendMessages` in the conversation's group.
func Answer(__c *__client.Client, conversationUid string, callUid string) (database.Call, error) {
	__path := "/conversation/{conversation_uid}/call/{call_uid}/answer"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	__path = __strings.Replace(__path, "{call_uid}", __client.EncodePath(callUid), 1)
	return __client.Request[database.Call](__c, "POST", __path, nil, nil)
}
// Hangup End a call in progress. Not restricted to the operator holding it: a call
// whose operator walked away has to be endable by whoever is still there. A
// call that was never answered here has nothing to hang up — refusing that one
// is `reject`.
//
// Requires `SendMessages` in the conversation's group.
func Hangup(__c *__client.Client, conversationUid string, callUid string) (struct{}, error) {
	__path := "/conversation/{conversation_uid}/call/{call_uid}/hangup"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	__path = __strings.Replace(__path, "{call_uid}", __client.EncodePath(callUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// Media The call's live media, typed both ways. Binary frames carry the media
// itself — `0x01` plus one 1920-byte s16le 16 kHz mono audio frame, or `0x02`
// plus a flags byte and one H.264 Annex-B access unit — in exactly the
// formats WhatsApp uses, so nothing between the browser and the contact
// transcodes. Text frames carry the in-call controls: the video upgrade
// handshake, camera state, orientation and reactions. Everything that decides
// whether the call exists stays on the REST routes above.
//
// Reconnecting re-attaches and replaces the previous tracks; a claimed call
// whose operator stays gone for 30 seconds is hung up rather than left
// running silently.
//
// Requires `SendMessages` in the conversation's group, and the caller must be
// the operator who answered (or placed) this call.
func Media(__c *__client.Client, conversationUid string, callUid string, __handlers __client.WsHandlers[call.CallServerMsg]) *__client.WsConnection[call.CallClientMsg] {
	__path := "/conversation/{conversation_uid}/call/{call_uid}/media/ws"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	__path = __strings.Replace(__path, "{call_uid}", __client.EncodePath(callUid), 1)
	return __client.Ws[call.CallClientMsg, call.CallServerMsg](__c, __path, nil, __handlers)
}
// Place Call the conversation's contact. The body is channel-tagged — only
// whatsapp_native carries calls, so no other channel's shape deserializes.
// Returns as soon as the offer is on the wire — the contact's phone has not
// rung yet, and the phases that follow arrive as `call_updated` events. Only
// one call at a time per account.
//
// Requires `SendMessages` in the conversation's group.
func Place(__c *__client.Client, conversationUid string, __body call.PlaceCallRequest) (database.Call, error) {
	__path := "/conversation/{conversation_uid}/call"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	return __client.Request[database.Call](__c, "POST", __path, nil, __body)
}
// Reject Refuse a ringing call. Available to anyone who could have answered it — a
// shared inbox's ringing call is everyone's to decline.
//
// Requires `SendMessages` in the conversation's group.
func Reject(__c *__client.Client, conversationUid string, callUid string) (struct{}, error) {
	__path := "/conversation/{conversation_uid}/call/{call_uid}/reject"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	__path = __strings.Replace(__path, "{call_uid}", __client.EncodePath(callUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// Ringing List the calls ringing right now on accounts the caller can see — inbound,
// unclaimed and still answerable. Ring events are broadcast once and never
// replayed, so a client that just connected (a reloaded page, a login while a
// call is ringing) hydrates its ringing list from here.
//
// Requires `ViewMessages`; the list is clamped to the groups where it is held.
func Ringing(__c *__client.Client) ([]database.Call, error) {
	__path := "/call/ringing"
	return __client.Request[[]database.Call](__c, "GET", __path, nil, nil)
}
