// Code generated by tapi. DO NOT EDIT.

package social_account

import (
	__client "integro_sdk"
	__strings "strings"
	domain "integro_sdk/types/domain"
	insight "integro_sdk/types/insight"
	meta "integro_sdk/types/meta"
	social_account "integro_sdk/types/social_account"
)

// Callback Meta OAuth redirect target: consumes the state, exchanges the code, and
// stashes the grant snapshot for review — nothing is registered yet; always
// redirects the browser back to the frontend, with a review token on
// success.
//
// Public — no authentication required; authorization comes from the one-shot state token issued by `socialAccount.connect`.
func Callback(__c *__client.Client, __query social_account.ConnectCallbackQuery) (struct{}, error) {
	__path := "/social-account/callback"
	return __client.Request[struct{}](__c, "GET", __path, __query, nil)
}
// Connect Start the Meta OAuth flow for a group, returning the login dialog URL. The
// callback stashes the granted pages (and linked Instagram accounts) for
// review; `socialAccount.connectConfirm` is what registers the selection.
//
// Requires `ConnectSocialAccounts` in the named group.
func Connect(__c *__client.Client, __body social_account.ConnectSocialAccountRequest) (social_account.ConnectSocialAccountResponse, error) {
	__path := "/social-account/connect"
	return __client.Request[social_account.ConnectSocialAccountResponse](__c, "POST", __path, nil, __body)
}
// ConnectConfirm Register the selected accounts from a stashed grant (one-shot). Pages and
// instagram accounts are selected independently; unselected accounts stay in
// the Meta grant but out of the hub.
//
// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
func ConnectConfirm(__c *__client.Client, __body social_account.ConnectConfirmRequest) (social_account.ConnectSocialAccountsConnected, error) {
	__path := "/social-account/connect/confirm"
	return __client.Request[social_account.ConnectSocialAccountsConnected](__c, "POST", __path, nil, __body)
}
// ConnectReview Load a stashed Meta grant for the selection screen: every account it
// covers, plus group accounts whose stored token died on the Meta side
// (access removed) — those are flagged for reauthorization. Repeatable;
// only confirm consumes the stash.
//
// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
func ConnectReview(__c *__client.Client, __query social_account.ConnectReviewQuery) (social_account.ConnectReviewResponse, error) {
	__path := "/social-account/connect/review"
	return __client.Request[social_account.ConnectReviewResponse](__c, "GET", __path, __query, nil)
}
// ConnectStevo Connect a Stevo instance (unofficial WhatsApp gateway) to a group: the hub
// validates the server + apikey and registers the account. The webhook must
// be set manually in the Stevo panel. Pair the phone afterwards via the
// `stevo/qr` or `stevo/pair` sub-routes.
//
// Requires `ConnectSocialAccounts` in the named group.
func ConnectStevo(__c *__client.Client, __body social_account.ConnectStevoRequest) (social_account.ConnectStevoResponse, error) {
	__path := "/social-account/stevo"
	return __client.Request[social_account.ConnectStevoResponse](__c, "POST", __path, nil, __body)
}
// ConnectWhatsapp Connect a WhatsApp Business Account to a group by manual provisioning: the
// hub discovers the WABA's phone numbers with the supplied permanent token,
// subscribes webhooks, and registers one social account per number.
//
// Requires `ConnectSocialAccounts` in the named group.
func ConnectWhatsapp(__c *__client.Client, __body social_account.ConnectWhatsappRequest) (social_account.ConnectWhatsappResponse, error) {
	__path := "/social-account/whatsapp"
	return __client.Request[social_account.ConnectWhatsappResponse](__c, "POST", __path, nil, __body)
}
// Count Count connected social accounts, optionally filtered by group.
//
// Requires `ViewSocialAccounts`; the count covers only accounts of groups where the caller holds it.
func Count(__c *__client.Client, __query social_account.ListSocialAccountsQuery) (uint64, error) {
	__path := "/social-account/count"
	return __client.Request[uint64](__c, "GET", __path, __query, nil)
}
// Delete Disconnect a social account, deleting its conversations, messages, and
// posts with it. Native whatsapp accounts also unpair the phone
// (best-effort, in the background).
//
// Requires `DeleteSocialAccounts` in the account's group.
func Delete(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Exposure Read the account's exposure telemetry, hour by hour over the requested
// period (at most 92 days): how many platform lookups it made (usync number
// checks, profile pictures, presence subscriptions), its sends by origin,
// first-time contacts, whatsapp 429 and 463/475 answers, slow send acks and
// sends still without a delivery receipt an hour later, plus the alerts the
// last 24 hours raise right now. Only the session-backed whatsapp channels
// are metered.
//
// Requires `ViewSocialAccounts` in the account's group.
func Exposure(__c *__client.Client, socialAccountUid string, __query social_account.ExposureQuery) (domain.ExposureReport, error) {
	__path := "/social-account/{social_account_uid}/exposure"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[domain.ExposureReport](__c, "GET", __path, __query, nil)
}
// Get Fetch a single connected social account by uid, with the live session
// status of its whatsapp session when applicable.
//
// Requires `ViewSocialAccounts` in the account's group.
func Get(__c *__client.Client, socialAccountUid string) (social_account.SocialAccountResponse, error) {
	__path := "/social-account/{social_account_uid}"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[social_account.SocialAccountResponse](__c, "GET", __path, nil, nil)
}
// Insights Fetch platform metrics for a facebook page or instagram professional
// account (the per-channel defaults, or a caller-supplied
// `metrics`/`period`/`metric_type`). No whatsapp flavor exposes insights.
//
// Requires `ViewInsights` in the account's group.
func Insights(__c *__client.Client, socialAccountUid string, __query social_account.AccountInsightsQuery) ([]meta.Insight, error) {
	__path := "/social-account/{social_account_uid}/insight"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[[]meta.Insight](__c, "GET", __path, __query, nil)
}
// InsightsHistory Day-by-day history of the account's collected metrics (reach, views,
// follower counts, …), grouped per metric — the charting companion to the
// live insights passthrough. History exists only from the day the account
// was connected. A channel that reports no insights is refused here exactly
// as the live endpoint refuses it.
//
// Requires `ViewInsights` in the account's group.
func InsightsHistory(__c *__client.Client, socialAccountUid string, __query insight.InsightHistoryQuery) ([]insight.InsightSeries, error) {
	__path := "/social-account/{social_account_uid}/insight/history"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[[]insight.InsightSeries](__c, "GET", __path, __query, nil)
}
// List List connected social accounts, optionally filtered by group, each with the
// live session status of its whatsapp session when applicable.
//
// Requires `ViewSocialAccounts`; the list covers only accounts of groups where the caller holds it.
func List(__c *__client.Client, __query social_account.ListSocialAccountsQuery) ([]social_account.SocialAccountResponse, error) {
	__path := "/social-account"
	return __client.Request[[]social_account.SocialAccountResponse](__c, "GET", __path, __query, nil)
}
// NativeDisconnect Close the account's session without unpairing the phone; conflicts if the
// phone already unpaired.
//
// Requires `ConnectSocialAccounts` in the account's group.
func NativeDisconnect(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/native/disconnect"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// NativeLogout Unpair the phone entirely (logout); re-pairing needs a new QR scan;
// conflicts if the phone already unpaired.
//
// Requires `ConnectSocialAccounts` in the account's group.
func NativeLogout(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/native/session"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// NativePairingStatus Poll a pairing's outcome; stop polling once `status` leaves `pairing`.
//
// Requires `ConnectSocialAccounts` in the group the pairing targets.
func NativePairingStatus(__c *__client.Client, pairingHandle string) (social_account.NativePairingStatusResponse, error) {
	__path := "/social-account-pairing/{pairing_handle}/status"
	__path = __strings.Replace(__path, "{pairing_handle}", __client.EncodePath(pairingHandle), 1)
	return __client.Request[social_account.NativePairingStatusResponse](__c, "GET", __path, nil, nil)
}
// NativeQr The current pairing QR to render (null until the first code arrives).
//
// Requires `ConnectSocialAccounts` in the group the pairing targets.
func NativeQr(__c *__client.Client, pairingHandle string) (social_account.NativeQrResponse, error) {
	__path := "/social-account-pairing/{pairing_handle}/qr"
	__path = __strings.Replace(__path, "{pairing_handle}", __client.EncodePath(pairingHandle), 1)
	return __client.Request[social_account.NativeQrResponse](__c, "GET", __path, nil, nil)
}
// NativeReconnect Re-establish the account's session after a drop; conflicts if the phone
// unpaired (re-pair with a new QR instead) or while a whatsapp ban on the
// number is still in force, since logging back in during a ban lengthens it.
//
// Requires `ConnectSocialAccounts` in the account's group.
func NativeReconnect(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/native/reconnect"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// NativeStatus Live session status of a native account; a phone-side unpair reports
// `unpaired` instead of an error.
//
// Requires `ViewSocialAccounts` in the account's group.
func NativeStatus(__c *__client.Client, socialAccountUid string) (social_account.SessionStatus, error) {
	__path := "/social-account/{social_account_uid}/native/status"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[social_account.SessionStatus](__c, "GET", __path, nil, nil)
}
// RefreshProfile Re-read this account's name and picture from its platform now, rather than
// waiting for the daily sweep. Answers `true` when something actually changed.
//
// Never touches the alias — that is yours, and a platform rename is exactly
// what it is meant to survive.
//
// Requires `UpdateSocialAccounts` in the account's group.
func RefreshProfile(__c *__client.Client, socialAccountUid string) (social_account.RefreshProfileResponse, error) {
	__path := "/social-account/{social_account_uid}/profile/refresh"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[social_account.RefreshProfileResponse](__c, "POST", __path, nil, nil)
}
// SetAlias Set or clear an operator's own label for a connected account, on any
// channel. The account's `name` is the platform's and is refreshed from it —
// this is the field a team controls, for telling apart several accounts that
// the platform names alike. Clearing it leaves the platform name alone.
//
// Requires `UpdateSocialAccounts` in the account's group.
func SetAlias(__c *__client.Client, socialAccountUid string, __body social_account.SetSocialAccountAliasRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/alias"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetConversationCap Cap how many conversations the hub may open on this account in any 24
// hours, whoever asks for them (inbox, api key, campaign, import, GoHighLevel),
// or lift the cap with `null`. Only the session-backed whatsapp channels enforce
// it; other channels are refused.
//
// Requires `UpdateSocialAccounts` in the account's group.
func SetConversationCap(__c *__client.Client, socialAccountUid string, __body social_account.SetSocialAccountConversationCapRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/conversation-cap"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetEnabled Enable or disable a connected social account; disabled accounts stop
// ingesting webhooks and reject sends/publishes. Enabling clears a session
// incident the next connect would clear anyway, leaves a reach-out hold to
// expire on its own, and conflicts while a whatsapp ban is still in force. Disabling a native whatsapp account also
// disconnects its session, and enabling connects it again.
//
// Requires `UpdateSocialAccounts` in the account's group.
func SetEnabled(__c *__client.Client, socialAccountUid string, __body social_account.SetSocialAccountEnabledRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/enabled"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetPresence Choose how this native whatsapp account announces itself online: following
// the operators looking at its inbox (the default) or never. Takes effect on
// the live session at once. One change per account every 30 seconds; a
// sooner one is refused with the seconds left. Other channels have no
// presence to steer and are refused.
//
// Requires `UpdateSocialAccounts` in the account's group.
func SetPresence(__c *__client.Client, socialAccountUid string, __body social_account.SetSocialAccountPresenceRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/presence"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// StartNativePairing Start a native (whatsmeow) pairing; returns a handle to poll for the QR and
// the paired account. The account row is created only when the scan succeeds.
//
// Requires `ConnectSocialAccounts` in the named group.
func StartNativePairing(__c *__client.Client, __body social_account.ConnectNativeRequest) (social_account.StartNativePairingResponse, error) {
	__path := "/social-account/native"
	return __client.Request[social_account.StartNativePairingResponse](__c, "POST", __path, nil, __body)
}
// StevoDisconnect Close the instance's session without unpairing the phone. Temporarily
// disabled — always fails with 503.
//
// Requires `ConnectSocialAccounts` in the account's group.
func StevoDisconnect(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/stevo/disconnect"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// StevoLogout Unpair the phone entirely (logout); re-pairing needs a new QR scan.
// Temporarily disabled — always fails with 503.
//
// Requires `ConnectSocialAccounts` in the account's group.
func StevoLogout(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/stevo/session"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// StevoPair Start QR-less pairing: returns the code the user types under "link with
// phone number" on the device. Temporarily disabled — always fails with 503.
//
// Requires `ConnectSocialAccounts` in the account's group.
func StevoPair(__c *__client.Client, socialAccountUid string, __body social_account.StevoPairRequest) (social_account.StevoPairResponse, error) {
	__path := "/social-account/{social_account_uid}/stevo/pair"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[social_account.StevoPairResponse](__c, "POST", __path, nil, __body)
}
// StevoQr Fetch the instance's pairing QR code to render for the admin (valid while
// the instance is connected but not yet logged in). Temporarily disabled —
// always fails with 503.
//
// Requires `ConnectSocialAccounts` in the account's group.
func StevoQr(__c *__client.Client, socialAccountUid string) (social_account.StevoQrResponse, error) {
	__path := "/social-account/{social_account_uid}/stevo/qr"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[social_account.StevoQrResponse](__c, "GET", __path, nil, nil)
}
// StevoReconnect Re-establish the instance's session after a drop; conflicts while a
// whatsapp ban on the number is still in force, since logging back in
// during a ban lengthens it. Temporarily disabled — always fails with 503.
//
// Requires `ConnectSocialAccounts` in the account's group.
func StevoReconnect(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/stevo/reconnect"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// StevoStatus Live connection status of the instance (connected = session up; logged_in
// = phone paired). Reading it also refreshes the account's stored name from
// the paired profile when it changed (the picture follows the daily profile
// sweep, which asks for it only once the gateway has echoed the account's
// own number), and reads the gateway's health report: a reported reach-out
// hold records a `reachout_timelock` session incident on the account, and its
// lifting clears it. Both emit `account_updated` — the poll is the natural
// refresh point, since it already runs whenever the panel is open.
//
// Requires `ViewSocialAccounts` in the account's group.
func StevoStatus(__c *__client.Client, socialAccountUid string) (social_account.StevoStatusResponse, error) {
	__path := "/social-account/{social_account_uid}/stevo/status"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[social_account.StevoStatusResponse](__c, "GET", __path, nil, nil)
}
