// Code generated by tapi. DO NOT EDIT.

package social_account

import (
	__client "integro_sdk"
	__strings "strings"
	domain "integro_sdk/types/domain"
	insight "integro_sdk/types/insight"
	social_account "integro_sdk/types/social_account"
)

// Callback Login redirect target for both flows: consumes the state, reads the grant
// back (Meta: exchanges the code and lists the pages; gateway: lists the
// pages, instagram accounts or whatsapp numbers it covers) and stashes the
// snapshot for review — nothing is registered yet; always redirects the
// browser back to the frontend, with a review token on success.
//
// Public — no authentication required; authorization comes from the one-shot state token issued by `socialAccount.connect`.
func Callback(__c *__client.Client, __query social_account.ConnectCallbackQuery) (struct{}, error) {
	__path := "/social-account/callback"
	return __client.Request[struct{}](__c, "GET", __path, __query, nil)
}
// Connect Start a login flow for a group, returning the dialog URL: the hub's own
// Meta app (`meta`) or the alternate gateway's for one alt channel. The
// callback stashes the granted accounts for review;
// `socialAccount.connectConfirm` is what registers the selection. A login
// naming `social_account_uid` reconnects that account in place; any other
// registers new accounts, one per selection, however many times the same
// identity is already connected.
//
// Requires `ConnectSocialAccounts` in the named group; a `social_account_uid` outside it, or not an account of the login's channel, reads as not found.
func Connect(__c *__client.Client, __body social_account.ConnectSocialAccountRequest) (social_account.ConnectSocialAccountResponse, error) {
	__path := "/social-account/connect"
	return __client.Request[social_account.ConnectSocialAccountResponse](__c, "POST", __path, nil, __body)
}
// ConnectConfirm Register the selected accounts from a stashed grant (one-shot). Pages and
// instagram accounts are selected independently; unselected accounts stay in
// the grant but out of the hub. A gateway selection is completed at the
// gateway and registered under its alt channel.
//
// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
func ConnectConfirm(__c *__client.Client, __body social_account.ConnectConfirmRequest) (social_account.ConnectSocialAccountsConnected, error) {
	__path := "/social-account/connect/confirm"
	return __client.Request[social_account.ConnectSocialAccountsConnected](__c, "POST", __path, nil, __body)
}
// ConnectReview Load a stashed grant for the selection screen: every account it covers,
// plus (Meta grants only) group accounts whose stored token died on the Meta
// side (access removed) — those are flagged for reauthorization. Repeatable;
// only confirm consumes the stash.
//
// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
func ConnectReview(__c *__client.Client, __query social_account.ConnectReviewQuery) (social_account.ConnectReviewResponse, error) {
	__path := "/social-account/connect/review"
	return __client.Request[social_account.ConnectReviewResponse](__c, "GET", __path, __query, nil)
}
// ConnectWhatsapp Connect a WhatsApp Business Account to a group by manual provisioning: the
// hub discovers the WABA's phone numbers with the supplied permanent token,
// subscribes webhooks, and registers one new social account per number — or,
// naming `social_account_uid`, refreshes that account from its number alone.
//
// Requires `ConnectSocialAccounts` in the named group; a `social_account_uid` outside it, or not an official whatsapp account, reads as not found.
func ConnectWhatsapp(__c *__client.Client, __body social_account.ConnectWhatsappRequest) (social_account.ConnectWhatsappResponse, error) {
	__path := "/social-account/whatsapp"
	return __client.Request[social_account.ConnectWhatsappResponse](__c, "POST", __path, nil, __body)
}
// Count Count connected social accounts, optionally filtered by groups.
//
// Requires `ViewSocialAccounts`; the count covers only accounts of groups where the caller holds it.
func Count(__c *__client.Client, __query social_account.ListSocialAccountsQuery) (uint64, error) {
	__path := "/social-account/count"
	return __client.Request[uint64](__c, "GET", __path, __query, nil)
}
// Delete Disconnect a social account, deleting its conversations, messages, and
// posts with it. Native whatsapp accounts also unpair the phone
// (best-effort, in the background).
//
// Requires `DeleteSocialAccounts` in the account's group.
func Delete(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Exposure Read the account's exposure telemetry, hour by hour over the requested
// period (at most 92 days): how many platform lookups it made (usync number
// checks, profile pictures, presence subscriptions), its sends by origin,
// first-time contacts, whatsapp 429 and 463/475 answers, slow send acks and
// sends still without a delivery receipt an hour later, plus the alerts the
// last 24 hours raise right now. Only the session-backed whatsapp channels
// are metered.
//
// Requires `ViewSocialAccounts` in the account's group.
func Exposure(__c *__client.Client, socialAccountUid string, __query social_account.ExposureQuery) (domain.ExposureReport, error) {
	__path := "/social-account/{social_account_uid}/exposure"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[domain.ExposureReport](__c, "GET", __path, __query, nil)
}
// Get Fetch a single connected social account by uid, with the live session
// status of its whatsapp session when applicable.
//
// Requires `ViewSocialAccounts` in the account's group.
func Get(__c *__client.Client, socialAccountUid string) (social_account.SocialAccountResponse, error) {
	__path := "/social-account/{social_account_uid}"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[social_account.SocialAccountResponse](__c, "GET", __path, nil, nil)
}
// GroupReferences List what still acts on this account from inside its group — GoHighLevel
// locations, campaigns that are not canceled and contact imports that are not
// finished — split into what can move with it and what other accounts of the
// group also use. Read it before moving the account to another group.
//
// Session users only. Requires `UpdateSocialAccounts` in the account's group.
func GroupReferences(__c *__client.Client, socialAccountUid string) (domain.AccountReferences, error) {
	__path := "/social-account/{social_account_uid}/group/reference"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[domain.AccountReferences](__c, "GET", __path, nil, nil)
}
// InsightsHistory Day-by-day history of the account's collected metrics, in its channel's
// own vocabulary. History exists from the day the account was connected; the
// newest day is often still partial. A channel that reports no metrics is
// refused.
//
// Requires `ViewInsights` in the account's group.
func InsightsHistory(__c *__client.Client, socialAccountUid string, __query insight.InsightHistoryQuery) (insight.AccountInsightHistory, error) {
	__path := "/social-account/{social_account_uid}/insight/history"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[insight.AccountInsightHistory](__c, "GET", __path, __query, nil)
}
// List List connected social accounts, optionally filtered by groups, each with the
// live session status of its whatsapp session when applicable.
//
// Requires `ViewSocialAccounts`; the list covers only accounts of groups where the caller holds it.
func List(__c *__client.Client, __query social_account.ListSocialAccountsQuery) ([]social_account.SocialAccountResponse, error) {
	__path := "/social-account"
	return __client.Request[[]social_account.SocialAccountResponse](__c, "GET", __path, __query, nil)
}
// NativeDisconnect Close the account's session without unpairing the phone; conflicts if the
// phone already unpaired.
//
// Requires `ConnectSocialAccounts` in the account's group.
func NativeDisconnect(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/native/disconnect"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// NativeLogout Unpair the phone entirely (logout); re-pairing needs a new QR scan;
// conflicts if the phone already unpaired.
//
// Requires `ConnectSocialAccounts` in the account's group.
func NativeLogout(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/native/session"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// NativePairingStatus Poll a pairing's outcome; stop polling once `status` leaves `pairing`.
//
// Requires `ConnectSocialAccounts` in the group the pairing targets.
func NativePairingStatus(__c *__client.Client, pairingHandle string) (social_account.NativePairingStatusResponse, error) {
	__path := "/social-account-pairing/{pairing_handle}/status"
	__path = __strings.Replace(__path, "{pairing_handle}", __client.EncodePath(pairingHandle), 1)
	return __client.Request[social_account.NativePairingStatusResponse](__c, "GET", __path, nil, nil)
}
// NativeQr The current pairing QR to render (null until the first code arrives).
//
// Requires `ConnectSocialAccounts` in the group the pairing targets.
func NativeQr(__c *__client.Client, pairingHandle string) (social_account.NativeQrResponse, error) {
	__path := "/social-account-pairing/{pairing_handle}/qr"
	__path = __strings.Replace(__path, "{pairing_handle}", __client.EncodePath(pairingHandle), 1)
	return __client.Request[social_account.NativeQrResponse](__c, "GET", __path, nil, nil)
}
// NativeReconnect Re-establish the account's session after a drop; conflicts if the phone
// unpaired (re-pair with a new QR instead) or while a whatsapp ban on the
// number is still in force, since logging back in during a ban lengthens it.
//
// Requires `ConnectSocialAccounts` in the account's group.
func NativeReconnect(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/native/reconnect"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// NativeRenewQr Ask the phone for a fresh QR code on a pairing whose code expired; the
// next `native/qr` poll carries it. Codes never renew on their own. The
// pairing's ten-minute window does not restart.
//
// Requires `ConnectSocialAccounts` in the group the pairing targets; a pairing that already ended reads as not found.
func NativeRenewQr(__c *__client.Client, pairingHandle string) (struct{}, error) {
	__path := "/social-account-pairing/{pairing_handle}/qr/renew"
	__path = __strings.Replace(__path, "{pairing_handle}", __client.EncodePath(pairingHandle), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// NativeStatus Live session status of a native account; a phone-side unpair reports
// `unpaired` instead of an error.
//
// Requires `ViewSocialAccounts` in the account's group.
func NativeStatus(__c *__client.Client, socialAccountUid string) (social_account.SessionStatus, error) {
	__path := "/social-account/{social_account_uid}/native/status"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[social_account.SessionStatus](__c, "GET", __path, nil, nil)
}
// RefreshProfile Re-read this account's name and picture from its platform now, rather than
// waiting for the daily sweep. Answers `true` when something actually changed.
//
// Never touches the alias — that is yours, and a platform rename is exactly
// what it is meant to survive.
//
// Requires `UpdateSocialAccounts` in the account's group.
func RefreshProfile(__c *__client.Client, socialAccountUid string) (social_account.RefreshProfileResponse, error) {
	__path := "/social-account/{social_account_uid}/profile/refresh"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[social_account.RefreshProfileResponse](__c, "POST", __path, nil, nil)
}
// SetAlias Set or clear an operator's own label for a connected account, on any
// channel. The account's `name` is the platform's and is refreshed from it —
// this is the field a team controls, for telling apart several accounts that
// the platform names alike. Clearing it leaves the platform name alone.
//
// Requires `UpdateSocialAccounts` in the account's group.
func SetAlias(__c *__client.Client, socialAccountUid string, __body social_account.SetSocialAccountAliasRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/alias"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetConversationCap Cap how many conversations the hub may open on this account in any 24
// hours, whoever asks for them (inbox, api key, campaign, import, GoHighLevel),
// or lift the cap with `null`. Only the session-backed whatsapp channels enforce
// it; other channels are refused.
//
// Requires `UpdateSocialAccounts` in the account's group.
func SetConversationCap(__c *__client.Client, socialAccountUid string, __body social_account.SetSocialAccountConversationCapRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/conversation-cap"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetEnabled Enable or disable a connected social account; disabled accounts stop
// ingesting webhooks and reject sends/publishes. Enabling clears a session
// incident the next connect would clear anyway, leaves a reach-out hold to
// expire on its own, and conflicts while a whatsapp ban is still in force. Disabling a native whatsapp account also
// disconnects its session, and enabling connects it again.
//
// Requires `UpdateSocialAccounts` in the account's group.
func SetEnabled(__c *__client.Client, socialAccountUid string, __body social_account.SetSocialAccountEnabledRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/enabled"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetGroup Move an account to another group, together with its conversations, messages,
// posts and calls, whose media becomes visible to the new group and stops being
// visible to the old one. Refused while a campaign or contact import also uses
// other accounts of the current group, and — unless `move_references` is set —
// while a GoHighLevel location, campaign or contact import acts only on this
// account; with it set, those move along. Canceled campaigns, and contact
// imports that are done or canceled, stay where they ran; a done campaign
// moves, since it can run again. Watchers of the old group see the account
// removed, and the move is recorded in the audit of both groups.
//
// Session users only. Requires `UpdateSocialAccounts` in both the account's current group and the target group.
func SetGroup(__c *__client.Client, socialAccountUid string, __body social_account.SetSocialAccountGroupRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/group"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetPresence Choose how this native whatsapp account announces itself online: following
// the operators looking at its inbox (the default) or never. Takes effect on
// the live session at once. One change per account every 30 seconds; a
// sooner one is refused with the seconds left. Other channels have no
// presence to steer and are refused.
//
// Requires `UpdateSocialAccounts` in the account's group.
func SetPresence(__c *__client.Client, socialAccountUid string, __body social_account.SetSocialAccountPresenceRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/presence"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// StartNativePairing Start a native (whatsmeow) pairing; returns a handle to poll for the QR and
// the paired account. The account row is created only when the scan succeeds,
// and every scan is a new account — the same number paired twice is two
// accounts — unless `social_account_uid` names the one to pair again, whose
// number the scan must match.
//
// Requires `ConnectSocialAccounts` in the named group; a `social_account_uid` outside it, or not a native account, reads as not found.
func StartNativePairing(__c *__client.Client, __body social_account.ConnectNativeRequest) (social_account.StartNativePairingResponse, error) {
	__path := "/social-account/native"
	return __client.Request[social_account.StartNativePairingResponse](__c, "POST", __path, nil, __body)
}
