// Code generated by tapir. DO NOT EDIT.

package types

// The order the account-wide audience source walks the inbox in — the
// "the N oldest / the N most recently active" pick. Created-time orders
// read contact age; activity orders read engagement recency.
type AudienceOrder string

const (
	AudienceOrderOldest AudienceOrder = "oldest"
	AudienceOrderNewest AudienceOrder = "newest"
	AudienceOrderInactive AudienceOrder = "inactive"
	AudienceOrderActive AudienceOrder = "active"
)
