// Code generated by tapir. DO NOT EDIT.

package types

type AuditResource string

const (
	AuditResourceAuth AuditResource = "auth"
	AuditResourceUser AuditResource = "user"
	AuditResourceGroup AuditResource = "group"
	AuditResourceUserInvite AuditResource = "user_invite"
	AuditResourceUserSession AuditResource = "user_session"
	AuditResourceRateLimit AuditResource = "rate_limit"
	AuditResourceApiKey AuditResource = "api_key"
	AuditResourceEmail AuditResource = "email"
	AuditResourceUserMfa AuditResource = "user_mfa"
	AuditResourceIssue AuditResource = "issue"
	AuditResourceSocialAccount AuditResource = "social_account"
	AuditResourceMessage AuditResource = "message"
	AuditResourcePost AuditResource = "post"
	AuditResourceWebhook AuditResource = "webhook"
	AuditResourceComment AuditResource = "comment"
	AuditResourceMention AuditResource = "mention"
	AuditResourceMedia AuditResource = "media"
	AuditResourceTemplate AuditResource = "template"
	AuditResourceConversation AuditResource = "conversation"
	AuditResourceGoogleAccount AuditResource = "google_account"
	AuditResourceUserGroup AuditResource = "user_group"
	AuditResourceCall AuditResource = "call"
	AuditResourceGhlLocation AuditResource = "ghl_location"
	AuditResourceContactImport AuditResource = "contact_import"
	AuditResourceCampaign AuditResource = "campaign"
	AuditResourceUnknown AuditResource = "unknown"
)
