// Code generated by tapir. DO NOT EDIT.

package types

type AuditAction string

const (
	AuditActionLogin AuditAction = "login"
	AuditActionLogout AuditAction = "logout"
	AuditActionLogoutAll AuditAction = "logout_all"
	AuditActionForgotPassword AuditAction = "forgot_password"
	AuditActionResetPassword AuditAction = "reset_password"
	AuditActionRegister AuditAction = "register"
	AuditActionCreate AuditAction = "create"
	AuditActionUpdate AuditAction = "update"
	AuditActionDelete AuditAction = "delete"
	AuditActionActivate AuditAction = "activate"
	AuditActionDeactivate AuditAction = "deactivate"
	AuditActionChangePassword AuditAction = "change_password"
	AuditActionRevoke AuditAction = "revoke"
	AuditActionRotate AuditAction = "rotate"
	AuditActionGenerate AuditAction = "generate"
	AuditActionSetPermissions AuditAction = "set_permissions"
	AuditActionSetEnabled AuditAction = "set_enabled"
	AuditActionRetry AuditAction = "retry"
	AuditActionEnrollUserMfa AuditAction = "enroll_user_mfa"
	AuditActionRemoveUserMfa AuditAction = "remove_user_mfa"
	AuditActionUserMfaChallenge AuditAction = "user_mfa_challenge"
	AuditActionUserMfaVerify AuditAction = "user_mfa_verify"
	AuditActionResetUserMfa AuditAction = "reset_user_mfa"
	AuditActionAddMember AuditAction = "add_member"
	AuditActionSetMemberRole AuditAction = "set_member_role"
	AuditActionRemoveMember AuditAction = "remove_member"
	AuditActionSetSuperAdmin AuditAction = "set_super_admin"
	AuditActionUnknown AuditAction = "unknown"
)
