// Code generated by tapir. DO NOT EDIT.

package types

// Where a live call currently is. The hub's own vocabulary, deliberately
// mirroring the bridge's phases rather than re-exporting them: the bridge type
// is deserialize-only and cannot cross the API, and this way a phase whatsapp
// adds later arrives as [`CallPhase::Other`] instead of breaking the wire.
//
// Never stored — a finished call is described by its outcome and timestamps.
type CallPhase = interface{}
