// Code generated by tapir. DO NOT EDIT.

package types

// One row's outcome, on two deliberately separate axes. The parse verdicts
// (`MissingPhone`, `InvalidPhone`, `InvalidName`, `DuplicateInFile`) are
// final at upload and editable while the import is staged; the platform
// verdicts (`Imported`, `NotOnWhatsapp`, `CheckFailed`) are the loader's.
// `CheckFailed` is distinct from `NotOnWhatsapp` on purpose: one is an
// answer, the other is the absence of one.
type ContactImportRowVerdict string

const (
	ContactImportRowVerdictPending ContactImportRowVerdict = "pending"
	ContactImportRowVerdictMissingPhone ContactImportRowVerdict = "missing_phone"
	ContactImportRowVerdictInvalidPhone ContactImportRowVerdict = "invalid_phone"
	ContactImportRowVerdictInvalidName ContactImportRowVerdict = "invalid_name"
	ContactImportRowVerdictDuplicateInFile ContactImportRowVerdict = "duplicate_in_file"
	ContactImportRowVerdictImported ContactImportRowVerdict = "imported"
	ContactImportRowVerdictNotOnWhatsapp ContactImportRowVerdict = "not_on_whatsapp"
	ContactImportRowVerdictCheckFailed ContactImportRowVerdict = "check_failed"
	ContactImportRowVerdictSkipped ContactImportRowVerdict = "skipped"
)
