// Code generated by tapir. DO NOT EDIT.

package types

type HttpRateLimitScope string

const (
	HttpRateLimitScopeGlobal HttpRateLimitScope = "global"
	HttpRateLimitScopeAnonymous HttpRateLimitScope = "anonymous"
	HttpRateLimitScopeGroup HttpRateLimitScope = "group"
)
