// Code generated by tapir. DO NOT EDIT.

package types

// Content that only arrives inbound. There is no send call for these shapes
// — a send request takes [`OutboundContent`] and cannot even express them.
type InboundContent = interface{}
