// Code generated by tapir. DO NOT EDIT.

package types

type IssueCategory string

const (
	IssueCategoryBug IssueCategory = "bug"
	IssueCategoryPerformance IssueCategory = "performance"
	IssueCategorySuggestion IssueCategory = "suggestion"
	IssueCategoryUi IssueCategory = "ui"
	IssueCategoryOther IssueCategory = "other"
)
