// Code generated by tapir. DO NOT EDIT.

package types

import (
	primitives "integro_sdk/types/primitives"
)

type IssueScreenshot struct {
	Uid primitives.Uid `json:"uid"`
	Filename string `json:"filename"`
	ContentType string `json:"content_type"`
	Size uint64 `json:"size"`
}
