// Code generated by tapir. DO NOT EDIT.

package types

// The storage/DTO axis: the role one `user_group` membership holds, stored as
// TEXT. Splitting it from [`UserRole`] is what makes `SuperAdmin`
// unrepresentable as a membership — the DB CHECK and strict deserialization
// both reject it.
type MembershipRole string

const (
	MembershipRoleAdmin MembershipRole = "admin"
	MembershipRoleUser MembershipRole = "user"
)
