// Code generated by tapir. DO NOT EDIT.

package types

type MessageStatus string

const (
	MessageStatusReceived MessageStatus = "received"
	MessageStatusPending MessageStatus = "pending"
	MessageStatusSent MessageStatus = "sent"
	MessageStatusDelivered MessageStatus = "delivered"
	MessageStatusRead MessageStatus = "read"
	MessageStatusFailed MessageStatus = "failed"
	MessageStatusCanceled MessageStatus = "canceled"
)
