// Code generated by tapir. DO NOT EDIT.

package types

// Who produced an outbound message row — the attribution consumers (CRMs)
// use to tell machine sends from human takeovers without correlation
// heuristics. `None` on inbound rows and on rows stored before the field
// existed.
type MessageSentBy string

const (
	MessageSentByApiKey MessageSentBy = "api_key"
	MessageSentByUser MessageSentBy = "user"
	MessageSentByPlatform MessageSentBy = "platform"
	MessageSentByGhl MessageSentBy = "ghl"
	MessageSentByCampaign MessageSentBy = "campaign"
)
