// Code generated by tapir. DO NOT EDIT.

package types

// A quick-reply chip attached to an outbound message; tapping it sends the
// payload back as an [`InboundContent::QuickReply`] message.
type QuickReply struct {
	Title string `json:"title"`
	Payload string `json:"payload"`
}
