// Code generated by tapir. DO NOT EDIT.

package types

// What a rate-limit rule targets *and* the budget it enforces, stored as
// tagged JSON in `rate_limit_rule.rule`. New limiting cases are new variants —
// the table, endpoints, and UI stay untouched.
//
// Each variant carries only the fields that mean something for it, so the
// budget shapes that do not belong together cannot be written down: an action
// rule with byte ceilings, a paced channel with a request budget, an HTTP
// scope disagreeing with its group. That is why pacing lives here at all —
// with the budget in shared columns it never fit.
type RateLimitRuleKind = interface{}
