// Code generated by tapir. DO NOT EDIT.

package types

// Where a conversation (re-)entry came from, normalized across every channel
// that reports one. Kind-tagged so consumers distinguish origins without
// probing fields: each variant carries exactly what its origin provides.
type Referral = interface{}
