// Code generated by tapir. DO NOT EDIT.

package types

// One card of a generic template carousel.
type TemplateCard struct {
	Title string `json:"title"`
	Subtitle *string `json:"subtitle"`
	ImageUrl *string `json:"image_url"`
	Buttons []TemplateButton `json:"buttons"`
}
