// Code generated by tapir. DO NOT EDIT.

package types

type UserInviteEmailStatus string

const (
	UserInviteEmailStatusPendingSend UserInviteEmailStatus = "pending_send"
	UserInviteEmailStatusSent UserInviteEmailStatus = "sent"
	UserInviteEmailStatusFailed UserInviteEmailStatus = "failed"
)
