// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	domain "integro_sdk/types/domain"
)

// One channel and the platform rules the hub enforces on it.
type ChannelRule struct {
	Channel domain.Channel `json:"channel"`
	Family domain.ChannelFamily `json:"family"`
	Transport domain.Transport `json:"transport"`
	// What a conversation accepts after the contact's last inbound message;
	// the send routes refuse what it does not pass.
	ResponseWindow domain.ResponseWindow `json:"response_window"`
}
