// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	primitives "integro_sdk/types/primitives"
)

type ConnectStevoResponse struct {
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	Connected bool `json:"connected"`
	// False until a phone is paired — fetch the QR (or a pairing code) next.
	LoggedIn bool `json:"logged_in"`
}
