// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	primitives "integro_sdk/types/primitives"
)

type ConnectWhatsappRequest struct {
	GroupUid primitives.Uid `json:"group_uid"`
	// The WhatsApp Business Account id (from Business Manager).
	WabaId string `json:"waba_id"`
	// A permanent system user token holding `whatsapp_business_messaging` +
	// `whatsapp_business_management`, generated once in Business Manager.
	AccessToken string `json:"access_token"`
}
