// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	primitives "integro_sdk/types/primitives"
)

type ConnectSocialAccountRequest struct {
	GroupUid primitives.Uid `json:"group_uid"`
}
