// Code generated by tapir. DO NOT EDIT.

package social_account

type ConnectConfirmRequest struct {
	Token string `json:"token"`
	// The `external_id`s to register — pages and instagram accounts are
	// selected independently.
	ExternalIds []string `json:"external_ids"`
}
