// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	primitives "integro_sdk/types/primitives"
)

type ExposureQuery struct {
	// Start of the period; defaults to seven days before `until`.
	Since *primitives.Timestamp `json:"since"`
	// End of the period; defaults to now.
	Until *primitives.Timestamp `json:"until"`
}
