// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	domain "integro_sdk/types/domain"
)

// One account the stashed grant covers, for the selection screen.
type GrantAccount struct {
	Channel domain.Channel `json:"channel"`
	ExternalId string `json:"external_id"`
	Name string `json:"name"`
	Username *string `json:"username"`
	// How many accounts of this identity the target group already holds;
	// confirming adds another, independent one, unless the login named the
	// account it reconnects.
	Connections uint32 `json:"connections"`
}
