// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	types "integro_sdk/types/types"
)

// One account the stashed grant covers, for the selection screen.
type GrantAccount struct {
	Channel types.Channel `json:"channel"`
	ExternalId string `json:"external_id"`
	Name string `json:"name"`
	Username *string `json:"username"`
	// Already registered in the target group — confirming it refreshes the
	// stored token and display fields.
	Connected bool `json:"connected"`
	// Registered in another group: shown locked, never selectable (accounts
	// cannot be moved between groups by a connect).
	OtherGroup bool `json:"other_group"`
}
