// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	primitives "integro_sdk/types/primitives"
)

type NativePairingStatusResponse struct {
	Status NativePairingStatus `json:"status"`
	// Set once `status` is `paired`.
	SocialAccountUid *primitives.Uid `json:"social_account_uid"`
}
