// Code generated by tapir. DO NOT EDIT.

package social_account

// Progress of a native QR pairing.
type NativePairingStatus string

const (
	NativePairingStatusPairing NativePairingStatus = "pairing"
	NativePairingStatusPaired NativePairingStatus = "paired"
	NativePairingStatusFailed NativePairingStatus = "failed"
)
