// Code generated by tapir. DO NOT EDIT.

package social_account

type RefreshProfileResponse struct {
	// Whether the platform reported a name or picture different from the stored one.
	Changed bool `json:"changed"`
}
