// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

// A group account whose stored token no longer works — access was removed
// on the Meta side. Flagged `needs_reauth`; reconnecting (with the account
// selected again) is the cure.
type RemovedAccess struct {
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	Channel domain.Channel `json:"channel"`
	Name string `json:"name"`
}
