// Code generated by tapir. DO NOT EDIT.

package social_account

// Channel-agnostic whatsapp session state, precomputed so the frontend maps
// each value straight to a badge and action — no per-channel logic.
type SessionStatus string

const (
	SessionStatusConnected SessionStatus = "connected"
	SessionStatusDisconnected SessionStatus = "disconnected"
	SessionStatusUnpaired SessionStatus = "unpaired"
	SessionStatusUnavailable SessionStatus = "unavailable"
)
