// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	primitives "integro_sdk/types/primitives"
)

type SetSocialAccountGroupRequest struct {
	// The group the account moves into.
	GroupUid primitives.Uid `json:"group_uid"`
	// Carry along the GoHighLevel locations, campaigns and contact imports that
	// act only on this account. Without it, the move is refused while any exist.
	MoveReferences bool `json:"move_references"`
}
