// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	domain "integro_sdk/types/domain"
)

type SetSocialAccountPresenceRequest struct {
	Policy domain.PresencePolicy `json:"policy"`
}
