// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	primitives "integro_sdk/types/primitives"
)

type SetSocialAccountConversationCapRequest struct {
	// Most conversations the hub may open on the account in any 24 hours;
	// `null` lifts the cap.
	Cap *primitives.Number1_100000 `json:"cap"`
}
