// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	domain "integro_sdk/types/domain"
)

type SocialAccountResponse struct {
	domain.SocialAccount
	// Live session status for the session-backed whatsapp channels
	// (native/stevo); null for channels without a session concept.
	Session *SessionStatus `json:"session"`
}
