// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	database "integro_sdk/types/database"
)

type SocialAccountResponse struct {
	database.SocialAccount
	// Live session status for the session-backed whatsapp channels
	// (native/stevo); null for channels without a session concept.
	Session *SessionStatus `json:"session"`
}
