// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	primitives "integro_sdk/types/primitives"
)

type StartNativePairingResponse struct {
	// Poll `native/{handle}/qr` and `native/{handle}/status` with this.
	PairingHandle primitives.Uid `json:"pairing_handle"`
}
