// Code generated by tapir. DO NOT EDIT.

package social_account

import (
	primitives "integro_sdk/types/primitives"
)

type StevoPairRequest struct {
	// The phone to pair, in E.164 (`+<country code><number>`).
	Phone primitives.Phone `json:"phone"`
}
