// Code generated by tapir. DO NOT EDIT.

package social_account

type StevoPairResponse struct {
	// The code the user types under "link with phone number" on the device.
	Code string `json:"code"`
}
