// Code generated by tapi. DO NOT EDIT.

package campaign

import (
	__client "integro_sdk"
	__strings "strings"
	campaign "integro_sdk/types/campaign"
	domain "integro_sdk/types/domain"
)

// AddRecipients Append an audience to the end of the queue — the same sources as a
// build, added to what is there. Draft, paused or done; conversations
// already in the ledger (queued or reached) are skipped.
//
// Requires `ManageCampaigns` in the campaign's group.
func AddRecipients(__c *__client.Client, campaignUid string, __body campaign.AudienceRequest) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}/recipient"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "POST", __path, nil, __body)
}
// BuildAudience Build (or rebuild) the audience: the source resolves to numbers, each
// assigned an account (balanced, preferring one that already has the
// conversation), frozen as the recipient ledger. Draft only — past a start
// the ledger is the record of who was reached; use `addRecipients`.
//
// Requires `ManageCampaigns` in the campaign's group.
func BuildAudience(__c *__client.Client, campaignUid string, __body campaign.AudienceRequest) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}/audience"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "POST", __path, nil, __body)
}
// Cancel Cancel the campaign: queued recipients become `canceled`, and campaign
// messages still waiting in the send queue are pulled back. Terminal;
// messages already sent stay.
//
// Requires `ManageCampaigns` in the campaign's group.
func Cancel(__c *__client.Client, campaignUid string) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}/cancel"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "POST", __path, nil, nil)
}
// Create Create a draft campaign in a group. Its accounts are the group's whatsapp
// accounts (native or Stevo, mixed freely); nothing sends until templates,
// accounts and an audience exist and `start` passes the preflight.
//
// Requires `ManageCampaigns` in the target group; group-scoped API keys create into their own group, others must name it.
func Create(__c *__client.Client, __body campaign.CreateCampaignRequest) (campaign.CampaignDetail, error) {
	__path := "/campaign"
	return __client.Request[campaign.CampaignDetail](__c, "POST", __path, nil, __body)
}
// Delete Delete a campaign and its ledger. Refused while running — pause or cancel
// first. Messages already sent stay in their conversations.
//
// Requires `ManageCampaigns` in the campaign's group.
func Delete(__c *__client.Client, campaignUid string) (struct{}, error) {
	__path := "/campaign/{campaign_uid}"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Get One campaign with its derived counters — the page's poll.
//
// Requires `ViewCampaigns` in the campaign's group.
func Get(__c *__client.Client, campaignUid string) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "GET", __path, nil, nil)
}
// List List campaigns, newest first, optionally one group's.
//
// Requires `ViewCampaigns`; the list covers only campaigns of groups where the caller holds it.
func List(__c *__client.Client, __query campaign.ListCampaignsQuery) ([]campaign.CampaignDetail, error) {
	__path := "/campaign"
	return __client.Request[[]campaign.CampaignDetail](__c, "GET", __path, __query, nil)
}
// Pause Pause the drip: queued recipients stay queued, nothing more is sent until
// a resume. Messages already in the send queue still go out.
//
// Requires `ManageCampaigns` in the campaign's group.
func Pause(__c *__client.Client, campaignUid string) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}/pause"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "POST", __path, nil, nil)
}
// Preflight The start gate's dry run: hard errors, foreseeable skips, and the sending
// estimate.
//
// Requires `ViewCampaigns` in the campaign's group.
func Preflight(__c *__client.Client, campaignUid string) (campaign.PreflightReport, error) {
	__path := "/campaign/{campaign_uid}/preflight"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.PreflightReport](__c, "GET", __path, nil, nil)
}
// Recipients A page of the recipient ledger in drip order, optionally one status.
//
// Requires `ViewCampaigns` in the campaign's group.
func Recipients(__c *__client.Client, campaignUid string, __query campaign.ListRecipientsQuery) ([]domain.CampaignRecipient, error) {
	__path := "/campaign/{campaign_uid}/recipient"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[[]domain.CampaignRecipient](__c, "GET", __path, __query, nil)
}
// Redistribute Hand the whole queue out again across the current accounts: balanced,
// preferring an account that already has each number's conversation. For
// after accounts were added, or a queue that grew lopsided. Draft, paused
// and done only.
//
// Requires `ManageCampaigns` in the campaign's group.
func Redistribute(__c *__client.Client, campaignUid string) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}/redistribute"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "POST", __path, nil, nil)
}
// RemoveRecipients Drop queued recipients from the audience. Draft, paused or done; rows that
// already ran stay as history.
//
// Requires `ManageCampaigns` in the campaign's group.
func RemoveRecipients(__c *__client.Client, campaignUid string, __body campaign.RemoveRecipientsRequest) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}/recipient/remove"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "POST", __path, nil, __body)
}
// Resume Resume a paused drip where it stood.
//
// Requires `ManageCampaigns` in the campaign's group.
func Resume(__c *__client.Client, campaignUid string) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}/resume"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "POST", __path, nil, nil)
}
// SetAccounts Replace the participating account set. Draft, paused and done only; every
// account must be a whatsapp (native or Stevo) account of the campaign's
// group. Queued recipients of an account taken out are handed to the
// accounts that remain, balanced and preferring one that already knows
// them; rows that already ran stay. The set may be empty — the queue then
// waits for the next account change — and the campaign cannot start until
// it has one.
//
// Requires `ManageCampaigns` in the campaign's group.
func SetAccounts(__c *__client.Client, campaignUid string, __body campaign.SetAccountsRequest) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}/account"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "PUT", __path, nil, __body)
}
// Start Start the drip, from draft or from done — a done campaign restarts on
// whatever is still queued, never on who was already reached. Runs the
// preflight and refuses on any error; from then on the dispatcher sends
// one message per interval inside the window.
//
// Requires `ManageCampaigns` in the campaign's group.
func Start(__c *__client.Client, campaignUid string) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}/start"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "POST", __path, nil, nil)
}
// Stats Delivery truth: recipient status crossed with each message's own platform
// status, plus the reply count.
//
// Requires `ViewCampaigns` in the campaign's group.
func Stats(__c *__client.Client, campaignUid string) (campaign.CampaignStats, error) {
	__path := "/campaign/{campaign_uid}/stats"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignStats](__c, "GET", __path, nil, nil)
}
// Test Send one template to one conversation, now, outside any schedule — the
// operator's own eyes on the rendered result.
//
// Requires `ManageCampaigns` in the campaign's group; the conversation must belong to the same group and channel.
func Test(__c *__client.Client, campaignUid string, __body campaign.TestSendRequest) (domain.MessageWithContext, error) {
	__path := "/campaign/{campaign_uid}/test"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[domain.MessageWithContext](__c, "POST", __path, nil, __body)
}
// Update Replace the campaign's schedule, ceilings and rotation. Draft, paused and
// done only — a running drip is retuned by pausing first.
//
// Requires `ManageCampaigns` in the campaign's group.
func Update(__c *__client.Client, campaignUid string, __body campaign.UpdateCampaignRequest) (campaign.CampaignDetail, error) {
	__path := "/campaign/{campaign_uid}"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignDetail](__c, "PUT", __path, nil, __body)
}
