// Code generated by tapi. DO NOT EDIT.

package pacing

import (
	__client "integro_sdk"
	__strings "strings"
	database "integro_sdk/types/database"
	rate_limit "integro_sdk/types/rate_limit"
)

// Create Start pacing outbound sends on a channel. Every send is queued either way —
// `message.send` stores the message as `pending` and returns immediately — so
// a rule decides how fast the per-account queue drains, not whether one is
// used. Without a rule (the default) the queue drains as fast as it can.
//
// Requires `CreateRateLimits`, which only platform staff hold.
func Create(__c *__client.Client, __body rate_limit.CreateChannelPacingRequest) (rate_limit.CreateChannelPacingResponse, error) {
	__path := "/rate-limit/pacing"
	return __client.Request[rate_limit.CreateChannelPacingResponse](__c, "POST", __path, nil, __body)
}
// Delete Stop pacing a channel: its queue drains as fast as it can again. Messages
// already queued still drain, without the delay.
//
// Requires `DeleteRateLimits`, which only platform staff hold.
func Delete(__c *__client.Client, channel string) (struct{}, error) {
	__path := "/rate-limit/pacing/{channel}"
	__path = __strings.Replace(__path, "{channel}", __client.EncodePath(channel), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Get Fetch a single channel pacing rule by uid.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func Get(__c *__client.Client, channel string) (database.ChannelPacingRule, error) {
	__path := "/rate-limit/pacing/{channel}"
	__path = __strings.Replace(__path, "{channel}", __client.EncodePath(channel), 1)
	return __client.Request[database.ChannelPacingRule](__c, "GET", __path, nil, nil)
}
// List List every channel pacing rule. Channels with no rule are unpaced.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func List(__c *__client.Client) ([]database.ChannelPacingRule, error) {
	__path := "/rate-limit/pacing"
	return __client.Request[[]database.ChannelPacingRule](__c, "GET", __path, nil, nil)
}
// Update Update a channel's pacing. Takes effect on the next send; messages already
// queued keep draining under the new timing.
//
// Requires `UpdateRateLimits`, which only platform staff hold.
func Update(__c *__client.Client, channel string, __body rate_limit.UpdateChannelPacingRequest) (struct{}, error) {
	__path := "/rate-limit/pacing/{channel}"
	__path = __strings.Replace(__path, "{channel}", __client.EncodePath(channel), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
