// Code generated by tapi. DO NOT EDIT.

package pacing

import (
	"integro_sdk"
	"strings"
	database "integro_sdk/types/database"
	rate_limit "integro_sdk/types/rate_limit"
)

// Create Start pacing outbound sends on a channel. Every send is queued either way —
// `message.send` stores the message as `pending` and returns immediately — so
// a rule decides how fast the per-account queue drains, not whether one is
// used. Without a rule (the default) the queue drains as fast as it can.
//
// Requires `CreateRateLimits`, which only platform staff hold.
func Create(c *client.Client, body rate_limit.CreateChannelPacingRequest) (rate_limit.CreateChannelPacingResponse, error) {
	__path := "/rate-limit/pacing"
	return client.Request[rate_limit.CreateChannelPacingResponse](c, "POST", __path, nil, body)
}
// Delete Stop pacing a channel: its queue drains as fast as it can again. Messages
// already queued still drain, without the delay.
//
// Requires `DeleteRateLimits`, which only platform staff hold.
func Delete(c *client.Client, channel string) (struct{}, error) {
	__path := "/rate-limit/pacing/{channel}"
	__path = strings.Replace(__path, "{channel}", client.EncodePath(channel), 1)
	return client.Request[struct{}](c, "DELETE", __path, nil, nil)
}
// Get Fetch a single channel pacing rule by uid.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func Get(c *client.Client, channel string) (database.ChannelPacingRule, error) {
	__path := "/rate-limit/pacing/{channel}"
	__path = strings.Replace(__path, "{channel}", client.EncodePath(channel), 1)
	return client.Request[database.ChannelPacingRule](c, "GET", __path, nil, nil)
}
// List List every channel pacing rule. Channels with no rule are unpaced.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func List(c *client.Client) ([]database.ChannelPacingRule, error) {
	__path := "/rate-limit/pacing"
	return client.Request[[]database.ChannelPacingRule](c, "GET", __path, nil, nil)
}
// Update Update a channel's pacing. Takes effect on the next send; messages already
// queued keep draining under the new timing.
//
// Requires `UpdateRateLimits`, which only platform staff hold.
func Update(c *client.Client, channel string, body rate_limit.UpdateChannelPacingRequest) (struct{}, error) {
	__path := "/rate-limit/pacing/{channel}"
	__path = strings.Replace(__path, "{channel}", client.EncodePath(channel), 1)
	return client.Request[struct{}](c, "PUT", __path, nil, body)
}
