// Code generated by tapi. DO NOT EDIT.

package email

import (
	__client "integro_sdk"
	user_mfa "integro_sdk/types/user_mfa"
)

// Confirm Confirm bootstrap email-factor enrollment with a code and, on success, mint a user session token.
//
// Public — no authentication required; the request is gated solely by the ephemeral enrollment token in the body.
func Confirm(__c *__client.Client, __body user_mfa.UserMfaEnrollConfirmRequest) (user_mfa.UserMfaEnrollSessionResponse, error) {
	__path := "/user-session/mfa/enroll/email/confirm"
	return __client.Request[user_mfa.UserMfaEnrollSessionResponse](__c, "POST", __path, nil, __body)
}
// Start Begin email-factor enrollment during forced bootstrap, emailing a one-time code.
//
// Public — no authentication required; the request is gated by the ephemeral enrollment token in the body and by the per-IP and per-token code-dispatch throttle.
func Start(__c *__client.Client, __body user_mfa.UserMfaEnrollEmailStartRequest) (struct{}, error) {
	__path := "/user-session/mfa/enroll/email/start"
	return __client.Request[struct{}](__c, "POST", __path, nil, __body)
}
