// Code generated by tapi. DO NOT EDIT.

package ghl

import (
	__client "integro_sdk"
	__strings "strings"
	ghl "integro_sdk/types/ghl"
)

// Receive GoHighLevel conversation-provider delivery webhook: sends the message a
// location placed on the provider out on the whatsapp account it is linked
// to. Anything the bridge can never deliver is answered 200 so GoHighLevel
// stops retrying it; a failed send answers 5xx so it does not.
//
// Public — no authentication required; authorization comes from the secret path segment configured as the marketplace app's delivery URL.
func Receive(__c *__client.Client, secret string, __body ghl.GhlDeliveryPayload) (struct{}, error) {
	__path := "/webhook/ghl/{secret}"
	__path = __strings.Replace(__path, "{secret}", __client.EncodePath(secret), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, __body)
}
