// Code generated by tapi. DO NOT EDIT.

package totp

import (
	"integro_sdk"
	user_mfa "integro_sdk/types/user_mfa"
)

// Confirm Confirm self-service TOTP enrollment with a code.
//
// Authenticated user acting on their own factors; no permission required.
func Confirm(c *client.Client, body user_mfa.UserMfaMgmtTotpConfirmRequest) (struct{}, error) {
	__path := "/user-mfa/factor/totp/confirm"
	return client.Request[struct{}](c, "POST", __path, nil, body)
}
// Start Begin self-service TOTP enrollment, returning the secret, otpauth URI, and QR code.
//
// Authenticated user acting on their own factors; no permission required.
func Start(c *client.Client) (user_mfa.UserMfaEnrollTotpStartResponse, error) {
	__path := "/user-mfa/factor/totp/start"
	return client.Request[user_mfa.UserMfaEnrollTotpStartResponse](c, "POST", __path, nil, nil)
}
