// Code generated by tapi. DO NOT EDIT.

package whatsapp_template

import (
	"integro_sdk"
	message "integro_sdk/types/message"
)

// Create Submit a whatsapp message template for Meta's review; once APPROVED it is
// sendable as `template` content.
//
// Requires `ManageTemplates` in the account's group.
func Create(c *client.Client, body message.CreateTemplateRequest) (message.CreateTemplateResponse, error) {
	__path := "/whatsapp/template"
	return client.Request[message.CreateTemplateResponse](c, "POST", __path, nil, body)
}
// Delete Delete a whatsapp message template by name (all languages, or one specific
// `hsm_id`).
//
// Requires `ManageTemplates` in the account's group.
func Delete(c *client.Client, query message.DeleteTemplateQuery) (struct{}, error) {
	__path := "/whatsapp/template"
	return client.Request[struct{}](c, "DELETE", __path, query, nil)
}
// List List the WABA's whatsapp message templates, all statuses (only APPROVED
// ones are sendable).
//
// Requires `ViewTemplates` in the account's group.
func List(c *client.Client, query message.ListTemplatesQuery) ([]message.TemplateResponse, error) {
	__path := "/whatsapp/template"
	return client.Request[[]message.TemplateResponse](c, "GET", __path, query, nil)
}
