// Code generated by tapir. DO NOT EDIT.

package user_invite

import (
	primitives "integro_sdk/types/primitives"
)

type UserInviteJoinResponse struct {
	GroupUid primitives.Uid `json:"group_uid"`
}
