// Code generated by tapir. DO NOT EDIT.

package user_invite

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type UserInviteDetailResponse struct {
	Email primitives.Email `json:"email"`
	GroupUid primitives.Uid `json:"group_uid"`
	GroupName primitives.Name `json:"group_name"`
	// Whether `userInvite.logo` has an image to serve for this group.
	HasLogo bool `json:"has_logo"`
	Role types.MembershipRole `json:"role"`
	InvitedByName primitives.Name `json:"invited_by_name"`
	ExpiresAt primitives.Timestamp `json:"expires_at"`
}
