// Code generated by tapi. DO NOT EDIT.

package stevo

import (
	__client "integro_sdk"
)

// Receive Stevo webhook receiver: authenticates the delivery by the echoed instance
// token, stores normalized messages (deduplicating redeliveries), applies
// receipts/reactions/edits/revokes, and enqueues CRM fan-out events.
//
// Public — no authentication required; authorization comes from the instance token echoed inside the payload.
func Receive(__c *__client.Client) (struct{}, error) {
	__path := "/webhook/stevo"
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
