// Code generated by tapi. DO NOT EDIT.

package factor

import (
	"integro_sdk"
	"strings"
	user_mfa "integro_sdk/types/user_mfa"
)

// Delete Delete one of the caller's own MFA factors, refusing to remove their last confirmed factor.
//
// Authenticated user acting on their own factors; no permission required.
func Delete(c *client.Client, kind string) (struct{}, error) {
	__path := "/user-mfa/factor/{kind}"
	__path = strings.Replace(__path, "{kind}", client.EncodePath(kind), 1)
	return client.Request[struct{}](c, "DELETE", __path, nil, nil)
}
// List List the caller's own enrolled MFA factors.
//
// Authenticated user acting on their own factors; no permission required.
func List(c *client.Client) ([]user_mfa.UserMfaFactorRow, error) {
	__path := "/user-mfa/factor"
	return client.Request[[]user_mfa.UserMfaFactorRow](c, "GET", __path, nil, nil)
}
