// Code generated by tapi. DO NOT EDIT.

package calendar

import (
	"integro_sdk"
	"strings"
	google "integro_sdk/types/google"
	google_account "integro_sdk/types/google_account"
)

// CreateEvent Create an event on a calendar the account can write to.
//
// Requires `ManageCalendars` in the account's group.
func CreateEvent(c *client.Client, socialAccountUid string, query google_account.CalendarEventQuery, body google.EventInput) (google.Event, error) {
	__path := "/calendar/{social_account_uid}/event"
	__path = strings.Replace(__path, "{social_account_uid}", client.EncodePath(socialAccountUid), 1)
	return client.Request[google.Event](c, "POST", __path, query, body)
}
// DeleteEvent Delete (cancel) an event; deleting an already-cancelled event succeeds.
//
// Requires `ManageCalendars` in the account's group.
func DeleteEvent(c *client.Client, socialAccountUid string, eventId string, query google_account.CalendarEventQuery) (struct{}, error) {
	__path := "/calendar/{social_account_uid}/event/{event_id}"
	__path = strings.Replace(__path, "{social_account_uid}", client.EncodePath(socialAccountUid), 1)
	__path = strings.Replace(__path, "{event_id}", client.EncodePath(eventId), 1)
	return client.Request[struct{}](c, "DELETE", __path, query, nil)
}
// FreeBusy Busy intervals for a set of calendars within a time range. A calendar
// that cannot be read carries an `error` — never treat it as free.
//
// Requires `ViewCalendars` in the account's group.
func FreeBusy(c *client.Client, socialAccountUid string, body google_account.FreeBusyRequest) (google_account.FreeBusyResponse, error) {
	__path := "/calendar/{social_account_uid}/freebusy"
	__path = strings.Replace(__path, "{social_account_uid}", client.EncodePath(socialAccountUid), 1)
	return client.Request[google_account.FreeBusyResponse](c, "POST", __path, nil, body)
}
// GetEvent Get one event.
//
// Requires `ViewCalendars` in the account's group.
func GetEvent(c *client.Client, socialAccountUid string, eventId string, query google_account.CalendarEventQuery) (google.Event, error) {
	__path := "/calendar/{social_account_uid}/event/{event_id}"
	__path = strings.Replace(__path, "{social_account_uid}", client.EncodePath(socialAccountUid), 1)
	__path = strings.Replace(__path, "{event_id}", client.EncodePath(eventId), 1)
	return client.Request[google.Event](c, "GET", __path, query, nil)
}
// ListCalendars List the calendars the account can see — for pickers. Follow
// `next_page_token` for more.
//
// Requires `ViewCalendars` in the account's group.
func ListCalendars(c *client.Client, socialAccountUid string, query google_account.ListCalendarsQuery) (google.CalendarPage, error) {
	__path := "/calendar/{social_account_uid}/calendar"
	__path = strings.Replace(__path, "{social_account_uid}", client.EncodePath(socialAccountUid), 1)
	return client.Request[google.CalendarPage](c, "GET", __path, query, nil)
}
// ListEvents List a calendar's events within a time range, expanded to single
// instances and ordered by start. Follow `next_page_token` for more.
//
// Requires `ViewCalendars` in the account's group.
func ListEvents(c *client.Client, socialAccountUid string, query google_account.ListCalendarEventsQuery) (google.EventPage, error) {
	__path := "/calendar/{social_account_uid}/event"
	__path = strings.Replace(__path, "{social_account_uid}", client.EncodePath(socialAccountUid), 1)
	return client.Request[google.EventPage](c, "GET", __path, query, nil)
}
// UpdateEvent Patch an event: only the fields sent are changed — an omitted field is
// kept, never cleared.
//
// Requires `ManageCalendars` in the account's group.
func UpdateEvent(c *client.Client, socialAccountUid string, eventId string, query google_account.CalendarEventQuery, body google.EventInput) (google.Event, error) {
	__path := "/calendar/{social_account_uid}/event/{event_id}"
	__path = strings.Replace(__path, "{social_account_uid}", client.EncodePath(socialAccountUid), 1)
	__path = strings.Replace(__path, "{event_id}", client.EncodePath(eventId), 1)
	return client.Request[google.Event](c, "PATCH", __path, query, body)
}
