// Code generated by tapi. DO NOT EDIT.
//
// The tapir Go client runtime: a typed HTTP/SSE/WebSocket engine the generated
// client.go builds on. Uses net/http for request/response and SSE, and
// github.com/gorilla/websocket for WebSocket. Add gorilla/websocket to go.mod.

package client

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/gorilla/websocket"
)

// Client is a configured API client. Safe for concurrent use.
type Client struct {
	host    string
	http    *http.Client
	mu      sync.Mutex
	headers http.Header
}

// NewClient returns a client pointed at host (e.g. "https://api.example.com").
func NewClient(host string) *Client {
	return &Client{host: strings.TrimRight(host, "/"), http: &http.Client{}, headers: http.Header{}}
}

// SetHeader sets a default header sent with every request.
func (c *Client) SetHeader(key, value string) {
	c.mu.Lock()
	c.headers.Set(key, value)
	c.mu.Unlock()
}

// SetBearer sets the Authorization: Bearer header (empty clears it).
func (c *Client) SetBearer(token string) {
	if token == "" {
		c.mu.Lock()
		c.headers.Del("Authorization")
		c.mu.Unlock()
		return
	}
	c.SetHeader("Authorization", "Bearer "+token)
}

func (c *Client) headerClone() http.Header {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.headers.Clone()
}

// ApiError is a non-2xx response, a transport failure, or a decode failure.
type ApiError struct {
	Kind    string // "network" | "api" | "parse"
	Code    int
	Message string
	Body    string
}

func (e *ApiError) Error() string {
	switch e.Kind {
	case "api":
		return fmt.Sprintf("api error %d: %s", e.Code, e.Message)
	default:
		return fmt.Sprintf("%s error: %s", e.Kind, e.Message)
	}
}

func encodePath(v string) string { return url.PathEscape(v) }

// buildURL joins host + path + a serde_qs-compatible (bracket-nested) query.
func (c *Client) buildURL(path string, query any) (string, error) {
	u := c.host + path
	if query == nil {
		return u, nil
	}
	raw, err := json.Marshal(query)
	if err != nil {
		return "", &ApiError{Kind: "parse", Message: err.Error()}
	}
	var m any
	if err := json.Unmarshal(raw, &m); err != nil {
		return "", &ApiError{Kind: "parse", Message: err.Error()}
	}
	var segs []string
	appendQuery(&segs, "", m)
	if len(segs) > 0 {
		u += "?" + strings.Join(segs, "&")
	}
	return u, nil
}

// appendQuery emits bracket-nested key=value segments, matching serde_qs.
func appendQuery(out *[]string, key string, value any) {
	switch v := value.(type) {
	case nil:
		if key != "" {
			*out = append(*out, url.QueryEscape(key))
		}
	case map[string]any:
		for k, vv := range v {
			child := k
			if key != "" {
				child = key + "[" + k + "]"
			}
			appendQuery(out, child, vv)
		}
	case []any:
		for i, vv := range v {
			appendQuery(out, key+"["+strconv.Itoa(i)+"]", vv)
		}
	case bool:
		*out = append(*out, url.QueryEscape(key)+"="+strconv.FormatBool(v))
	case float64:
		*out = append(*out, url.QueryEscape(key)+"="+strconv.FormatFloat(v, 'f', -1, 64))
	case string:
		*out = append(*out, url.QueryEscape(key)+"="+url.QueryEscape(v))
	default:
		*out = append(*out, url.QueryEscape(key)+"="+url.QueryEscape(fmt.Sprintf("%v", v)))
	}
}

func (c *Client) do(method, path string, query any, body any) (*http.Response, error) {
	u, err := c.buildURL(path, query)
	if err != nil {
		return nil, err
	}
	var reader io.Reader
	if body != nil {
		raw, err := json.Marshal(body)
		if err != nil {
			return nil, &ApiError{Kind: "parse", Message: err.Error()}
		}
		reader = bytes.NewReader(raw)
	}
	req, err := http.NewRequest(method, u, reader)
	if err != nil {
		return nil, &ApiError{Kind: "network", Message: err.Error()}
	}
	req.Header = c.headerClone()
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, &ApiError{Kind: "network", Message: err.Error()}
	}
	return resp, nil
}

// request performs a request with an optional query and JSON body, decoding the
// success body into R.
func request[R any](c *Client, method, path string, query any, body any) (R, error) {
	var zero R
	resp, err := c.do(method, path, query, body)
	if err != nil {
		return zero, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return zero, &ApiError{Kind: "api", Code: resp.StatusCode, Message: resp.Status, Body: string(raw)}
	}
	if err := json.Unmarshal(raw, &zero); err != nil {
		return zero, &ApiError{Kind: "parse", Message: err.Error()}
	}
	return zero, nil
}

// requestBytes returns the raw success body (file/blob responses).
func (c *Client) requestBytes(method, path string, query any, body any) ([]byte, error) {
	resp, err := c.do(method, path, query, body)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, &ApiError{Kind: "api", Code: resp.StatusCode, Message: resp.Status, Body: string(raw)}
	}
	return raw, nil
}

// MultipartForm collects file parts and text fields for a multipart request.
type MultipartForm struct {
	buf         bytes.Buffer
	writer      *multipart.Writer
	initialized bool
}

func NewMultipartForm() *MultipartForm {
	f := &MultipartForm{}
	f.writer = multipart.NewWriter(&f.buf)
	f.initialized = true
	return f
}

func (f *MultipartForm) Field(name, value string) { _ = f.writer.WriteField(name, value) }

func (f *MultipartForm) File(name, filename string, content []byte) {
	w, err := f.writer.CreateFormFile(name, filename)
	if err == nil {
		_, _ = w.Write(content)
	}
}

func requestMultipart[R any](c *Client, method, path string, query any, form *MultipartForm) (R, error) {
	var zero R
	_ = form.writer.Close()
	u, err := c.buildURL(path, query)
	if err != nil {
		return zero, err
	}
	req, err := http.NewRequest(method, u, bytes.NewReader(form.buf.Bytes()))
	if err != nil {
		return zero, &ApiError{Kind: "network", Message: err.Error()}
	}
	req.Header = c.headerClone()
	req.Header.Set("Content-Type", form.writer.FormDataContentType())
	resp, err := c.http.Do(req)
	if err != nil {
		return zero, &ApiError{Kind: "network", Message: err.Error()}
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return zero, &ApiError{Kind: "api", Code: resp.StatusCode, Message: resp.Status, Body: string(raw)}
	}
	if err := json.Unmarshal(raw, &zero); err != nil {
		return zero, &ApiError{Kind: "parse", Message: err.Error()}
	}
	return zero, nil
}

// sse opens a Server-Sent Events stream, invoking onEvent with each event's raw
// data payload. Blocks until the server ends the stream.
func (c *Client) sse(path string, query any, onEvent func(json.RawMessage)) error {
	u, err := c.buildURL(path, query)
	if err != nil {
		return err
	}
	req, err := http.NewRequest("GET", u, nil)
	if err != nil {
		return &ApiError{Kind: "network", Message: err.Error()}
	}
	req.Header = c.headerClone()
	req.Header.Set("Accept", "text/event-stream")
	resp, err := c.http.Do(req)
	if err != nil {
		return &ApiError{Kind: "network", Message: err.Error()}
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return &ApiError{Kind: "api", Code: resp.StatusCode, Message: resp.Status}
	}
	scanner := bufio.NewScanner(resp.Body)
	scanner.Buffer(make([]byte, 0, 64*1024), 16*1024*1024)
	var data []string
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" {
			if len(data) > 0 {
				onEvent(json.RawMessage(strings.Join(data, "\n")))
				data = data[:0]
			}
			continue
		}
		if strings.HasPrefix(line, ":") {
			continue
		}
		if rest, ok := strings.CutPrefix(line, "data:"); ok {
			data = append(data, strings.TrimPrefix(rest, " "))
		}
	}
	if len(data) > 0 {
		onEvent(json.RawMessage(strings.Join(data, "\n")))
	}
	return nil
}

// ---- WebSocket ----------------------------------------------------------

type WsStatus int

const (
	WsConnecting WsStatus = iota
	WsOpen
	WsReconnecting
	WsStopped
)

// WsHandlers holds optional WebSocket lifecycle callbacks. OnMessage receives
// each JSON text frame as raw bytes.
type WsHandlers struct {
	OnMessage func(json.RawMessage)
	OnOpen    func()
	OnClose   func()
	OnError   func(error)
	OnStatus  func(WsStatus)
}

// WsConnection is a live socket with automatic reconnection.
type WsConnection struct {
	send   chan []byte
	stop   chan struct{}
	closed sync.Once
}

// Send JSON-serializes and sends one frame. Returns false if the socket is gone.
func (w *WsConnection) Send(message any) bool {
	raw, err := json.Marshal(message)
	if err != nil {
		return false
	}
	select {
	case w.send <- raw:
		return true
	case <-w.stop:
		return false
	}
}

// Stop closes the socket and stops reconnecting.
func (w *WsConnection) Stop() {
	w.closed.Do(func() { close(w.stop) })
}

func (c *Client) ws(path string, handlers WsHandlers) *WsConnection {
	conn := &WsConnection{send: make(chan []byte, 16), stop: make(chan struct{})}
	wsURL := toWsScheme(c.host) + path
	status := func(s WsStatus) {
		if handlers.OnStatus != nil {
			handlers.OnStatus(s)
		}
	}
	go func() {
		failures := 0
		for {
			select {
			case <-conn.stop:
				status(WsStopped)
				return
			default:
			}
			if failures == 0 {
				status(WsConnecting)
			} else {
				status(WsReconnecting)
			}
			ws, _, err := websocket.DefaultDialer.Dial(wsURL, c.headerClone())
			if err != nil {
				if handlers.OnError != nil {
					handlers.OnError(err)
				}
			} else {
				failures = 0
				status(WsOpen)
				if handlers.OnOpen != nil {
					handlers.OnOpen()
				}
				done := make(chan struct{})
				go func() {
					for {
						_, msg, err := ws.ReadMessage()
						if err != nil {
							close(done)
							return
						}
						if handlers.OnMessage != nil {
							handlers.OnMessage(json.RawMessage(msg))
						}
					}
				}()
			writeLoop:
				for {
					select {
					case <-conn.stop:
						_ = ws.Close()
						status(WsStopped)
						return
					case <-done:
						break writeLoop
					case out := <-conn.send:
						if err := ws.WriteMessage(websocket.TextMessage, out); err != nil {
							break writeLoop
						}
					}
				}
				_ = ws.Close()
				if handlers.OnClose != nil {
					handlers.OnClose()
				}
			}
			select {
			case <-conn.stop:
				status(WsStopped)
				return
			default:
			}
			backoff := 500 * (1 << min(failures, 5))
			if backoff > 15000 {
				backoff = 15000
			}
			failures++
			ctx, cancel := context.WithTimeout(context.Background(), time.Duration(backoff)*time.Millisecond)
			select {
			case <-conn.stop:
				cancel()
				status(WsStopped)
				return
			case <-ctx.Done():
				cancel()
			}
		}
	}()
	return conn
}

func toWsScheme(host string) string {
	if rest, ok := strings.CutPrefix(host, "https://"); ok {
		return "wss://" + rest
	}
	if rest, ok := strings.CutPrefix(host, "http://"); ok {
		return "ws://" + rest
	}
	return host
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// ---- exported request wrappers ---------------------------------------------
// So the generated route packages (each its own Go package under routes/) can
// drive requests from outside package `client`.

func Request[R any](c *Client, method, path string, query any, body any) (R, error) {
	return request[R](c, method, path, query, body)
}

func RequestBytes(c *Client, method, path string, query any, body any) ([]byte, error) {
	return c.requestBytes(method, path, query, body)
}

func RequestMultipart[R any](c *Client, method, path string, query any, form *MultipartForm) (R, error) {
	return requestMultipart[R](c, method, path, query, form)
}

func Sse(c *Client, path string, query any, onEvent func(json.RawMessage)) error {
	return c.sse(path, query, onEvent)
}

func Ws(c *Client, path string, handlers WsHandlers) *WsConnection {
	return c.ws(path, handlers)
}

func EncodePath(v string) string { return encodePath(v) }
