// Code generated by tapir. DO NOT EDIT.

package oauth_server

import (
	primitives "integro_sdk/types/primitives"
)

type ApproveRequest struct {
	ClientId primitives.Uid `json:"client_id"`
	RedirectUri string `json:"redirect_uri"`
	State *string `json:"state"`
	CodeChallenge string `json:"code_challenge"`
	CodeChallengeMethod string `json:"code_challenge_method"`
	ResponseType *string `json:"response_type"`
	Resource *string `json:"resource"`
}
