// Code generated by tapir. DO NOT EDIT.

package engagement

// Channel-tagged top-level comment: only facebook and instagram carry a
// comment surface, so no other channel's shape deserializes. The `channel`
// must match the account's.
type CreateCommentRequest = interface{}
