// Code generated by tapir. DO NOT EDIT.

package engagement

import (
	primitives "integro_sdk/types/primitives"
)

type ListCommentsQuery struct {
	// Narrow to these groups, each one the caller may see; omit for everything the caller may see.
	GroupUids *[]primitives.Uid `json:"group_uids"`
	// Narrow to these accounts, each one in scope; naming any account overrides the groups.
	SocialAccountUids *[]primitives.Uid `json:"social_account_uids"`
	// Filter to one post's comments (platform post/media id).
	ExternalPostId *string `json:"external_post_id"`
	// Poll cursor: only comments with `id` strictly greater are returned.
	SinceId uint64 `json:"since_id"`
	Limit *primitives.Number1_500 `json:"limit"`
}
