// Code generated by tapir. DO NOT EDIT.

package engagement

import (
	primitives "integro_sdk/types/primitives"
)

type ListMentionsQuery struct {
	GroupUid *primitives.Uid `json:"group_uid"`
	SocialAccountUid *primitives.Uid `json:"social_account_uid"`
	SinceId uint64 `json:"since_id"`
	Limit *primitives.Number1_500 `json:"limit"`
}
