// Code generated by tapir. DO NOT EDIT.

package engagement

// Channel-tagged mention reply: mentions are an instagram surface, so no
// other channel's shape deserializes. The `channel` must match the
// account's.
type MentionReplyRequest = interface{}
