// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type ActionRateLimitRule struct {
	Uid primitives.Uid `json:"uid"`
	Action types.RateLimitAction `json:"action"`
	MaxRequests primitives.Number1_100000 `json:"max_requests"`
	WindowSeconds primitives.Number1_3600 `json:"window_seconds"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
