// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

// One audience entry — a number, the account assigned to reach it — and its
// outcome. The `pending` rows of a campaign, per account in `id` order, are
// that account's queue: the message-table pattern, so a restart resumes the
// drip from the table itself.
type CampaignRecipient struct {
	Id uint64 `json:"id"`
	CampaignUid primitives.Uid `json:"campaign_uid"`
	// E.164, the audience key: one row per number per campaign.
	Phone primitives.Phone `json:"phone"`
	// The name known for the number at build — an import's name column, or
	// an existing conversation's — for `{{nome}}` on a conversation that has
	// none yet, and applied as its alias when it is discovered.
	Alias *primitives.Name `json:"alias"`
	// The account assigned to send, by the balanced-with-affinity
	// distribution at build.
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	// The conversation on that account; `None` until the dispatcher
	// discovers it — a "new conversation" for the operator.
	ConversationUid *primitives.Uid `json:"conversation_uid"`
	Status types.CampaignRecipientStatus `json:"status"`
	SkipReason *types.CampaignSkipReason `json:"skip_reason"`
	// The wheel's pick, recorded at dispatch.
	TemplateUid *primitives.Uid `json:"template_uid"`
	MessageUid *primitives.Uid `json:"message_uid"`
	Error *string `json:"error"`
	DispatchedAt *primitives.Timestamp `json:"dispatched_at"`
}
