// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

// One outbound-pacing rule per channel. A randomized delay in
// `[min_delay_ms, max_delay_ms]` sits between consecutive sends on any account
// of the channel; after every `batch_size` sends a `batch_pause_ms` pause
// applies. No rule (or all-zero delays with no `batch_size`) means no pacing —
// sends go out synchronously.
type ChannelPacingRule struct {
	Uid primitives.Uid `json:"uid"`
	Channel types.Channel `json:"channel"`
	MinDelayMs primitives.Number0_600000 `json:"min_delay_ms"`
	MaxDelayMs primitives.Number0_600000 `json:"max_delay_ms"`
	BatchSize *primitives.Number1_100000 `json:"batch_size"`
	BatchPauseMs primitives.Number0_3600000 `json:"batch_pause_ms"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
