// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
)

type Comment struct {
	// Strictly increasing insert order — the polling cursor.
	Id uint64 `json:"id"`
	Uid primitives.Uid `json:"uid"`
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	// Local post row when the commented post was published through the hub.
	PostUid *primitives.Uid `json:"post_uid"`
	ExternalId string `json:"external_id"`
	ExternalPostId string `json:"external_post_id"`
	ExternalParentId *string `json:"external_parent_id"`
	FromId string `json:"from_id"`
	FromName *string `json:"from_name"`
	// The account's own comments (our replies or comments made natively).
	FromAccount bool `json:"from_account"`
	Text string `json:"text"`
	Hidden bool `json:"hidden"`
	Deleted bool `json:"deleted"`
	SentAt primitives.Timestamp `json:"sent_at"`
	CreatedAt primitives.Timestamp `json:"created_at"`
}
