// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type Conversation struct {
	Uid primitives.Uid `json:"uid"`
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	// Platform participant id (PSID / IGSID / whatsapp wa_id) — scoped to the
	// account.
	ParticipantId string `json:"participant_id"`
	// Best-effort profile fetched from Meta on first contact.
	ParticipantName *string `json:"participant_name"`
	ParticipantUsername *string `json:"participant_username"`
	ParticipantAvatarUrl *string `json:"participant_avatar_url"`
	// The operator's own label for the person — set by hand or by a contact
	// import's name column. Independent of `participant_name`, which the
	// platform owns and profile refreshes overwrite; this is never touched by
	// them, and clearing it falls back to the platform name.
	Alias *primitives.Name `json:"alias"`
	LastMessageAt primitives.Timestamp `json:"last_message_at"`
	// Last inbound (participant) message — anchors whatsapp's 24h window.
	LastInboundAt *primitives.Timestamp `json:"last_inbound_at"`
	// Inbound messages sent at or before this instant were marked seen on the
	// platform. Unread detection: `last_inbound_at > seen_up_to`.
	SeenUpTo *primitives.Timestamp `json:"seen_up_to"`
	// Inbound messages since the conversation was last read (hub-local; a
	// platform mark-seen also clears it).
	UnreadCount uint32 `json:"unread_count"`
	// Denormalized newest-message preview — what a chat-list line renders.
	LastMessageUid *primitives.Uid `json:"last_message_uid"`
	LastMessageKind *types.MessageContentKind `json:"last_message_kind"`
	LastMessageText *string `json:"last_message_text"`
	LastMessageDirection *types.MessageDirection `json:"last_message_direction"`
	LastMessageStatus *types.MessageStatus `json:"last_message_status"`
	// Sender attribution of the previewed message (outbound only) — lets list
	// consumers detect human takeovers without fetching messages.
	LastMessageSentBy *types.MessageSentBy `json:"last_message_sent_by"`
	// The ad the conversation last arrived from (click-to-whatsapp) — the
	// newest message-level referral, rolled up here like the last_message_*
	// columns so a chat list answers "where did this come from" directly.
	Referral *types.Referral `json:"referral"`
	// When that referral arrived (the message's sent_at).
	ReferralAt *primitives.Timestamp `json:"referral_at"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
