// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
)

// An installed GoHighLevel location: a delivery destination owning its OAuth
// grant plus the binding to the whatsapp account it bridges into the
// location's SMS channel. Disconnecting deletes the row — there is no
// `enabled` flag.
type GhlLocation struct {
	Uid primitives.Uid `json:"uid"`
	GroupUid primitives.Uid `json:"group_uid"`
	// GHL's location (sub-account) id — how the delivery webhook finds the row.
	LocationId string `json:"location_id"`
	// GHL's agency (company) id; empty when the grant does not carry one.
	CompanyId string `json:"company_id"`
	Name string `json:"name"`
	Scope *string `json:"scope"`
	// The grant went stale (`invalid_grant` on refresh) and only a reconnect
	// can revive it.
	NeedsReauth bool `json:"needs_reauth"`
	// The social account this location bridges; `None` until an admin links one.
	TargetAccountUid *primitives.Uid `json:"target_account_uid"`
	// The contact tag added on GoHighLevel's side when a human answers from the
	// hub or the paired phone — the hook a location's workflow uses to put its
	// Conversation AI bot to sleep. `None` = the handoff is off.
	HandoffTag *string `json:"handoff_tag"`
	// Inbound-sync cursor into `message.id`: the target account's messages
	// beyond it still owe GHL a delivery.
	LastMessageId uint64 `json:"last_message_id"`
	ConnectedBy primitives.Uid `json:"connected_by"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
