// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type HttpRateLimitRule struct {
	Uid primitives.Uid `json:"uid"`
	Scope types.HttpRateLimitScope `json:"scope"`
	GroupUid *primitives.Uid `json:"group_uid"`
	MaxRequests primitives.Number1_100000 `json:"max_requests"`
	MaxBytesIn *primitives.Number1024_107374182400 `json:"max_bytes_in"`
	MaxBytesOut *primitives.Number1024_107374182400 `json:"max_bytes_out"`
	WindowSeconds primitives.Number1_3600 `json:"window_seconds"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
