// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type Issue struct {
	Id uint64 `json:"id"`
	Uid primitives.Uid `json:"uid"`
	Category types.IssueCategory `json:"category"`
	Severity types.IssueSeverity `json:"severity"`
	Status types.IssueStatus `json:"status"`
	Description primitives.Text0_8000 `json:"description"`
	Details types.IssueDetails `json:"details"`
	Screenshots types.IssueScreenshots `json:"screenshots"`
	ReportedBy primitives.Uid `json:"reported_by"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
