// Code generated by tapir. DO NOT EDIT.

package database

type PulseGpuMetricRow struct {
	RecordedAt int64 `json:"recorded_at"`
	GpuIndex uint32 `json:"gpu_index"`
	VramUsedBytes uint64 `json:"vram_used_bytes"`
	VramUsagePercent float32 `json:"vram_usage_percent"`
	UtilizationPercent uint32 `json:"utilization_percent"`
	MemoryUtilizationPercent uint32 `json:"memory_utilization_percent"`
	ClockGraphicsMhz uint32 `json:"clock_graphics_mhz"`
	ClockMemoryMhz uint32 `json:"clock_memory_mhz"`
	TemperatureCelsius uint32 `json:"temperature_celsius"`
	PowerWatts float32 `json:"power_watts"`
}
