// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
)

type ServerUptime struct {
	Id uint32 `json:"id"`
	StartedAt primitives.Timestamp `json:"started_at"`
	LastHeartbeatAt primitives.Timestamp `json:"last_heartbeat_at"`
}
