// Code generated by tapir. DO NOT EDIT.

package database

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

// `group_uid` and `role` are a tied pair the DB CHECK enforces: both set means
// accepting joins that group with that role, both NULL means a platform invite
// that lands the new user in no group at all.
type UserInvite struct {
	Uid primitives.Uid `json:"uid"`
	Email primitives.Email `json:"email"`
	InvitedBy primitives.Uid `json:"invited_by"`
	GroupUid *primitives.Uid `json:"group_uid"`
	Role *types.MembershipRole `json:"role"`
	ExpiresAt primitives.Timestamp `json:"expires_at"`
	AcceptedAt *primitives.Timestamp `json:"accepted_at"`
	EmailStatus types.UserInviteEmailStatus `json:"email_status"`
	CreatedAt primitives.Timestamp `json:"created_at"`
}
