// Code generated by tapir. DO NOT EDIT.

package user

import (
	primitives "integro_sdk/types/primitives"
)

type CreateUserRequest struct {
	Email primitives.Email `json:"email"`
	Name primitives.Name `json:"name"`
	Password primitives.Password8_128_F_F_T_F `json:"password"`
}
