// Code generated by tapir. DO NOT EDIT.

package user

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

// One membership seen from the user's side — the mirror of the group roster's
// entry, carrying the fields that name the group behind it instead of the
// group record itself.
type UserMembershipResponse struct {
	GroupUid primitives.Uid `json:"group_uid"`
	// The group's name, so the panel names each group without a second call.
	Name primitives.Name `json:"name"`
	// The group's own flag: a membership into a disabled group keeps working,
	// so the roster says so rather than hiding it.
	Enabled bool `json:"enabled"`
	Role domain.MembershipRole `json:"role"`
	MemberSince primitives.Timestamp `json:"member_since"`
}
