// Code generated by tapir. DO NOT EDIT.

package user

import (
	domain "integro_sdk/types/domain"
)

// The caller's own account plus everything a gating decision reads: the
// platform-wide permission set the `super_admin` flag carries, and one entry
// per group they belong to. A user who belongs to nowhere is ordinary — both
// lists are simply empty.
type UserSelfResponse struct {
	domain.User
	// Held everywhere, in every group and outside all of them: the whole
	// catalog for platform staff, empty for everyone else, whose authority
	// lives entirely in `memberships`.
	Permissions []domain.UserPermission `json:"permissions"`
	Memberships []MembershipResponse `json:"memberships"`
}
