// Code generated by tapir. DO NOT EDIT.

package user

import (
	domain "integro_sdk/types/domain"
)

// The caller's own notification choices that are not tied to one account.
type UserNotificationResponse struct {
	MessageChime domain.MessageChime `json:"message_chime"`
}
