// Code generated by tapi. DO NOT EDIT.

package history

import (
	__client "integro_sdk"
	domain "integro_sdk/types/domain"
	pulse "integro_sdk/types/pulse"
)

// Disk List historical disk metrics within a time window.
//
// Requires `ViewPulse`, which only platform staff hold.
func Disk(__c *__client.Client, __query pulse.PulseHistoryQuery) ([]domain.PulseDiskMetricRow, error) {
	__path := "/pulse/history/disk"
	return __client.Request[[]domain.PulseDiskMetricRow](__c, "GET", __path, __query, nil)
}
// Gpu List historical GPU metrics within a time window.
//
// Requires `ViewPulse`, which only platform staff hold.
func Gpu(__c *__client.Client, __query pulse.PulseHistoryQuery) ([]domain.PulseGpuMetricRow, error) {
	__path := "/pulse/history/gpu"
	return __client.Request[[]domain.PulseGpuMetricRow](__c, "GET", __path, __query, nil)
}
// Host List historical host metrics within a time window.
//
// Requires `ViewPulse`, which only platform staff hold.
func Host(__c *__client.Client, __query pulse.PulseHistoryQuery) ([]domain.PulseHostMetricRow, error) {
	__path := "/pulse/history/host"
	return __client.Request[[]domain.PulseHostMetricRow](__c, "GET", __path, __query, nil)
}
// Network List historical network metrics within a time window.
//
// Requires `ViewPulse`, which only platform staff hold.
func Network(__c *__client.Client, __query pulse.PulseHistoryQuery) ([]domain.PulseNetworkMetricRow, error) {
	__path := "/pulse/history/network"
	return __client.Request[[]domain.PulseNetworkMetricRow](__c, "GET", __path, __query, nil)
}
