// Code generated by tapir. DO NOT EDIT.

package pulse_sys

type PulseSnapshot struct {
	TimestampMs int64 `json:"timestamp_ms"`
	UptimeSecs uint64 `json:"uptime_secs"`
	Cpu PulseCpuSnapshot `json:"cpu"`
	Ram PulseRamSnapshot `json:"ram"`
	Disks []PulseDiskSnapshot `json:"disks"`
	Networks []PulseNetworkSnapshot `json:"networks"`
	Processes []PulseProcessSnapshot `json:"processes"`
	Gpus []PulseGpuSnapshot `json:"gpus"`
}
