// Code generated by tapir. DO NOT EDIT.

package pulse_sys

type PulseDiskSnapshot struct {
	Name string `json:"name"`
	MountPoint string `json:"mount_point"`
	FsType string `json:"fs_type"`
	TotalBytes uint64 `json:"total_bytes"`
	AvailableBytes uint64 `json:"available_bytes"`
	UsagePercent float32 `json:"usage_percent"`
	ReadBytes uint64 `json:"read_bytes"`
	WrittenBytes uint64 `json:"written_bytes"`
	TotalReadBytes uint64 `json:"total_read_bytes"`
	TotalWrittenBytes uint64 `json:"total_written_bytes"`
	ReadBytesPerSec float64 `json:"read_bytes_per_sec"`
	WrittenBytesPerSec float64 `json:"written_bytes_per_sec"`
	ReadIops float64 `json:"read_iops"`
	WriteIops float64 `json:"write_iops"`
	Temperatures []PulseTemperatureReading `json:"temperatures"`
}
