// Code generated by tapir. DO NOT EDIT.

package pulse_sys

type PulseProcessStatus string

const (
	PulseProcessStatusRun PulseProcessStatus = "run"
	PulseProcessStatusSleep PulseProcessStatus = "sleep"
	PulseProcessStatusStop PulseProcessStatus = "stop"
	PulseProcessStatusZombie PulseProcessStatus = "zombie"
	PulseProcessStatusIdle PulseProcessStatus = "idle"
	PulseProcessStatusDead PulseProcessStatus = "dead"
	PulseProcessStatusTracing PulseProcessStatus = "tracing"
	PulseProcessStatusWakekill PulseProcessStatus = "wakekill"
	PulseProcessStatusWaking PulseProcessStatus = "waking"
	PulseProcessStatusParked PulseProcessStatus = "parked"
	PulseProcessStatusLockBlocked PulseProcessStatus = "lock_blocked"
	PulseProcessStatusUninterruptibleDiskSleep PulseProcessStatus = "uninterruptible_disk_sleep"
	PulseProcessStatusSuspended PulseProcessStatus = "suspended"
	PulseProcessStatusUnknown PulseProcessStatus = "unknown"
)
