// Code generated by tapir. DO NOT EDIT.

package pulse_sys

type PulseProcessSnapshot struct {
	Pid uint32 `json:"pid"`
	Name string `json:"name"`
	CpuUsage float32 `json:"cpu_usage"`
	MemoryBytes uint64 `json:"memory_bytes"`
	VirtualMemoryBytes uint64 `json:"virtual_memory_bytes"`
	DiskReadBytes uint64 `json:"disk_read_bytes"`
	DiskWrittenBytes uint64 `json:"disk_written_bytes"`
	Status PulseProcessStatus `json:"status"`
	RunTimeSecs uint64 `json:"run_time_secs"`
}
