// Code generated by tapir. DO NOT EDIT.

package pulse_sys

type PulseSystemInfo struct {
	Hostname string `json:"hostname"`
	OsName string `json:"os_name"`
	OsVersion string `json:"os_version"`
	KernelVersion string `json:"kernel_version"`
	CpuModel string `json:"cpu_model"`
	PhysicalCores uint64 `json:"physical_cores"`
	LogicalCores uint64 `json:"logical_cores"`
}
