// Code generated by tapir. DO NOT EDIT.

package issue

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type CreateIssueForm struct {
	Severity domain.IssueSeverity `json:"severity"`
	Description primitives.Text0_8000 `json:"description"`
	Details domain.IssueDetails `json:"details"`
	Screenshots [][]byte `json:"screenshots"`
}
