// Code generated by tapir. DO NOT EDIT.

package issue

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type CreateIssueForm struct {
	Severity types.IssueSeverity `json:"severity"`
	Description primitives.Text8000 `json:"description"`
	Details types.IssueDetails `json:"details"`
	Screenshots [][]byte `json:"screenshots"`
}
