// Code generated by tapi. DO NOT EDIT.

package email

import (
	"integro_sdk"
	user_mfa "integro_sdk/types/user_mfa"
)

// Confirm Confirm self-service email-factor enrollment with a code.
//
// Authenticated user acting on their own factors; no permission required.
func Confirm(c *client.Client, body user_mfa.UserMfaEnrollConfirmRequest) (struct{}, error) {
	__path := "/user-mfa/factor/email/confirm"
	return client.Request[struct{}](c, "POST", __path, nil, body)
}
// Start Begin self-service email-factor enrollment, emailing a one-time code and returning an enrollment token.
//
// Authenticated user acting on their own factors; no permission required.
func Start(c *client.Client) (user_mfa.UserMfaMgmtEmailStartResponse, error) {
	__path := "/user-mfa/factor/email/start"
	return client.Request[user_mfa.UserMfaMgmtEmailStartResponse](c, "POST", __path, nil, nil)
}
