// Code generated by tapi. DO NOT EDIT.

package conversation

import (
	__client "integro_sdk"
	__strings "strings"
	call "integro_sdk/types/call"
	database "integro_sdk/types/database"
	message "integro_sdk/types/message"
)

// Action Send a presence signal into a conversation: mark_seen, typing_on, or
// typing_off. The payload is channel-tagged and the `channel` must match the
// conversation's account; official whatsapp has no typing_off (its indicator
// auto-dismisses), so that channel's shape cannot express one. Mark-seen
// advances the conversation's `seen_up_to` watermark (`last_inbound_at >
// seen_up_to` = unread).
//
// Requires `SendMessages` in the conversation's group.
func Action(__c *__client.Client, conversationUid string, __body message.ConversationActionRequest) (struct{}, error) {
	__path := "/conversation/{conversation_uid}/action"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, __body)
}
// Alias Set or clear the operator's label for the contact. Independent of the
// platform-fetched participant name, which profile refreshes keep updating;
// clearing the alias falls back to it.
//
// Requires `SendMessages` in the conversation's group.
func Alias(__c *__client.Client, conversationUid string, __body message.SetConversationAliasRequest) (database.Conversation, error) {
	__path := "/conversation/{conversation_uid}/alias"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	return __client.Request[database.Conversation](__c, "PUT", __path, nil, __body)
}
// Calls List a conversation's calls, newest first; `before_id` pages older history.
//
// Requires `ViewMessages` in the conversation's group.
func Calls(__c *__client.Client, conversationUid string, __query call.ConversationCallsQuery) ([]database.Call, error) {
	__path := "/conversation/{conversation_uid}/call"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	return __client.Request[[]database.Call](__c, "GET", __path, __query, nil)
}
// Clear Erase the conversation's stored history on the hub, keeping the
// conversation: its messages go, the preview and unread badge reset, and the
// 24h-window watermarks stay. Nothing is deleted on the platform.
//
// Requires `ManageMessages` in the conversation's group.
func Clear(__c *__client.Client, conversationUid string) (database.Conversation, error) {
	__path := "/conversation/{conversation_uid}/message"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	return __client.Request[database.Conversation](__c, "DELETE", __path, nil, nil)
}
// Create Open (or return) a conversation with a phone number — a channel-tagged
// request whose declared channel must match the account's; only
// whatsapp_stevo / whatsapp_native can verify a number on the platform,
// so no other channel's shape deserializes. The number is checked first
// (an unrecognized number or failed check creates nothing), the platform's
// canonical id keys the conversation, and the initial profile (name,
// picture) is stored best-effort.
//
// Requires `SendMessages` in the account's group.
func Create(__c *__client.Client, __body message.CreateConversationRequest) (database.Conversation, error) {
	__path := "/conversation"
	return __client.Request[database.Conversation](__c, "POST", __path, nil, __body)
}
// Delete Delete the conversation and its whole stored history from the hub.
// Nothing is deleted on the platform: a later inbound message from the same
// participant opens a fresh conversation.
//
// Requires `ManageMessages` in the conversation's group.
func Delete(__c *__client.Client, conversationUid string) (struct{}, error) {
	__path := "/conversation/{conversation_uid}"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// List List conversations, newest activity first, optionally filtered by group or
// social account; `before_activity_at`+`before_uid` page older activity
// (keyset cursor). Rows carry the denormalized chat-list summary (unread
// badge + last-message preview).
//
// Requires `ViewMessages`; the list covers only conversations of groups where the caller holds it.
func List(__c *__client.Client, __query message.ListConversationsQuery) ([]database.Conversation, error) {
	__path := "/conversation"
	return __client.Request[[]database.Conversation](__c, "GET", __path, __query, nil)
}
// MessageCount How many messages the conversation holds, narrowed by `kinds` like the
// list — what a media gallery shows as its total.
//
// Requires `ViewMessages` in the conversation's group.
func MessageCount(__c *__client.Client, conversationUid string, __query message.ConversationMessageCountQuery) (uint64, error) {
	__path := "/conversation/{conversation_uid}/message/count"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	return __client.Request[uint64](__c, "GET", __path, __query, nil)
}
// Messages List a conversation's messages, newest first; `before_id` pages older
// history.
//
// Requires `ViewMessages` in the conversation's group.
func Messages(__c *__client.Client, conversationUid string, __query message.ConversationMessagesQuery) ([]database.Message, error) {
	__path := "/conversation/{conversation_uid}/message"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	return __client.Request[[]database.Message](__c, "GET", __path, __query, nil)
}
// Read Clear the conversation's unread badge (hub-local read state, shared by
// every operator). Never sends a platform read receipt — that stays the
// explicit `mark_seen` conversation action.
//
// Requires `ViewMessages` in the conversation's group.
func Read(__c *__client.Client, conversationUid string) (database.Conversation, error) {
	__path := "/conversation/{conversation_uid}/read"
	__path = __strings.Replace(__path, "{conversation_uid}", __client.EncodePath(conversationUid), 1)
	return __client.Request[database.Conversation](__c, "PUT", __path, nil, nil)
}
// UnreadCount How many conversations hold unread messages, across every group where the
// caller holds `ViewMessages` — the inbox badge.
func UnreadCount(__c *__client.Client) (uint64, error) {
	__path := "/conversation/unread"
	return __client.Request[uint64](__c, "GET", __path, nil, nil)
}
