// Code generated by tapi. DO NOT EDIT.

package event

import (
	__client "integro_sdk"
	event "integro_sdk/types/event"
)

// Ws Live event stream over WebSocket, typed both ways: the client opens with
// `hello` (optional `(epoch, seq)` resume cursor + roster filter) and may
// replace the roster or the focused-conversation set at any time; the
// server pushes sequenced `event` frames — the same `HubEvent` payloads the
// group webhook delivers — plus `gap` when events were missed and cannot be
// replayed (re-hydrate from REST; storage is the source of truth). Auth is
// re-validated continuously, so key revocation, permission edits, and
// session expiry close the connection mid-stream.
//
// Requires `ViewMessages` anywhere to connect; every event is then delivered only to a caller — human or API key alike — holding that family's permission in the event's own group: `ViewMessages` for message, presence and conversation events, `ViewComments` for comment and mention events, `ViewPosts` for post events, `ViewSocialAccounts` for account events, `ViewBusiness` for review events (events failing that check are silently absent).
func Ws(__c *__client.Client, __handlers __client.WsHandlers[event.ServerMsg]) *__client.WsConnection[event.ClientMsg] {
	__path := "/event/ws"
	return __client.Ws[event.ClientMsg, event.ServerMsg](__c, __path, nil, __handlers)
}
