// Code generated by tapi. DO NOT EDIT.

package comment

import (
	__client "integro_sdk"
	__strings "strings"
	domain "integro_sdk/types/domain"
	engagement "integro_sdk/types/engagement"
)

// Create Comment on a post/media as the account named in the path (top-level
// comment). The payload is channel-tagged and must match the account's
// channel — only facebook and instagram carry a comment surface, so no
// other channel's shape deserializes.
//
// Requires `ReplyComments` in the account's group.
func Create(__c *__client.Client, socialAccountUid string, __body engagement.CreateCommentRequest) (domain.Comment, error) {
	__path := "/social-account/{social_account_uid}/comment"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[domain.Comment](__c, "POST", __path, nil, __body)
}
// Delete Delete a comment from the platform; the row is kept with `deleted` set.
//
// Requires `ModerateComments` in the account's group.
func Delete(__c *__client.Client, socialAccountUid string, commentUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/comment/{comment_uid}"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	__path = __strings.Replace(__path, "{comment_uid}", __client.EncodePath(commentUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Get Fetch a single comment of the account. A comment uid outside the named
// account reads as not found.
//
// Requires `ViewComments` in the account's group.
func Get(__c *__client.Client, socialAccountUid string, commentUid string) (domain.Comment, error) {
	__path := "/social-account/{social_account_uid}/comment/{comment_uid}"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	__path = __strings.Replace(__path, "{comment_uid}", __client.EncodePath(commentUid), 1)
	return __client.Request[domain.Comment](__c, "GET", __path, nil, nil)
}
// Like Like a comment as the page (Facebook only — Instagram's API has no
// comment likes).
//
// Requires `ReplyComments` in the account's group.
func Like(__c *__client.Client, socialAccountUid string, commentUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/comment/{comment_uid}/like"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	__path = __strings.Replace(__path, "{comment_uid}", __client.EncodePath(commentUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// List Poll the unified comment feed: comments with `id` greater than `since_id`,
// oldest first, optionally filtered by group, account, or post.
//
// Requires `ViewComments`; the feed covers only comments of groups where the caller holds it.
func List(__c *__client.Client, __query engagement.ListCommentsQuery) ([]domain.Comment, error) {
	__path := "/comment"
	return __client.Request[[]domain.Comment](__c, "GET", __path, __query, nil)
}
// PrivateReply Answer a comment privately with a DM (allowed once per comment; the
// message lands in the conversation via the echo webhook). The account's
// own comments are refused.
//
// Requires `SendMessages` in the account's group (the reply is a DM, not a comment).
func PrivateReply(__c *__client.Client, socialAccountUid string, commentUid string, __body engagement.PrivateReplyRequest) (engagement.PrivateReplyResponse, error) {
	__path := "/social-account/{social_account_uid}/comment/{comment_uid}/private-reply"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	__path = __strings.Replace(__path, "{comment_uid}", __client.EncodePath(commentUid), 1)
	return __client.Request[engagement.PrivateReplyResponse](__c, "POST", __path, nil, __body)
}
// Reply Reply to a comment as the account (threaded reply).
//
// Requires `ReplyComments` in the account's group.
func Reply(__c *__client.Client, socialAccountUid string, commentUid string, __body engagement.CommentMessageRequest) (domain.Comment, error) {
	__path := "/social-account/{social_account_uid}/comment/{comment_uid}/reply"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	__path = __strings.Replace(__path, "{comment_uid}", __client.EncodePath(commentUid), 1)
	return __client.Request[domain.Comment](__c, "POST", __path, nil, __body)
}
// SetHidden Hide or unhide a comment on the platform.
//
// Requires `ModerateComments` in the account's group.
func SetHidden(__c *__client.Client, socialAccountUid string, commentUid string, __body engagement.SetCommentHiddenRequest) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/comment/{comment_uid}/hidden"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	__path = __strings.Replace(__path, "{comment_uid}", __client.EncodePath(commentUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// Unlike Remove the page's like from a comment (Facebook only).
//
// Requires `ReplyComments` in the account's group.
func Unlike(__c *__client.Client, socialAccountUid string, commentUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/comment/{comment_uid}/like"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	__path = __strings.Replace(__path, "{comment_uid}", __client.EncodePath(commentUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
