// Code generated by tapi. DO NOT EDIT.

package post

import (
	__client "integro_sdk"
	__strings "strings"
	domain "integro_sdk/types/domain"
	post "integro_sdk/types/post"
)

// Create Publish (or schedule) a post through a social account; the channel-tagged
// content must match the account's channel.
//
// Requires `PublishPosts` in the account's group.
func Create(__c *__client.Client, __body post.CreatePostRequest) (domain.Post, error) {
	__path := "/post"
	return __client.Request[domain.Post](__c, "POST", __path, nil, __body)
}
// Delete Delete a post: published posts are removed from the platform (Instagram
// carousels are deleted as a whole); a published instagram_alt post cannot
// be removed through the alternate gateway and is refused (400). A
// scheduled or pending post is cancelled hub-side — it is never published, and its unpublished Instagram
// container is left to expire on Meta's side rather than deleted. The row is
// kept with a `deleted` status.
//
// Requires `DeletePosts` in the post's group.
func Delete(__c *__client.Client, postUid string) (struct{}, error) {
	__path := "/post/{post_uid}"
	__path = __strings.Replace(__path, "{post_uid}", __client.EncodePath(postUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Get Fetch a single post by uid.
//
// Requires `ViewPosts` in the post's group.
func Get(__c *__client.Client, postUid string) (domain.Post, error) {
	__path := "/post/{post_uid}"
	__path = __strings.Replace(__path, "{post_uid}", __client.EncodePath(postUid), 1)
	return __client.Request[domain.Post](__c, "GET", __path, nil, nil)
}
// List List posts, newest first, optionally filtered by groups or social accounts.
//
// Requires `ViewPosts`; the list covers only posts of groups where the caller holds it.
func List(__c *__client.Client, __query post.ListPostsQuery) ([]domain.Post, error) {
	__path := "/post"
	return __client.Request[[]domain.Post](__c, "GET", __path, __query, nil)
}
// SetComments Enable or disable comments on a published post. The payload is
// channel-tagged and must match the post's channel — instagram only
// (Facebook has no per-post comment toggle in the API), so no other
// channel's shape deserializes.
//
// Requires `UpdatePosts` in the post's group.
func SetComments(__c *__client.Client, postUid string, __body post.SetPostCommentsRequest) (struct{}, error) {
	__path := "/post/{post_uid}/comment"
	__path = __strings.Replace(__path, "{post_uid}", __client.EncodePath(postUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetHidden Hide or unhide a published post from the Page timeline — it stays
// reachable by direct link. The payload is channel-tagged and must match
// the post's channel — facebook only, non-video posts — so no other
// channel's shape deserializes.
//
// Requires `UpdatePosts` in the post's group.
func SetHidden(__c *__client.Client, postUid string, __body post.SetPostHiddenRequest) (struct{}, error) {
	__path := "/post/{post_uid}/hidden"
	__path = __strings.Replace(__path, "{post_uid}", __client.EncodePath(postUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetPinned Pin or unpin a published post to the top of the Page timeline. The
// payload is channel-tagged and must match the post's channel — facebook
// only, non-video posts — so no other channel's shape deserializes.
//
// Requires `UpdatePosts` in the post's group.
func SetPinned(__c *__client.Client, postUid string, __body post.SetPostPinnedRequest) (struct{}, error) {
	__path := "/post/{post_uid}/pinned"
	__path = __strings.Replace(__path, "{post_uid}", __client.EncodePath(postUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// Update Edit a published post's text on the platform. The payload is
// channel-tagged and must match the post's channel — only facebook can edit
// (the Instagram API cannot edit captions; stories carry no text), so no
// other channel's shape deserializes.
//
// Requires `UpdatePosts` in the post's group.
func Update(__c *__client.Client, postUid string, __body post.UpdatePostRequest) (domain.Post, error) {
	__path := "/post/{post_uid}"
	__path = __strings.Replace(__path, "{post_uid}", __client.EncodePath(postUid), 1)
	return __client.Request[domain.Post](__c, "PUT", __path, nil, __body)
}
