// Code generated by tapi. DO NOT EDIT.

package user_password_reset

import (
	"integro_sdk"
	user_password_reset "integro_sdk/types/user_password_reset"
)

// Confirm Set a new password using a valid reset token, revoking the user's existing sessions.
//
// Public — no authentication required; authorization is via the ephemeral reset token.
func Confirm(c *client.Client, body user_password_reset.UserPasswordResetConfirmRequest) (struct{}, error) {
	__path := "/user-password-reset/confirm"
	return client.Request[struct{}](c, "POST", __path, nil, body)
}
// Request Issue a password-reset token and email a reset link to the address if it maps to an enabled account.
//
// Public — no authentication required.
func Request(c *client.Client, body user_password_reset.UserPasswordResetStartRequest) (struct{}, error) {
	__path := "/user-password-reset/request"
	return client.Request[struct{}](c, "POST", __path, nil, body)
}
