// Code generated by tapi. DO NOT EDIT.

package user_password_reset

import (
	__client "integro_sdk"
	user_password_reset "integro_sdk/types/user_password_reset"
)

// Confirm Set a new password using a valid reset token, revoking the user's existing sessions.
//
// Public — no authentication required; authorization is via the ephemeral reset token.
func Confirm(__c *__client.Client, __body user_password_reset.UserPasswordResetConfirmRequest) (struct{}, error) {
	__path := "/user-password-reset/confirm"
	return __client.Request[struct{}](__c, "POST", __path, nil, __body)
}
// Request Issue a password-reset token and email a reset link to the address if it maps to an enabled account.
//
// Public — no authentication required. Rejected when the caller trips either the per-IP or the per-email password-reset throttle.
func Request(__c *__client.Client, __body user_password_reset.UserPasswordResetStartRequest) (struct{}, error) {
	__path := "/user-password-reset/request"
	return __client.Request[struct{}](__c, "POST", __path, nil, __body)
}
