// Code generated by tapir. DO NOT EDIT.

package insight

// Which account metrics to aggregate; the channel decides the vocabulary, and
// only accounts of that channel take part.
type AccountMetricQuery = interface{}
