// Code generated by tapir. DO NOT EDIT.

package insight

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type ConversationInsightQuery struct {
	// Narrow to these groups, each one the caller may see; omit for everything the caller may see.
	GroupUids *[]primitives.Uid `json:"group_uids"`
	// Narrow to these accounts; each must be in scope.
	SocialAccountUids *[]primitives.Uid `json:"social_account_uids"`
	// Narrow to these channels.
	Channels *[]domain.Channel `json:"channels"`
	// Start of the period (unix ms), inclusive.
	Since primitives.Timestamp `json:"since"`
	// End of the period (unix ms), exclusive.
	Until primitives.Timestamp `json:"until"`
	Granularity domain.ActivityGranularity `json:"granularity"`
	// Minutes east of UTC that periods align to; 0 when omitted.
	UtcOffsetMinutes *int32 `json:"utc_offset_minutes"`
}
