// Code generated by tapir. DO NOT EDIT.

package insight

// Atendimentos opened in one hour of the week across the period.
type HourOfWeek struct {
	// 1 is Monday and 7 is Sunday, in the requested offset.
	Weekday int64 `json:"weekday"`
	// Hour of the day, 0 to 23, in the requested offset.
	Hour int64 `json:"hour"`
	Openings int64 `json:"openings"`
	FirstReply ReplyBands `json:"first_reply"`
}
