// Code generated by tapir. DO NOT EDIT.

package insight

import (
	primitives "integro_sdk/types/primitives"
)

type InsightHistoryQuery struct {
	// Filter to these collected metric names (comma-separated); defaults to
	// every stored metric.
	Metrics *string `json:"metrics"`
	// Inclusive range over snapshot days (unix ms); defaults to the last 30 days.
	From *primitives.Timestamp `json:"from"`
	To *primitives.Timestamp `json:"to"`
}
