// Code generated by tapir. DO NOT EDIT.

package insight

import (
	primitives "integro_sdk/types/primitives"
)

type InsightHistoryQuery struct {
	// Inclusive range over snapshot days (unix ms); defaults to the last 30 days.
	Since *primitives.Timestamp `json:"since"`
	Until *primitives.Timestamp `json:"until"`
}
