// Code generated by tapir. DO NOT EDIT.

package insight

import (
	meta "integro_sdk/types/meta"
	primitives "integro_sdk/types/primitives"
)

// One snapshot day's value. The newest day is usually still partial — the
// collector keeps re-capturing it until the UTC day rolls over.
type InsightPoint struct {
	// UTC midnight of the snapshot day.
	CapturedOn primitives.Timestamp `json:"captured_on"`
	Value meta.InsightValue `json:"value"`
}
