// Code generated by tapir. DO NOT EDIT.

package insight

type PostingInsightResponse struct {
	// Accounts the query covered after every filter.
	Accounts int64 `json:"accounts"`
	// One per period, oldest first, gaps included as zeros.
	Buckets []PostingBucket `json:"buckets"`
	// Posts published across the whole period.
	Posts int64 `json:"posts"`
}
