// Code generated by tapir. DO NOT EDIT.

package insight

import (
	primitives "integro_sdk/types/primitives"
)

type PostingBucket struct {
	// Start of the period (unix ms), aligned to the requested offset.
	PeriodStart primitives.Timestamp `json:"period_start"`
	// Platform posts published in the period.
	Posts int64 `json:"posts"`
}
