// Code generated by tapir. DO NOT EDIT.

package insight

// Answered requests by how long the customer waited, from the request's
// first message to the account's reply.
type ReplyBands struct {
	// Answered within 5 minutes.
	UpTo5m int64 `json:"up_to_5m"`
	// Answered after 5 minutes and within an hour.
	UpTo1h int64 `json:"up_to_1h"`
	// Answered after an hour and within 24 hours.
	UpTo24h int64 `json:"up_to_24h"`
	// Answered after more than 24 hours.
	Over24h int64 `json:"over_24h"`
}
