// Code generated by tapir. DO NOT EDIT.

package api_key

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type CreateApiKeyRequest struct {
	Name primitives.Name `json:"name"`
	GroupUid *primitives.Uid `json:"group_uid"`
	Permissions domain.ApiKeyPermissions `json:"permissions"`
}
