// Code generated by tapir. DO NOT EDIT.

package api_key

import (
	primitives "integro_sdk/types/primitives"
)

type CreateApiKeyResponse struct {
	Uid primitives.Uid `json:"uid"`
	Key string `json:"key"`
}
