// Code generated by tapir. DO NOT EDIT.

package api_key

import (
	database "integro_sdk/types/database"
	primitives "integro_sdk/types/primitives"
)

type CreateApiKeyRequest struct {
	Name primitives.Name `json:"name"`
	GroupUid *primitives.Uid `json:"group_uid"`
	Permissions database.ApiKeyPermissions `json:"permissions"`
}
