// Code generated by tapir. DO NOT EDIT.

package api_key

import (
	primitives "integro_sdk/types/primitives"
)

type ListApiKeysQuery struct {
	// Narrow to these groups, each one the caller may see; omit for everything the caller may see.
	GroupUids *[]primitives.Uid `json:"group_uids"`
}
