// Code generated by tapir. DO NOT EDIT.

package api_key

import (
	axumy "integro_sdk/types/axumy"
)

type UpdateApiKeyRequest struct {
	Name axumy.OptionalUpdate `json:"name"`
	Enabled axumy.OptionalUpdate `json:"enabled"`
}
