// Code generated by tapir. DO NOT EDIT.

package api_key

import (
	database "integro_sdk/types/database"
)

type UpdateApiKeyPermissionsRequest struct {
	Permissions database.ApiKeyPermissions `json:"permissions"`
}
