// Code generated by tapi. DO NOT EDIT.

package event_webhook

import (
	"integro_sdk"
	"strings"
	database "integro_sdk/types/database"
	event "integro_sdk/types/event"
)

// Delete Remove the group's outbound webhook, dropping its pending deliveries.
//
// Requires `ManageWebhook` in the webhook's group.
func Delete(c *client.Client, webhookUid string) (struct{}, error) {
	__path := "/event/webhook/{webhook_uid}"
	__path = strings.Replace(__path, "{webhook_uid}", client.EncodePath(webhookUid), 1)
	return client.Request[struct{}](c, "DELETE", __path, nil, nil)
}
// Get Fetch the group's outbound webhook configuration (the secret is never
// returned here).
//
// Requires `ViewWebhook` in the target group; group-scoped API keys read their own group, others must name it.
func Get(c *client.Client, query event.GetWebhookQuery) (*database.Webhook, error) {
	__path := "/event/webhook"
	return client.Request[*database.Webhook](c, "GET", __path, query, nil)
}
// Set Configure (create or replace) the group's outbound webhook: the group's
// events (optionally narrowed by kind/channel filters) are POSTed to the
// URL in signed batches.
//
// Requires `ManageWebhook` in the target group; group-scoped API keys configure their own group, others must name it.
func Set(c *client.Client, body event.SetWebhookRequest) (event.SetWebhookResponse, error) {
	__path := "/event/webhook"
	return client.Request[event.SetWebhookResponse](c, "PUT", __path, nil, body)
}
