// Code generated by tapi. DO NOT EDIT.

package insight

import (
	__client "integro_sdk"
	insight "integro_sdk/types/insight"
)

// Query Aggregate collected metrics over many accounts of one channel, by day,
// week or month. Only accounts of the declared channel take part; a named
// account of another channel is refused. Breakdown metrics (demographics)
// cannot be aggregated.
//
// Requires `ViewInsights` in every group the query reaches; accounts the caller may not see are refused.
func Query(__c *__client.Client, __body insight.InsightQueryRequest) (insight.InsightQueryResponse, error) {
	__path := "/insight/query"
	return __client.Request[insight.InsightQueryResponse](__c, "POST", __path, nil, __body)
}
