// Code generated by tapir. DO NOT EDIT.

package post

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type CreatePostRequest struct {
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	Content types.PostContent `json:"content"`
	// Hub-side schedule: when set (future instant), the post is stored as
	// `scheduled` and published by the hub when due — uniform across channels.
	ScheduledAt *primitives.Timestamp `json:"scheduled_at"`
}
