// Code generated by tapir. DO NOT EDIT.

package post

type PostInsightsQuery struct {
	// Meta metric names (comma-separated); defaults per media kind.
	Metrics *string `json:"metrics"`
	Period *string `json:"period"`
}
