// Code generated by tapir. DO NOT EDIT.

package post

import (
	primitives "integro_sdk/types/primitives"
)

type SocialPostSummaryQuery struct {
	GroupUid *primitives.Uid `json:"group_uid"`
	SocialAccountUid *primitives.Uid `json:"social_account_uid"`
	// Only posts with at least one third-party comment the account has not answered.
	UnansweredOnly bool `json:"unanswered_only"`
	// Only posts published at or after this instant (ms).
	Since *primitives.Timestamp `json:"since"`
	// Only posts published before this instant (ms).
	Until *primitives.Timestamp `json:"until"`
	// Caption search: a case-insensitive substring.
	Q *string `json:"q"`
}
