// Code generated by tapir. DO NOT EDIT.

package post

import (
	primitives "integro_sdk/types/primitives"
)

type SocialPostSummaryQuery struct {
	// Narrow to these groups, each one the caller may see; omit for everything the caller may see.
	GroupUids *[]primitives.Uid `json:"group_uids"`
	// Narrow to these accounts, each one in scope; naming any account overrides the groups.
	SocialAccountUids *[]primitives.Uid `json:"social_account_uids"`
	// Only posts with at least one third-party comment the account has not answered.
	UnansweredOnly bool `json:"unanswered_only"`
	// Only posts published at or after this instant (ms).
	Since *primitives.Timestamp `json:"since"`
	// Only posts published before this instant (ms).
	Until *primitives.Timestamp `json:"until"`
	// Caption search: a case-insensitive substring.
	Q *string `json:"q"`
}
