// Code generated by tapir. DO NOT EDIT.

package post

// Channel-tagged edit payload — only facebook can edit a published post's
// text on the platform (the Instagram API cannot edit captions), so no
// other channel's shape deserializes. The `channel` must match the post's.
type UpdatePostRequest = interface{}
