// Code generated by tapir. DO NOT EDIT.

package uptime

import (
	primitives "integro_sdk/types/primitives"
)

type ServerUptimeRangeQuery struct {
	Since primitives.Timestamp `json:"since"`
	Until primitives.Timestamp `json:"until"`
}
