// Code generated by tapi. DO NOT EDIT.

package pulse

import (
	"integro_sdk"
	"encoding/json"
	pulse "integro_sdk/types/pulse"
	pulse_sys "integro_sdk/types/pulse_sys"
)

// Current Return the most recent host metrics snapshot.
//
// Requires `ViewPulse`, which only platform staff hold.
func Current(c *client.Client) (pulse_sys.PulseSnapshot, error) {
	__path := "/pulse/current"
	return client.Request[pulse_sys.PulseSnapshot](c, "GET", __path, nil, nil)
}
// Inventory Return the disk, network, and GPU hardware inventory as of a point in time.
//
// Requires `ViewPulse`, which only platform staff hold.
func Inventory(c *client.Client, query pulse.PulseInventoryQuery) (pulse.PulseInventoryResponse, error) {
	__path := "/pulse/inventory"
	return client.Request[pulse.PulseInventoryResponse](c, "GET", __path, query, nil)
}
// Stream Stream live host metrics snapshots over server-sent events.
//
// Requires `ViewPulse`, which only platform staff hold; the stream is gated at connect.
func Stream(c *client.Client, onEvent func(json.RawMessage)) error {
	__path := "/pulse/stream"
	return client.Sse(c, __path, nil, onEvent)
}
// SystemInfo Return static system information about the host running the backend.
//
// Requires `ViewPulse`, which only platform staff hold.
func SystemInfo(c *client.Client) (pulse_sys.PulseSystemInfo, error) {
	__path := "/pulse/system-info"
	return client.Request[pulse_sys.PulseSystemInfo](c, "GET", __path, nil, nil)
}
