// Code generated by tapir. DO NOT EDIT.

package contact_import

// Row counts by verdict — always derived from the rows, never stored, so
// they cannot drift from the ledger they summarize.
type ContactImportCounts struct {
	Total uint32 `json:"total"`
	Pending uint32 `json:"pending"`
	MissingPhone uint32 `json:"missing_phone"`
	InvalidPhone uint32 `json:"invalid_phone"`
	InvalidName uint32 `json:"invalid_name"`
	DuplicateInFile uint32 `json:"duplicate_in_file"`
	Imported uint32 `json:"imported"`
	NotOnWhatsapp uint32 `json:"not_on_whatsapp"`
	CheckFailed uint32 `json:"check_failed"`
	Skipped uint32 `json:"skipped"`
}
