// Code generated by tapir. DO NOT EDIT.

package contact_import

import (
	primitives "integro_sdk/types/primitives"
)

type ListImportsQuery struct {
	// Narrow to these groups, each one the caller may see; omit for everything the caller may see.
	GroupUids *[]primitives.Uid `json:"group_uids"`
	Limit *primitives.Number1_200 `json:"limit"`
}
