// Code generated by tapir. DO NOT EDIT.

package contact_import

import (
	primitives "integro_sdk/types/primitives"
)

// The editable identity of an import: its name. Everything else about it
// is the file and the mapping, fixed at upload.
type UpdateContactImportRequest struct {
	Name primitives.Name `json:"name"`
}
