// Code generated by tapir. DO NOT EDIT.

package google_account

type AnswerBusinessQuestionRequest struct {
	// The question's name, `locations/{id}/questions/{id}`.
	Question string `json:"question"`
	Text string `json:"text"`
}
