// Code generated by tapir. DO NOT EDIT.

package google_account

type BusinessCallsQuery struct {
	// The location's v1 name, `locations/{id}`.
	Location string `json:"location"`
	PageToken *string `json:"page_token"`
}
