// Code generated by tapir. DO NOT EDIT.

package google_account

import (
	primitives "integro_sdk/types/primitives"
)

type BusinessKeywordsQuery struct {
	// The location's v1 name, `locations/{id}`.
	Location string `json:"location"`
	// Range bounds, inclusive, resolved to UTC calendar months. Keyword data
	// lags — the current month is usually empty.
	Start primitives.Timestamp `json:"start"`
	End primitives.Timestamp `json:"end"`
	PageToken *string `json:"page_token"`
}
