// Code generated by tapir. DO NOT EDIT.

package google_account

import (
	primitives "integro_sdk/types/primitives"
)

type ConnectGoogleRequest struct {
	GroupUid primitives.Uid `json:"group_uid"`
	// At least one; connecting later with more capabilities extends the grant
	// (incremental auth) instead of replacing it.
	Capabilities []GoogleCapability `json:"capabilities"`
}
