// Code generated by tapir. DO NOT EDIT.

package google_account

import (
	google "integro_sdk/types/google"
)

type CreateBusinessPostRequest struct {
	// The location's v4 name, `accounts/{id}/locations/{id}`.
	Location string `json:"location"`
	Post google.LocalPost `json:"post"`
}
