// Code generated by tapir. DO NOT EDIT.

package google_account

type DeleteBusinessMediaQuery struct {
	// The item's v4 name, `accounts/{id}/locations/{id}/media/{id}`.
	Media string `json:"media"`
}
