// Code generated by tapir. DO NOT EDIT.

package google_account

type DeleteBusinessPostQuery struct {
	// The post's v4 name, `accounts/{id}/locations/{id}/localPosts/{id}`.
	Post string `json:"post"`
}
