// Code generated by tapir. DO NOT EDIT.

package google_account

type FreeBusyResponse struct {
	// One outcome per requested calendar, in request order.
	Calendars []CalendarBusy `json:"calendars"`
}
