// Code generated by tapir. DO NOT EDIT.

package google_account

import (
	domain "integro_sdk/types/domain"
)

// What a stashed Google grant covers, for the capability-selection screen.
type GoogleReview struct {
	Email string `json:"email"`
	Name string `json:"name"`
	AvatarUrl *string `json:"avatar_url"`
	// The account is already registered in the target group — confirming
	// refreshes its grant and replaces its enabled capabilities.
	Connected bool `json:"connected"`
	// Capabilities the grant covers — the selectable set. Incremental auth
	// unions grants, so this may exceed what was just requested.
	Granted []domain.GoogleCapability `json:"granted"`
	// Capabilities the admin asked for when starting the flow — the
	// pre-checked set.
	Requested []domain.GoogleCapability `json:"requested"`
}
