// Code generated by tapir. DO NOT EDIT.

package google_account

type GoogleReviewQuery struct {
	// The review token from the callback redirect (`?google_review=<token>`).
	Token string `json:"token"`
}
