// Code generated by tapir. DO NOT EDIT.

package google_account

type GoogleConfirmRequest struct {
	Token string `json:"token"`
	// The capabilities to enable on the hub account; the stored scope keeps
	// only these families, even when the grant covers more.
	Capabilities []GoogleCapability `json:"capabilities"`
}
