// Code generated by tapir. DO NOT EDIT.

package google_account

type ListBusinessLocationsQuery struct {
	// The owning account, `accounts/{id}` (from `business.listAccounts`).
	Account string `json:"account"`
	PageToken *string `json:"page_token"`
}
