// Code generated by tapir. DO NOT EDIT.

package google_account

import (
	primitives "integro_sdk/types/primitives"
)

type ListBusinessPostsQuery struct {
	// The location's v4 name, `accounts/{id}/locations/{id}`.
	Location string `json:"location"`
	// Page size; capped at 100 (Google's limit), default 20.
	PageSize *primitives.Number1_100 `json:"page_size"`
	PageToken *string `json:"page_token"`
}
