// Code generated by tapir. DO NOT EDIT.

package google_account

import (
	primitives "integro_sdk/types/primitives"
)

type ListBusinessQuestionsQuery struct {
	// The location's v1 name, `locations/{id}`.
	Location string `json:"location"`
	// Page size; capped at 100 (Google's limit), default 20.
	PageSize *primitives.Number1_100 `json:"page_size"`
	PageToken *string `json:"page_token"`
}
