// Code generated by tapir. DO NOT EDIT.

package google_account

type ListBusinessQuestionsQuery struct {
	// The location's v1 name, `locations/{id}`.
	Location string `json:"location"`
	// Page size; capped at 100, default 20.
	PageSize *uint32 `json:"page_size"`
	PageToken *string `json:"page_token"`
}
