// Code generated by tapir. DO NOT EDIT.

package google_account

type ListBusinessMediaQuery struct {
	// The location's v4 name, `accounts/{id}/locations/{id}`.
	Location string `json:"location"`
	// Page size; capped at 100, default 50.
	PageSize *uint32 `json:"page_size"`
	PageToken *string `json:"page_token"`
}
