// Code generated by tapir. DO NOT EDIT.

package google_account

type ReplyBusinessReviewRequest struct {
	// The review's v4 name, `accounts/{id}/locations/{id}/reviews/{id}`.
	Review string `json:"review"`
	Comment string `json:"comment"`
}
