// Code generated by tapir. DO NOT EDIT.

package google_account

import (
	google "integro_sdk/types/google"
)

type UpdateBusinessMenusRequest struct {
	// The location's v4 name, `accounts/{id}/locations/{id}`.
	Location string `json:"location"`
	// The full menu set — the update replaces the menus wholesale.
	Menus google.FoodMenus `json:"menus"`
}
