// Code generated by tapir. DO NOT EDIT.

package google_account

import (
	google "integro_sdk/types/google"
)

type UpdateBusinessLocationRequest struct {
	// The location's v1 name, `locations/{id}`.
	Location string `json:"location"`
	// The new values for the masked fields.
	Update google.Location `json:"update"`
	// Comma-separated camelCase fields to write (e.g.
	// `profile.description,phoneNumbers.primaryPhone,websiteUri`); a masked
	// field absent from `update` is cleared.
	UpdateMask string `json:"update_mask"`
}
