// Code generated by tapir. DO NOT EDIT.

package google_account

import (
	google "integro_sdk/types/google"
)

type UpdateBusinessPostRequest struct {
	// The post's v4 name, `accounts/{id}/locations/{id}/localPosts/{id}`.
	Post string `json:"post"`
	// The new values for the masked fields.
	Update google.LocalPost `json:"update"`
	// Comma-separated camelCase fields to write (e.g. `summary,callToAction`).
	UpdateMask string `json:"update_mask"`
}
