// Code generated by tapi. DO NOT EDIT.

package google

import (
	__client "integro_sdk"
	google_account "integro_sdk/types/google_account"
)

// Callback Google OAuth redirect target: consumes the state, exchanges the code, and
// stashes the grant snapshot for review — nothing is registered yet; always
// redirects the browser back to the frontend, with a review token on
// success.
//
// Public — no authentication required; authorization comes from the one-shot state token issued by `google.connect`.
func Callback(__c *__client.Client, __query google_account.GoogleCallbackQuery) (struct{}, error) {
	__path := "/google/callback"
	return __client.Request[struct{}](__c, "GET", __path, __query, nil)
}
// Connect Start the Google OAuth flow for a group with the chosen capabilities
// (calendar, business profile), returning the consent dialog URL; the
// granted account is connected to the group by the callback.
//
// Requires `ConnectSocialAccounts` in the named group.
func Connect(__c *__client.Client, __body google_account.ConnectGoogleRequest) (google_account.ConnectGoogleResponse, error) {
	__path := "/google/connect"
	return __client.Request[google_account.ConnectGoogleResponse](__c, "POST", __path, nil, __body)
}
// ConnectConfirm Register (or refresh) the account from a stashed grant, enabling exactly
// the chosen capabilities (one-shot). A granted-but-unchosen capability
// stays out of the hub until a future connect enables it.
//
// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
func ConnectConfirm(__c *__client.Client, __body google_account.GoogleConfirmRequest) (struct{}, error) {
	__path := "/google/connect/confirm"
	return __client.Request[struct{}](__c, "POST", __path, nil, __body)
}
// ConnectReview Load a stashed Google grant for the capability-selection screen: the
// account's identity plus which capabilities the grant covers and which
// were requested. Repeatable; only confirm consumes the stash.
//
// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
func ConnectReview(__c *__client.Client, __query google_account.GoogleReviewQuery) (google_account.GoogleReview, error) {
	__path := "/google/connect/review"
	return __client.Request[google_account.GoogleReview](__c, "GET", __path, __query, nil)
}
