// Code generated by tapi. DO NOT EDIT.

package social_post

import (
	__client "integro_sdk"
	__strings "strings"
	domain "integro_sdk/types/domain"
	insight "integro_sdk/types/insight"
	post "integro_sdk/types/post"
)

// Get Fetch one platform post by uid.
//
// Requires `ViewPosts` in the post's group.
func Get(__c *__client.Client, socialPostUid string) (domain.SocialPost, error) {
	__path := "/social-post/{social_post_uid}"
	__path = __strings.Replace(__path, "{social_post_uid}", __client.EncodePath(socialPostUid), 1)
	return __client.Request[domain.SocialPost](__c, "GET", __path, nil, nil)
}
// InsightsHistory Day-by-day history of a platform post's collected metrics, in its channel's
// own vocabulary. Posts are re-read on a schedule that slows with age (every
// 5 minutes in the first day, every 3 hours after a month), so the newest day
// is often still partial.
//
// Requires `ViewInsights` in the group of the post's account.
func InsightsHistory(__c *__client.Client, socialPostUid string, __query insight.InsightHistoryQuery) (insight.SocialPostInsightHistory, error) {
	__path := "/social-post/{social_post_uid}/insight/history"
	__path = __strings.Replace(__path, "{social_post_uid}", __client.EncodePath(socialPostUid), 1)
	return __client.Request[insight.SocialPostInsightHistory](__c, "GET", __path, __query, nil)
}
// List List the posts that stand on the platforms, newest first: every post the
// hub knows about an account, published through it or not, with the
// platform's comment and like counts and how many third-party comments the
// account has not answered. `before` pages backwards.
//
// Requires `ViewPosts`; the list covers only posts of groups where the caller holds it.
func List(__c *__client.Client, __query post.ListSocialPostsQuery) ([]domain.SocialPost, error) {
	__path := "/social-post"
	return __client.Request[[]domain.SocialPost](__c, "GET", __path, __query, nil)
}
// Sync Start a re-read of the account's posts from its platform in the background
// and answer at once: the 25 most recent plus every post with comments, their
// thumbnails and, for posts seen for the first time, their whole comment
// thread. Every post the sync touches emits `social_post_updated`. Allowed
// once per account every five minutes; the hub runs it by itself once when an
// account connects. Only facebook_alt and instagram_alt accounts can be synced.
//
// Requires `ViewPosts` in the account's group; throttled to one call per account every five minutes.
func Sync(__c *__client.Client, socialAccountUid string) (struct{}, error) {
	__path := "/social-account/{social_account_uid}/social-post/sync"
	__path = __strings.Replace(__path, "{social_account_uid}", __client.EncodePath(socialAccountUid), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
