// Code generated by tapir. DO NOT EDIT.

package domain

// What still acts on an account from inside its group, and so has to travel
// with it when the account changes group. Finished work stays behind: a
// canceled campaign, or a contact import that is done or canceled, is not
// counted.
type AccountReferences struct {
	// GoHighLevel locations delivering into this account.
	GhlLocations uint64 `json:"ghl_locations"`
	// Campaigns sending only from this account.
	Campaigns uint64 `json:"campaigns"`
	// Contact imports loading only into this account.
	ContactImports uint64 `json:"contact_imports"`
	// Campaigns that also send from other accounts of the group, which cannot follow it.
	SharedCampaigns uint64 `json:"shared_campaigns"`
	// Contact imports that also load into other accounts of the group, which cannot follow it.
	SharedContactImports uint64 `json:"shared_contact_imports"`
}
