// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

type ApiKey struct {
	Uid primitives.Uid `json:"uid"`
	GroupUid *primitives.Uid `json:"group_uid"`
	Name primitives.Name `json:"name"`
	Permissions ApiKeyPermissions `json:"permissions"`
	Enabled bool `json:"enabled"`
	CreatedBy primitives.Uid `json:"created_by"`
	RevokedAt *primitives.Timestamp `json:"revoked_at"`
	RevokedBy *primitives.Uid `json:"revoked_by"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
