// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

type AuditLog struct {
	UserUid *primitives.Uid `json:"user_uid"`
	ApiKeyUid *primitives.Uid `json:"api_key_uid"`
	GroupUid *primitives.Uid `json:"group_uid"`
	Action AuditAction `json:"action"`
	Resource AuditResource `json:"resource"`
	ResourceUid string `json:"resource_uid"`
	Success bool `json:"success"`
	Details string `json:"details"`
	SocketAddr string `json:"socket_addr"`
	RecordedAt primitives.Timestamp `json:"recorded_at"`
}
