// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

// One bulk-messaging campaign: the schedule, the ceilings and the template
// wheel's cursor. The audience lives in `campaign_recipient`, the wheel in
// `campaign_template`; every progress counter is derived from them.
type Campaign struct {
	Uid primitives.Uid `json:"uid"`
	GroupUid primitives.Uid `json:"group_uid"`
	Name primitives.Name `json:"name"`
	Status CampaignStatus `json:"status"`
	MinIntervalMs primitives.Number1000_86400000 `json:"min_interval_ms"`
	MaxIntervalMs primitives.Number1000_86400000 `json:"max_interval_ms"`
	Timezone primitives.Timezone `json:"timezone"`
	WindowStartMinute primitives.Number0_1439 `json:"window_start_minute"`
	WindowEndMinute primitives.Number0_1439 `json:"window_end_minute"`
	Weekdays primitives.Number1_127 `json:"weekdays"`
	StartsAt *primitives.Timestamp `json:"starts_at"`
	EndsAt *primitives.Timestamp `json:"ends_at"`
	MaxPerDay *primitives.Number1_100000 `json:"max_per_day"`
	MaxPerAccountPerDay *primitives.Number1_100000 `json:"max_per_account_per_day"`
	TemplateMode TemplateRotation `json:"template_mode"`
	// The linear wheel's position; advances on every dispatch, in either mode.
	TemplateCursor uint32 `json:"template_cursor"`
	CooldownDays *primitives.Number1_365 `json:"cooldown_days"`
	CreatedByUid *primitives.Uid `json:"created_by_uid"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
