// Code generated by tapir. DO NOT EDIT.

package domain

// Where a campaign stands in its lifecycle. Config, wheel, accounts and
// queue are editable while `Draft`, `Paused` or `Done`; `start` moves it to
// `Running`, and the dispatcher advances each participating account of a
// `Running` campaign by at most one send per tick.
type CampaignStatus string

const (
	CampaignStatusDraft CampaignStatus = "draft"
	CampaignStatusRunning CampaignStatus = "running"
	CampaignStatusPaused CampaignStatus = "paused"
	CampaignStatusDone CampaignStatus = "done"
	CampaignStatusCanceled CampaignStatus = "canceled"
)
