// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

// One CSV upload: the mapping the operator confirmed and where the load
// stands. The rows (and their verdicts) live in `contact_import_row`; every
// counter a page renders is derived from them, never stored here.
type ContactImport struct {
	Uid primitives.Uid `json:"uid"`
	GroupUid primitives.Uid `json:"group_uid"`
	// The operator's name for the batch; `filename` is where it came from.
	Name primitives.Name `json:"name"`
	Filename string `json:"filename"`
	Status ContactImportStatus `json:"status"`
	// The CSV header row; `ContactImportRow::raw` indexes into it.
	Columns []string `json:"columns"`
	// Column indexes the operator mapped.
	PhoneColumn uint32 `json:"phone_column"`
	NameColumn *uint32 `json:"name_column"`
	// The country a bare number is read against (e.g. `55`).
	DefaultCallingCode string `json:"default_calling_code"`
	CreatedByUid *primitives.Uid `json:"created_by_uid"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
