// Code generated by tapir. DO NOT EDIT.

package domain

// A shared contact entry, squashed to the fields every channel can carry.
type ContactCard struct {
	Name string `json:"name"`
	Phones []string `json:"phones"`
}
