// Code generated by tapir. DO NOT EDIT.

package domain

type EmailQueueStatus string

const (
	EmailQueueStatusPending EmailQueueStatus = "pending"
	EmailQueueStatusSending EmailQueueStatus = "sending"
	EmailQueueStatusSent EmailQueueStatus = "sent"
	EmailQueueStatusFailed EmailQueueStatus = "failed"
)
