// Code generated by tapir. DO NOT EDIT.

package domain

// Tags a queued email so the worker can update the originating record on
// completion (e.g. flip an `user_invite.email_status` to Sent/Failed).
type EmailKind string

const (
	EmailKindOther EmailKind = "other"
	EmailKindUserInvite EmailKind = "user_invite"
	EmailKindUserPasswordReset EmailKind = "user_password_reset"
)
