// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

type EmailQueueItem struct {
	Id uint64 `json:"id"`
	ToEmail string `json:"to_email"`
	ToName *string `json:"to_name"`
	Subject string `json:"subject"`
	TemplateName EmailTemplateName `json:"template_name"`
	Status EmailQueueStatus `json:"status"`
	Attempts uint8 `json:"attempts"`
	// When set, the worker won't retry this row until `next_retry_at <= now`.
	// `NULL` means "ready immediately" (fresh enqueue or operator-triggered retry).
	NextRetryAt *primitives.Timestamp `json:"next_retry_at"`
	ErrorMessage *string `json:"error_message"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	SentAt *primitives.Timestamp `json:"sent_at"`
}
