// Code generated by tapir. DO NOT EDIT.

package domain

// The kind of a [`HubEvent`], named exactly as its `event` tag.
type EventKind string

const (
	EventKindMessageReceived EventKind = "message_received"
	EventKindMessageSent EventKind = "message_sent"
	EventKindMessageQueued EventKind = "message_queued"
	EventKindMessageCanceled EventKind = "message_canceled"
	EventKindMessageReaction EventKind = "message_reaction"
	EventKindMessageDelivered EventKind = "message_delivered"
	EventKindMessageRead EventKind = "message_read"
	EventKindMessageFailed EventKind = "message_failed"
	EventKindMessageUpdated EventKind = "message_updated"
	EventKindMessageDeleted EventKind = "message_deleted"
	EventKindParticipantPresence EventKind = "participant_presence"
	EventKindCommentReceived EventKind = "comment_received"
	EventKindCommentUpdated EventKind = "comment_updated"
	EventKindCommentDeleted EventKind = "comment_deleted"
	EventKindSocialPostUpdated EventKind = "social_post_updated"
	EventKindPostPublished EventKind = "post_published"
	EventKindPostFailed EventKind = "post_failed"
	EventKindConversationUpdated EventKind = "conversation_updated"
	EventKindConversationCleared EventKind = "conversation_cleared"
	EventKindConversationRemoved EventKind = "conversation_removed"
	EventKindContactPresence EventKind = "contact_presence"
	EventKindCallRinging EventKind = "call_ringing"
	EventKindCallUpdated EventKind = "call_updated"
	EventKindCallEnded EventKind = "call_ended"
	EventKindAccountUpdated EventKind = "account_updated"
	EventKindAccountRemoved EventKind = "account_removed"
	EventKindReviewReceived EventKind = "review_received"
)
