// Code generated by tapir. DO NOT EDIT.

package domain

// A Facebook Page publication. `message` is the post text / media caption /
// video description; `place_id` tags a location (feed and photo posts only).
type FacebookPostContent struct {
	Media FacebookMedia `json:"media"`
	Message *string `json:"message"`
	PlaceId *string `json:"place_id"`
}
