// Code generated by tapir. DO NOT EDIT.

package domain

// One metric as a day-by-day series.
type FacebookAltAccountSeries struct {
	Metric FacebookAltAccountMetric `json:"metric"`
	Points []InsightPoint `json:"points"`
}
