// Code generated by tapir. DO NOT EDIT.

package domain

// Facebook post metrics as the alternate gateway reports them.
type FacebookAltPostMetric string

const (
	FacebookAltPostMetricImpressions FacebookAltPostMetric = "impressions"
	FacebookAltPostMetricReach FacebookAltPostMetric = "reach"
	FacebookAltPostMetricLikes FacebookAltPostMetric = "likes"
	FacebookAltPostMetricComments FacebookAltPostMetric = "comments"
	FacebookAltPostMetricShares FacebookAltPostMetric = "shares"
	FacebookAltPostMetricClicks FacebookAltPostMetric = "clicks"
	FacebookAltPostMetricViews FacebookAltPostMetric = "views"
	FacebookAltPostMetricEngagementRate FacebookAltPostMetric = "engagement_rate"
	FacebookAltPostMetricReactionsLike FacebookAltPostMetric = "reactions_like"
	FacebookAltPostMetricReactionsLove FacebookAltPostMetric = "reactions_love"
	FacebookAltPostMetricReactionsHaha FacebookAltPostMetric = "reactions_haha"
	FacebookAltPostMetricReactionsWow FacebookAltPostMetric = "reactions_wow"
	FacebookAltPostMetricReactionsSad FacebookAltPostMetric = "reactions_sad"
	FacebookAltPostMetricReactionsAngry FacebookAltPostMetric = "reactions_angry"
	FacebookAltPostMetricReactionsCare FacebookAltPostMetric = "reactions_care"
)
