// Code generated by tapir. DO NOT EDIT.

package domain

// One metric as a day-by-day series.
type FacebookPostSeries struct {
	Metric FacebookPostMetric `json:"metric"`
	Points []InsightPoint `json:"points"`
}
