// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

// One aggregated period of one metric across the queried subjects.
type FacebookAltAccountBucket struct {
	PeriodStart primitives.Timestamp `json:"period_start"`
	Metric FacebookAltAccountMetric `json:"metric"`
	Value float64 `json:"value"`
	// How many subjects — accounts, or posts — contributed rows to the period.
	Subjects int64 `json:"subjects"`
}
