// Code generated by tapir. DO NOT EDIT.

package domain

// Facebook Page account metrics as the alternate gateway reports them.
type FacebookAltAccountMetric string

const (
	FacebookAltAccountMetricFollowers FacebookAltAccountMetric = "followers"
	FacebookAltAccountMetricPageMediaView FacebookAltAccountMetric = "page_media_view"
	FacebookAltAccountMetricPageViewsTotal FacebookAltAccountMetric = "page_views_total"
	FacebookAltAccountMetricPagePostEngagements FacebookAltAccountMetric = "page_post_engagements"
	FacebookAltAccountMetricPageVideoViews FacebookAltAccountMetric = "page_video_views"
	FacebookAltAccountMetricPageVideoViewTime FacebookAltAccountMetric = "page_video_view_time"
	FacebookAltAccountMetricPageFollows FacebookAltAccountMetric = "page_follows"
	FacebookAltAccountMetricFollowersGained FacebookAltAccountMetric = "followers_gained"
	FacebookAltAccountMetricFollowersLost FacebookAltAccountMetric = "followers_lost"
)
