// Code generated by tapir. DO NOT EDIT.

package domain

// The media word the alternate gateway reports for a post.
type GatewayMediaType string

const (
	GatewayMediaTypeImage GatewayMediaType = "image"
	GatewayMediaTypeVideo GatewayMediaType = "video"
	GatewayMediaTypeCarousel GatewayMediaType = "carousel"
	GatewayMediaTypeText GatewayMediaType = "text"
	GatewayMediaTypeOther GatewayMediaType = "other"
)
