// Code generated by tapir. DO NOT EDIT.

package domain

// A surface a google grant can cover; the connect asks for a set and the
// review shows which of them the grant actually returned.
type GoogleCapability string

const (
	GoogleCapabilityCalendar GoogleCapability = "calendar"
	GoogleCapabilityBusiness GoogleCapability = "business"
)
