// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

type Group struct {
	Uid primitives.Uid `json:"uid"`
	Name primitives.Name `json:"name"`
	Enabled bool `json:"enabled"`
	LogoContentType *string `json:"logo_content_type"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
