// Code generated by tapir. DO NOT EDIT.

package domain

// Every event the hub emits, in the exact shape delivered to its outbound
// transports: the group webhook (as the POST body) and the WebSocket stream
// (as one frame). The `event` tag names the kind ([`EventKind`]). The
// live-only kinds (the presence kinds) reach the socket only — they never
// enter the replay ring the webhook batcher reads.
type HubEvent = interface{}
