// Code generated by tapir. DO NOT EDIT.

package domain

// Instagram account metrics as the alternate gateway reports them;
// `follower_*` are daily demographic breakdowns.
type InstagramAltAccountMetric string

const (
	InstagramAltAccountMetricFollowers InstagramAltAccountMetric = "followers"
	InstagramAltAccountMetricReach InstagramAltAccountMetric = "reach"
	InstagramAltAccountMetricViews InstagramAltAccountMetric = "views"
	InstagramAltAccountMetricAccountsEngaged InstagramAltAccountMetric = "accounts_engaged"
	InstagramAltAccountMetricTotalInteractions InstagramAltAccountMetric = "total_interactions"
	InstagramAltAccountMetricLikes InstagramAltAccountMetric = "likes"
	InstagramAltAccountMetricComments InstagramAltAccountMetric = "comments"
	InstagramAltAccountMetricSaves InstagramAltAccountMetric = "saves"
	InstagramAltAccountMetricShares InstagramAltAccountMetric = "shares"
	InstagramAltAccountMetricReplies InstagramAltAccountMetric = "replies"
	InstagramAltAccountMetricReposts InstagramAltAccountMetric = "reposts"
	InstagramAltAccountMetricFollowsAndUnfollows InstagramAltAccountMetric = "follows_and_unfollows"
	InstagramAltAccountMetricProfileLinksTaps InstagramAltAccountMetric = "profile_links_taps"
	InstagramAltAccountMetricFollowerAge InstagramAltAccountMetric = "follower_age"
	InstagramAltAccountMetricFollowerGender InstagramAltAccountMetric = "follower_gender"
	InstagramAltAccountMetricFollowerCity InstagramAltAccountMetric = "follower_city"
	InstagramAltAccountMetricFollowerCountry InstagramAltAccountMetric = "follower_country"
)
