// Code generated by tapir. DO NOT EDIT.

package domain

// Instagram media metrics, Meta's own names.
type InstagramPostMetric string

const (
	InstagramPostMetricReach InstagramPostMetric = "reach"
	InstagramPostMetricViews InstagramPostMetric = "views"
	InstagramPostMetricLikes InstagramPostMetric = "likes"
	InstagramPostMetricComments InstagramPostMetric = "comments"
	InstagramPostMetricSaved InstagramPostMetric = "saved"
	InstagramPostMetricShares InstagramPostMetric = "shares"
	InstagramPostMetricReplies InstagramPostMetric = "replies"
)
