// Code generated by tapir. DO NOT EDIT.

package domain

// One metric as a day-by-day series.
type InstagramAltAccountSeries struct {
	Metric InstagramAltAccountMetric `json:"metric"`
	Points []InsightPoint `json:"points"`
}
