// Code generated by tapir. DO NOT EDIT.

package domain

// One metric as a day-by-day series.
type InstagramPostSeries struct {
	Metric InstagramPostMetric `json:"metric"`
	Points []InsightPoint `json:"points"`
}
