// Code generated by tapir. DO NOT EDIT.

package domain

// One metric as a day-by-day series.
type InstagramAltPostSeries struct {
	Metric InstagramAltPostMetric `json:"metric"`
	Points []InsightPoint `json:"points"`
}
