// Code generated by tapir. DO NOT EDIT.

package domain

// The kinds an Instagram media can be, as the hub published it.
type InstagramMediaKind string

const (
	InstagramMediaKindImage InstagramMediaKind = "image"
	InstagramMediaKindCarousel InstagramMediaKind = "carousel"
	InstagramMediaKindReel InstagramMediaKind = "reel"
	InstagramMediaKindStory InstagramMediaKind = "story"
)
