// Code generated by tapir. DO NOT EDIT.

package domain

// Which dialog opens an Instagram grant on the alternate channel.
type InstagramLogin string

const (
	InstagramLoginInstagramLogin InstagramLogin = "instagram_login"
	InstagramLoginFacebookLogin InstagramLogin = "facebook_login"
)
