// Code generated by tapir. DO NOT EDIT.

package domain

// Instagram account metrics, Meta's own names.
type InstagramAccountMetric string

const (
	InstagramAccountMetricReach InstagramAccountMetric = "reach"
	InstagramAccountMetricFollowerCount InstagramAccountMetric = "follower_count"
	InstagramAccountMetricProfileViews InstagramAccountMetric = "profile_views"
)
