// Code generated by tapir. DO NOT EDIT.

package domain

import (
	meta "integro_sdk/types/meta"
)

// One carousel item: exactly one of `image` / `video`.
type InstagramCarouselItem struct {
	Image *MediaRef `json:"image"`
	Video *MediaRef `json:"video"`
	UserTags []meta.InstagramUserTag `json:"user_tags"`
}
