// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

type Issue struct {
	Uid primitives.Uid `json:"uid"`
	Category IssueCategory `json:"category"`
	Severity IssueSeverity `json:"severity"`
	Status IssueStatus `json:"status"`
	Description primitives.Text0_8000 `json:"description"`
	// The page the reporter was on, when they chose to name one.
	Url *primitives.Text0_2048 `json:"url"`
	// The screenshots attached at report time, as hosted media.
	Screenshots []primitives.Uid `json:"screenshots"`
	ReportedBy primitives.Uid `json:"reported_by"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
