// Code generated by tapir. DO NOT EDIT.

package domain

type IssueStatus string

const (
	IssueStatusOpen IssueStatus = "open"
	IssueStatusTriaged IssueStatus = "triaged"
	IssueStatusResolved IssueStatus = "resolved"
	IssueStatusWontFix IssueStatus = "wont_fix"
)
