// Code generated by tapir. DO NOT EDIT.

package domain

type IssueSeverity string

const (
	IssueSeverityLow IssueSeverity = "low"
	IssueSeverityMedium IssueSeverity = "medium"
	IssueSeverityHigh IssueSeverity = "high"
	IssueSeverityCritical IssueSeverity = "critical"
)
