// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

type Issue struct {
	Id uint64 `json:"id"`
	Uid primitives.Uid `json:"uid"`
	Category IssueCategory `json:"category"`
	Severity IssueSeverity `json:"severity"`
	Status IssueStatus `json:"status"`
	Description primitives.Text0_8000 `json:"description"`
	Details IssueDetails `json:"details"`
	Screenshots IssueScreenshots `json:"screenshots"`
	ReportedBy primitives.Uid `json:"reported_by"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
