// Code generated by tapir. DO NOT EDIT.

package domain

// A media as content names it. `hosted` is a file the hub stores, served at
// `GET /media/{uid}` to a caller who may see something that references it;
// `remote` is an address outside the hub — a platform CDN link the rehost
// worker has not copied yet, or a public URL a caller supplied. The hub
// never hands a hosted uid to a platform as a bare URL: a send or a publish
// presents it as a signed address that expires.
type MediaRef = interface{}
