// Code generated by tapir. DO NOT EDIT.

package domain

// Coarse kind of a stored media file — mirrors Meta's attachment kinds, and
// is exactly what the `kind` column of a media row holds. Derived from the
// content type at ingest; never trusted from a caller.
type MediaKind string

const (
	MediaKindImage MediaKind = "image"
	MediaKindVideo MediaKind = "video"
	MediaKindAudio MediaKind = "audio"
	MediaKindFile MediaKind = "file"
)
