// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

type Mention struct {
	// Strictly increasing insert order — the polling cursor.
	Id uint64 `json:"id"`
	Uid primitives.Uid `json:"uid"`
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	// The media where the account was mentioned (caption or comment).
	ExternalMediaId string `json:"external_media_id"`
	// Set when the mention happened inside a comment.
	ExternalCommentId *string `json:"external_comment_id"`
	CreatedAt primitives.Timestamp `json:"created_at"`
}
