// Code generated by tapir. DO NOT EDIT.

package domain

// A reaction attached to a message. `reactor_id` is the platform participant
// id (or the page/account id when the reaction came from the business side).
type MessageReaction struct {
	ReactorId string `json:"reactor_id"`
	// The unicode emoji; a Meta reaction name (e.g. `love`) is stored as its
	// glyph. `None` when the platform sent neither a glyph nor a known name.
	Emoji *string `json:"emoji"`
}
