// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

type Message struct {
	// Strictly increasing insert order — the polling cursor.
	Id uint64 `json:"id"`
	Uid primitives.Uid `json:"uid"`
	ConversationUid primitives.Uid `json:"conversation_uid"`
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	ParticipantId string `json:"participant_id"`
	Direction MessageDirection `json:"direction"`
	Content MessageContent `json:"content"`
	Reactions []MessageReaction `json:"reactions"`
	// Local uid of the message this one replies to, when we hold it.
	ReplyToUid *primitives.Uid `json:"reply_to_uid"`
	// The ad this message arrived from (whatsapp: official reports it as
	// `referral`, the session-backed flavors as `contextInfo.externalAdReply`).
	// Set only on the first message after an ad tap.
	Referral *Referral `json:"referral"`
	Status MessageStatus `json:"status"`
	Error *string `json:"error"`
	ExternalMid *string `json:"external_mid"`
	// Client-supplied dedup key: a keyed retry of a failed send updates this
	// row in place instead of inserting a sibling.
	IdempotencyKey *string `json:"idempotency_key"`
	// Who produced this outbound row: a machine client through the api, a hub
	// operator, or a platform echo (paired phone / whatsapp web / meta
	// business inbox, incl. history imports). `None` on inbound rows and rows
	// stored before the field existed.
	SentBy *MessageSentBy `json:"sent_by"`
	// The api key / user uid behind `sent_by`, when it names one.
	SentByUid *primitives.Uid `json:"sent_by_uid"`
	// The send sequence this queued row belongs to; `None` for every send that stands alone.
	Burst *string `json:"burst"`
	// Set on a copy the hub forwarded from another conversation; the
	// session-backed whatsapp channels show it as forwarded.
	Forwarded bool `json:"forwarded"`
	// Set when the message text was edited on the platform.
	EditedAt *primitives.Timestamp `json:"edited_at"`
	// Set when the message was revoked on the platform; the row stays.
	DeletedAt *primitives.Timestamp `json:"deleted_at"`
	SentAt primitives.Timestamp `json:"sent_at"`
	CreatedAt primitives.Timestamp `json:"created_at"`
}
