// Code generated by tapir. DO NOT EDIT.

package domain

import (
	meta "integro_sdk/types/meta"
)

// Messenger/Instagram DM payload (Send API). Attachments carry no captions;
// quick replies may attach to any content.
type MessengerSend struct {
	Content MessengerContent `json:"content"`
	// Lifts the standard 24h response window (`human_agent` = 7 days; the
	// Meta app must hold the `human_agent` permission).
	Tag *meta.MessageTag `json:"tag"`
	// Up to 13 quick-reply chips.
	QuickReplies *[]QuickReply `json:"quick_replies"`
}
