// Code generated by tapir. DO NOT EDIT.

package domain

// Stored message content, identical across channels: every row carries
// either a sendable shape or an inbound-only one. Untagged over the two
// internally-tagged halves, so the JSON stays the flat `kind`-tagged object
// it always was — the split exists only in the type system.
type MessageContent = interface{}
