// Code generated by tapir. DO NOT EDIT.

package domain

// Which sound a new message plays in the operator's browser, if any. The
// sounds themselves ship with the frontend; the choice is personal to the
// operator and follows them across devices.
type MessageChime string

const (
	MessageChimeSoundOne MessageChime = "sound_one"
	MessageChimeSoundTwo MessageChime = "sound_two"
	MessageChimeSoundThree MessageChime = "sound_three"
	MessageChimeSoundFour MessageChime = "sound_four"
	MessageChimeOff MessageChime = "off"
)
