// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

// A message enriched with its channel/group context — the squashed shape
// CRMs consume from both the polling feed and the webhook fan-out.
type MessageWithContext struct {
	Message
	Channel Channel `json:"channel"`
	GroupUid primitives.Uid `json:"group_uid"`
}
