// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

// Native (whatsmeow) payload: text, media, locations and one contact card —
// the bridge sends no interactive shapes.
type NativeSend struct {
	Content NativeContent `json:"content"`
	// Send as a reply to this message (must belong to the same conversation).
	ReplyToUid *primitives.Uid `json:"reply_to_uid"`
}
