// Code generated by tapir. DO NOT EDIT.

package domain

// How a native whatsapp account announces itself online. An online presence
// silences the paired phone's notifications and stamps every delivery
// receipt as active, so the default follows the people actually looking.
type PresencePolicy string

const (
	PresencePolicyFollowsOperator PresencePolicy = "follows_operator"
	PresencePolicyAlwaysInvisible PresencePolicy = "always_invisible"
)
