// Code generated by tapir. DO NOT EDIT.

package domain

// Every kind of account the hub connects — the account registry's axis.
// Distinct from [`Channel`], which is the *messaging-domain* discriminator
// carried by conversations, messages, and posts: every messaging provider
// projects onto a channel, while non-messaging providers (calendar) have
// none — so messaging payloads can never name them.
//
// Adding an integration = a variant here + its connect flow + its
// capability module; the registry (table, CRUD, listing UI) is shared.
type Provider string

const (
	ProviderFacebook Provider = "facebook"
	ProviderInstagram Provider = "instagram"
	ProviderWhatsapp Provider = "whatsapp"
	ProviderWhatsappStevo Provider = "whatsapp_stevo"
	ProviderWhatsappNative Provider = "whatsapp_native"
	ProviderGoogle Provider = "google"
)
