// Code generated by tapir. DO NOT EDIT.

package domain

type PulseDiskMetricRow struct {
	RecordedAt int64 `json:"recorded_at"`
	Name string `json:"name"`
	AvailableBytes uint64 `json:"available_bytes"`
	UsagePercent float32 `json:"usage_percent"`
	ReadBytesPerSec float64 `json:"read_bytes_per_sec"`
	WrittenBytesPerSec float64 `json:"written_bytes_per_sec"`
	ReadIops float64 `json:"read_iops"`
	WriteIops float64 `json:"write_iops"`
	TempMaxCelsius *float32 `json:"temp_max_celsius"`
}
