// Code generated by tapir. DO NOT EDIT.

package domain

type PulseNetworkMetricRow struct {
	RecordedAt int64 `json:"recorded_at"`
	Interface string `json:"interface"`
	ReceivedBytesPerSec float64 `json:"received_bytes_per_sec"`
	TransmittedBytesPerSec float64 `json:"transmitted_bytes_per_sec"`
	ReceivedPackets uint64 `json:"received_packets"`
	TransmittedPackets uint64 `json:"transmitted_packets"`
	ReceivedErrors uint64 `json:"received_errors"`
	TransmittedErrors uint64 `json:"transmitted_errors"`
}
