// Code generated by tapir. DO NOT EDIT.

package domain

type PulseDiskInventoryRow struct {
	RecordedAt int64 `json:"recorded_at"`
	Name string `json:"name"`
	MountPoint string `json:"mount_point"`
	FsType string `json:"fs_type"`
	TotalBytes uint64 `json:"total_bytes"`
	Removed bool `json:"removed"`
}
