// Code generated by tapir. DO NOT EDIT.

package domain

type PulseGpuInventoryRow struct {
	RecordedAt int64 `json:"recorded_at"`
	GpuIndex uint32 `json:"gpu_index"`
	Name string `json:"name"`
	Vendor string `json:"vendor"`
	VramTotalBytes uint64 `json:"vram_total_bytes"`
	PowerLimitWatts float32 `json:"power_limit_watts"`
	Removed bool `json:"removed"`
}
