// Code generated by tapir. DO NOT EDIT.

package domain

type PulseNetworkInventoryRow struct {
	RecordedAt int64 `json:"recorded_at"`
	Interface string `json:"interface"`
	MacAddress string `json:"mac_address"`
	Ipv4Addresses []string `json:"ipv4_addresses"`
	Ipv6Addresses []string `json:"ipv6_addresses"`
	LinkSpeedMbps *uint32 `json:"link_speed_mbps"`
	IsPhysical bool `json:"is_physical"`
	Removed bool `json:"removed"`
}
