// Code generated by tapir. DO NOT EDIT.

package domain

type PulseHostMetricRow struct {
	RecordedAt int64 `json:"recorded_at"`
	UptimeSecs uint64 `json:"uptime_secs"`
	CpuGlobalUsage float32 `json:"cpu_global_usage"`
	CpuFrequencyMhz uint64 `json:"cpu_frequency_mhz"`
	CpuPerCoreUsage []float32 `json:"cpu_per_core_usage"`
	CpuPerCoreFrequencyMhz []uint64 `json:"cpu_per_core_frequency_mhz"`
	CpuPhysicalCores uint32 `json:"cpu_physical_cores"`
	CpuLogicalCores uint32 `json:"cpu_logical_cores"`
	CpuLoadAvgOne float64 `json:"cpu_load_avg_one"`
	CpuLoadAvgFive float64 `json:"cpu_load_avg_five"`
	CpuLoadAvgFifteen float64 `json:"cpu_load_avg_fifteen"`
	CpuTempMaxCelsius *float32 `json:"cpu_temp_max_celsius"`
	CpuTempAvgCelsius *float32 `json:"cpu_temp_avg_celsius"`
	RamTotalBytes uint64 `json:"ram_total_bytes"`
	RamUsedBytes uint64 `json:"ram_used_bytes"`
	RamAvailableBytes uint64 `json:"ram_available_bytes"`
	RamUsagePercent float32 `json:"ram_usage_percent"`
	RamSwapTotalBytes uint64 `json:"ram_swap_total_bytes"`
	RamSwapUsedBytes uint64 `json:"ram_swap_used_bytes"`
	RamSwapUsagePercent float32 `json:"ram_swap_usage_percent"`
	RamPageInBytesPerSec float64 `json:"ram_page_in_bytes_per_sec"`
	RamPageOutBytesPerSec float64 `json:"ram_page_out_bytes_per_sec"`
	RamSwapInBytesPerSec float64 `json:"ram_swap_in_bytes_per_sec"`
	RamSwapOutBytesPerSec float64 `json:"ram_swap_out_bytes_per_sec"`
	RamTempMaxCelsius *float32 `json:"ram_temp_max_celsius"`
}
