// Code generated by tapir. DO NOT EDIT.

package domain

// What one bucket stands for: the thing a rule counts against, one counter
// per distinct value. A rule may draw from several — a login attempt spends
// from the caller's IP bucket *and* the e-mail's bucket, and is refused when
// either runs dry.
type RateLimitBucket string

const (
	RateLimitBucketIp RateLimitBucket = "ip"
	RateLimitBucketUser RateLimitBucket = "user"
	RateLimitBucketApiKey RateLimitBucket = "api_key"
	RateLimitBucketEmail RateLimitBucket = "email"
	RateLimitBucketUserMfaToken RateLimitBucket = "user_mfa_token"
	RateLimitBucketSocialAccount RateLimitBucket = "social_account"
	RateLimitBucketGroup RateLimitBucket = "group"
	RateLimitBucketPlatform RateLimitBucket = "platform"
)
