// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

// One account's share of the queue.
type RecipientLoad struct {
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	// Queued rows assigned to the account.
	Pending uint32 `json:"pending"`
	// Of those, the numbers it has no conversation with yet — each one is a
	// discovery (a number check and a new thread) before the send.
	NewConversations uint32 `json:"new_conversations"`
}
