// Code generated by tapir. DO NOT EDIT.

package domain

// What a conversation on a channel accepts after the contact's last inbound
// message. The send routes enforce it; `GET /channel` publishes it.
type ResponseWindow = interface{}
