// Code generated by tapir. DO NOT EDIT.

package domain

// How a query folds the days of a bucket: add them (counts that arrive per
// day) or keep the last (running totals such as followers).
type Roll string

const (
	RollSum Roll = "sum"
	RollLast Roll = "last"
)
