// Code generated by tapir. DO NOT EDIT.

package domain

// The entities a search can answer with — the closed set every fan-out
// matches exhaustively, so a new entity fails the build at each decision
// point until it is handled there.
type SearchKind string

const (
	SearchKindGroup SearchKind = "group"
	SearchKindUser SearchKind = "user"
	SearchKindConversation SearchKind = "conversation"
	SearchKindMessage SearchKind = "message"
)
