// Code generated by tapir. DO NOT EDIT.

package domain

// Channel-tagged send payload: each variant carries exactly the fields and
// content kinds its channel can deliver, so a send the channel cannot
// express does not even deserialize. The `channel` must match the
// conversation's account.
type SendContent = interface{}
