// Code generated by tapir. DO NOT EDIT.

package domain

// Which behaviour earned a temporary ban, as the platform reported it.
//
// The single most actionable thing whatsapp says about a ban — it names the
// pattern to change, so it is typed rather than left inside the free-text
// detail. Only ever set alongside [`SessionIncidentKind::TemporaryBan`].
type SessionBanReason string

const (
	SessionBanReasonSentToTooManyPeople SessionBanReason = "sent_to_too_many_people"
	SessionBanReasonBlockedByUsers SessionBanReason = "blocked_by_users"
	SessionBanReasonCreatedTooManyGroups SessionBanReason = "created_too_many_groups"
	SessionBanReasonSentTooManySameMessage SessionBanReason = "sent_too_many_same_message"
	SessionBanReasonBroadcastList SessionBanReason = "broadcast_list"
	SessionBanReasonUnknown SessionBanReason = "unknown"
)
