// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

// A post as it stands on its platform, published through the hub or not.
// `unanswered_count` is the number of visible third-party root comments with
// no public reply from the account; `last_comment_at` the newest comment.
type SocialPost struct {
	Uid primitives.Uid `json:"uid"`
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	// The platform's post / media id.
	ExternalId string `json:"external_id"`
	// The hub post it came from, when it was published through the hub.
	PostUid *primitives.Uid `json:"post_uid"`
	Caption *string `json:"caption"`
	// The hosted thumbnail (`media.serve`).
	PictureUid *primitives.Uid `json:"picture_uid"`
	PictureSource *string `json:"picture_source"`
	Permalink *string `json:"permalink"`
	PublishedAt *primitives.Timestamp `json:"published_at"`
	// The platform's own count or the comments the hub holds, whichever is
	// larger: the platform's count lags behind a comment the webhook delivered.
	CommentCount int64 `json:"comment_count"`
	LikeCount int64 `json:"like_count"`
	Detail SocialPostDetail `json:"detail"`
	// When the gateway last described the post. `None` marks a post the hub
	// knows only through its comments: the listings never reached it.
	SyncedAt *primitives.Timestamp `json:"synced_at"`
	// When the whole comment thread of such a post was read by post id.
	ThreadImportedAt *primitives.Timestamp `json:"thread_imported_at"`
	InsightRefreshedAt *primitives.Timestamp `json:"insight_refreshed_at"`
	InsightNextAt *primitives.Timestamp `json:"insight_next_at"`
	// When the gateway found the post gone from the platform; a deleted post
	// leaves the list and its metrics stop being read.
	DeletedAt *primitives.Timestamp `json:"deleted_at"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
	UnansweredCount int64 `json:"unanswered_count"`
	LastCommentAt *primitives.Timestamp `json:"last_comment_at"`
}
