// Code generated by tapir. DO NOT EDIT.

package domain

// Totals over the platform posts in scope, deleted ones excluded.
type SocialPostSummary struct {
	Posts int64 `json:"posts"`
	// Comments across them, each post counting the larger of the platform's
	// number and the hub's.
	Comments int64 `json:"comments"`
	// Root comments of third parties the account has not answered.
	Unanswered int64 `json:"unanswered"`
}
