// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

// Stevo gateway payload: the whatsapp shapes minus templates, and one
// contact card per send (the gateway takes one vcard per call).
type StevoSend struct {
	Content StevoContent `json:"content"`
	// Send as a reply to this message (must belong to the same conversation).
	ReplyToUid *primitives.Uid `json:"reply_to_uid"`
}
