// Code generated by tapir. DO NOT EDIT.

package domain

// How the template wheel picks the next template.
type TemplateRotation string

const (
	TemplateRotationLinear TemplateRotation = "linear"
	TemplateRotationRandom TemplateRotation = "random"
)
