// Code generated by tapir. DO NOT EDIT.

package domain

// One card of a generic template carousel.
type TemplateCard struct {
	Title string `json:"title"`
	Subtitle *string `json:"subtitle"`
	Image *MediaRef `json:"image"`
	Buttons []TemplateButton `json:"buttons"`
}
