// Code generated by tapir. DO NOT EDIT.

package domain

// A button on a structured message. `Url` opens the link; `Postback` sends
// the payload back as an [`InboundContent::Postback`] message.
type TemplateButton = interface{}
