// Code generated by tapir. DO NOT EDIT.

package domain

// How the hub reaches a channel's platform.
type Transport string

const (
	TransportMeta Transport = "meta"
	TransportGateway Transport = "gateway"
	TransportNative Transport = "native"
)
