// Code generated by tapir. DO NOT EDIT.

package domain

import (
	primitives "integro_sdk/types/primitives"
)

type User struct {
	Uid primitives.Uid `json:"uid"`
	Email primitives.Email `json:"email"`
	Name primitives.Name `json:"name"`
	Enabled bool `json:"enabled"`
	SuperAdmin bool `json:"super_admin"`
	LastSeen *primitives.Timestamp `json:"last_seen"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	UpdatedAt primitives.Timestamp `json:"updated_at"`
}
