// Code generated by tapir. DO NOT EDIT.

package group

import (
	primitives "integro_sdk/types/primitives"
)

type CreateGroupForm struct {
	Name primitives.Name `json:"name"`
	Logo *[]byte `json:"logo"`
}
