// Code generated by tapir. DO NOT EDIT.

package group

import (
	database "integro_sdk/types/database"
)

type GroupResponse struct {
	database.Group
	// Present only with `with_counts`, and only for a caller holding
	// `ViewApiKeys` in this group; `null` says the count is out of reach, never
	// that the group has no keys.
	ApiKeyCount *uint64 `json:"api_key_count"`
	// Present only with `with_counts`, and only for a caller holding
	// `ViewMembers` in this group; `null` says the count is out of reach, never
	// that the group has no members.
	MemberCount *uint64 `json:"member_count"`
}
