// Code generated by tapir. DO NOT EDIT.

package group

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

// One membership, carrying the identity fields needed to recognize the person
// behind it — never the user record itself, which answers to `ViewUsers` and
// is platform staff's alone.
type GroupMemberResponse struct {
	UserUid primitives.Uid `json:"user_uid"`
	Email primitives.Email `json:"email"`
	Name primitives.Name `json:"name"`
	Enabled bool `json:"enabled"`
	LastSeen *primitives.Timestamp `json:"last_seen"`
	Role domain.MembershipRole `json:"role"`
	MemberSince primitives.Timestamp `json:"member_since"`
}
