// Code generated by tapir. DO NOT EDIT.

package group

import (
	primitives "integro_sdk/types/primitives"
)

type SetGroupLogoResponse struct {
	// The stored logo, now `Group.logo_uid`.
	LogoUid primitives.Uid `json:"logo_uid"`
}
