// Code generated by tapi. DO NOT EDIT.

package mail_queue

import (
	__client "integro_sdk"
	__strings "strings"
	database "integro_sdk/types/database"
	mailing "integro_sdk/types/mailing"
)

// List List queued emails, optionally filtered by delivery status.
//
// Requires `ManageEmailQueue`, which only platform staff hold.
func List(__c *__client.Client, __query mailing.EmailQueueListQuery) ([]database.EmailQueueItem, error) {
	__path := "/mail-queue"
	return __client.Request[[]database.EmailQueueItem](__c, "GET", __path, __query, nil)
}
// Remove Remove a queued email from the delivery queue. An email that carried a
// subscriber and had not been sent flips that record's email status to
// failed. An email already handed to the mail server is refused — it settles
// on its own.
//
// Requires `ManageEmailQueue`, which only platform staff hold.
func Remove(__c *__client.Client, id string) (struct{}, error) {
	__path := "/mail-queue/{id}"
	__path = __strings.Replace(__path, "{id}", __client.EncodePath(id), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Retry Reset a failed queued email so the worker attempts delivery again. A
// subscriber record goes back to pending-send.
//
// Requires `ManageEmailQueue`, which only platform staff hold.
func Retry(__c *__client.Client, id string) (struct{}, error) {
	__path := "/mail-queue/{id}/retry"
	__path = __strings.Replace(__path, "{id}", __client.EncodePath(id), 1)
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
