// Code generated by tapir. DO NOT EDIT.

package campaign

// Where the audience comes from. Every source resolves to phone numbers,
// deduplicated across the participating accounts; a number is then
// assigned one account to send from — balanced across the accounts, with
// preference for an account that already has its conversation.
type AudienceSource = interface{}
