// Code generated by tapir. DO NOT EDIT.

package campaign

// An audience to resolve — what `build` freezes as the ledger and what
// `add` appends to it.
type AudienceRequest struct {
	AudienceSource
	// Shuffle the resolved order once — the default, because a strict file
	// order reads machine-like. An append shuffles only the appended batch.
	Shuffle *bool `json:"shuffle"`
}
