// Code generated by tapir. DO NOT EDIT.

package campaign

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

// A template as the API shows it: the stored JSON decoded into its parts.
type CampaignTemplateResponse struct {
	Uid primitives.Uid `json:"uid"`
	CampaignUid primitives.Uid `json:"campaign_uid"`
	// The linear rotation order.
	Position uint32 `json:"position"`
	Label *primitives.Name `json:"label"`
	Parts []domain.OutboundContent `json:"parts"`
	CreatedAt primitives.Timestamp `json:"created_at"`
}
