// Code generated by tapir. DO NOT EDIT.

package campaign

type CampaignStats struct {
	Rows []CampaignStatRow `json:"rows"`
	// Conversations that answered after their campaign send.
	Replies uint32 `json:"replies"`
}
