// Code generated by tapir. DO NOT EDIT.

package campaign

// Recipient counts by status — always derived from the ledger.
type CampaignCounts struct {
	Total uint32 `json:"total"`
	Pending uint32 `json:"pending"`
	Sent uint32 `json:"sent"`
	Failed uint32 `json:"failed"`
	Skipped uint32 `json:"skipped"`
	Canceled uint32 `json:"canceled"`
}
