// Code generated by tapir. DO NOT EDIT.

package campaign

import (
	domain "integro_sdk/types/domain"
)

// One recipient-status × message-status cell of the stats join.
type CampaignStatRow struct {
	RecipientStatus domain.CampaignRecipientStatus `json:"recipient_status"`
	// The pointed message's own status; `null` for never-dispatched rows.
	MessageStatus *domain.MessageStatus `json:"message_status"`
	Count uint32 `json:"count"`
}
