// Code generated by tapir. DO NOT EDIT.

package campaign

import (
	primitives "integro_sdk/types/primitives"
)

// A new draft: identity only. The schedule starts from workable defaults
// (30–90s, 09:00–18:00 seg–sáb, BRT) and is edited in place.
type CreateCampaignRequest struct {
	// Required for users and platform keys; group-bound keys imply their group.
	GroupUid *primitives.Uid `json:"group_uid"`
	Name primitives.Name `json:"name"`
}
