// Code generated by tapir. DO NOT EDIT.

package campaign

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type ListRecipientsQuery struct {
	Status *domain.CampaignRecipientStatus `json:"status"`
	// Keyset cursor: only rows with `id` strictly greater are returned.
	AfterId *uint64 `json:"after_id"`
	Limit *primitives.Number1_500 `json:"limit"`
}
