// Code generated by tapir. DO NOT EDIT.

package campaign

import (
	primitives "integro_sdk/types/primitives"
)

type ListCampaignsQuery struct {
	GroupUid *primitives.Uid `json:"group_uid"`
	Limit *primitives.Number1_200 `json:"limit"`
}
