// Code generated by tapir. DO NOT EDIT.

package campaign

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type ListRecipientsQuery struct {
	Status *types.CampaignRecipientStatus `json:"status"`
	// Keyset cursor: only rows with `id` strictly greater are returned.
	AfterId *uint64 `json:"after_id"`
	Limit *primitives.Number1_500 `json:"limit"`
}
