// Code generated by tapir. DO NOT EDIT.

package campaign

// Queued recipients to drop. Rows that already ran (sent, failed, skipped,
// canceled) are history and stay.
type RemoveRecipientsRequest struct {
	RecipientIds []uint64 `json:"recipient_ids"`
}
