// Code generated by tapir. DO NOT EDIT.

package campaign

import (
	primitives "integro_sdk/types/primitives"
)

type TestSendRequest struct {
	TemplateUid primitives.Uid `json:"template_uid"`
	// A conversation of the campaign's group, on a whatsapp account, to
	// receive the rendered template, now, outside any schedule.
	ConversationUid primitives.Uid `json:"conversation_uid"`
}
