// Code generated by tapi. DO NOT EDIT.

package ghl

import (
	__client "integro_sdk"
	__strings "strings"
	database "integro_sdk/types/database"
	ghl "integro_sdk/types/ghl"
)

// Callback GoHighLevel OAuth redirect target: consumes the state, exchanges the code
// and registers (or reconnects) the location; always redirects the browser
// back to the frontend, carrying an error slug when the install failed.
//
// Public — no authentication required; authorization comes from the one-shot state token issued by `ghl.connect`.
func Callback(__c *__client.Client, __query ghl.GhlCallbackQuery) (struct{}, error) {
	__path := "/ghl/callback"
	return __client.Request[struct{}](__c, "GET", __path, __query, nil)
}
// Connect Start the GoHighLevel OAuth flow for a group, returning the location-choice
// dialog URL; the location the admin picks there is connected to the group by
// the callback.
//
// Requires `ConnectSocialAccounts` in the named group.
func Connect(__c *__client.Client, __body ghl.ConnectGhlRequest) (ghl.ConnectGhlResponse, error) {
	__path := "/ghl/connect"
	return __client.Request[ghl.ConnectGhlResponse](__c, "POST", __path, nil, __body)
}
// Disconnect Disconnect the location, deleting its stored grant and its binding.
// Reinstalling the app from GoHighLevel is what brings it back.
//
// Requires `ConnectSocialAccounts` in the location's group.
func Disconnect(__c *__client.Client, ghlLocationUid string) (struct{}, error) {
	__path := "/ghl/{ghl_location_uid}"
	__path = __strings.Replace(__path, "{ghl_location_uid}", __client.EncodePath(ghlLocationUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Link Bridge a whatsapp account into the location's conversations inbox: what the
// location sends over the provider goes out on that account, and what the
// account receives is mirrored back. The body is channel-tagged — only the
// whatsapp flavors that can open a conversation from a phone number
// deserialize. Only history from this moment on is carried over — the sync
// starts at the current message head.
//
// Requires `ConnectSocialAccounts` in the location's group — the group the target account must belong to as well.
func Link(__c *__client.Client, ghlLocationUid string, __body ghl.LinkGhlRequest) (database.GhlLocation, error) {
	__path := "/ghl/{ghl_location_uid}/link"
	__path = __strings.Replace(__path, "{ghl_location_uid}", __client.EncodePath(ghlLocationUid), 1)
	return __client.Request[database.GhlLocation](__c, "PUT", __path, nil, __body)
}
// List List the GoHighLevel locations installed in a group, each carrying the
// whatsapp account it bridges (`target_account_uid`, null while unlinked) and
// whether its grant needs reconnecting.
//
// Requires `ViewSocialAccounts` in the named group.
func List(__c *__client.Client, __query ghl.ListGhlQuery) ([]database.GhlLocation, error) {
	__path := "/ghl"
	return __client.Request[[]database.GhlLocation](__c, "GET", __path, __query, nil)
}
// Unlink Unbridge the location's whatsapp account, stopping the mirroring in both
// directions. The location stays installed and can be pointed at another
// account.
//
// Requires `ConnectSocialAccounts` in the location's group.
func Unlink(__c *__client.Client, ghlLocationUid string) (database.GhlLocation, error) {
	__path := "/ghl/{ghl_location_uid}/link"
	__path = __strings.Replace(__path, "{ghl_location_uid}", __client.EncodePath(ghlLocationUid), 1)
	return __client.Request[database.GhlLocation](__c, "DELETE", __path, nil, nil)
}
