// Code generated by tapir. DO NOT EDIT.

package google

type AggregateCallMetrics struct {
	MissedCallsCount uint32 `json:"missedCallsCount"`
	AnsweredCallsCount uint32 `json:"answeredCallsCount"`
	HourlyMetrics []HourlyCallMetrics `json:"hourlyMetrics,omitempty"`
	WeekdayMetrics []WeekdayCallMetrics `json:"weekdayMetrics,omitempty"`
	StartDate *Date `json:"startDate"`
	EndDate *Date `json:"endDate"`
}
