// Code generated by tapir. DO NOT EDIT.

package google

type Answer struct {
	// Resource name, `locations/{l}/questions/{q}/answers/{a}`.
	Name *string `json:"name"`
	Text *string `json:"text"`
	Author *QandaAuthor `json:"author"`
	UpvoteCount *uint32 `json:"upvoteCount,omitempty"`
	CreateTime *string `json:"createTime"`
	UpdateTime *string `json:"updateTime"`
}
