// Code generated by tapir. DO NOT EDIT.

package google

type CalendarListEntry struct {
	Id string `json:"id"`
	Summary *string `json:"summary"`
	Primary *bool `json:"primary"`
	AccessRole *string `json:"accessRole"`
	TimeZone *string `json:"timeZone"`
}
