// Code generated by tapir. DO NOT EDIT.

package google

// Post button: `action_type` is `BOOK`, `ORDER`, `SHOP`, `LEARN_MORE`,
// `SIGN_UP` or `CALL` (the latter needs no url).
type CallToAction struct {
	ActionType *string `json:"actionType"`
	Url *string `json:"url"`
}
