// Code generated by tapir. DO NOT EDIT.

package google

// Mutable event payload for insert/patch. Only set fields are sent — which
// also means a PATCH can never *clear* a field.
type EventInput struct {
	Summary *string `json:"summary"`
	Description *string `json:"description"`
	Location *string `json:"location"`
	Start *EventDateTime `json:"start"`
	End *EventDateTime `json:"end"`
	Attendees *[]EventAttendee `json:"attendees"`
	ExtendedProperties *ExtendedProperties `json:"extendedProperties"`
}
