// Code generated by tapir. DO NOT EDIT.

package google

// App-private key/value labels carried on an event. `private` is visible only
// to the connected account's grant, so it is where a caller stamps its own
// identifier for whoever booked the event — that label can then be filtered
// server-side, making Google the source of truth instead of a local mirror.
type ExtendedProperties struct {
	Private map[string]string `json:"private,omitempty"`
	Shared map[string]string `json:"shared,omitempty"`
}
