// Code generated by tapir. DO NOT EDIT.

package google

// A search term that surfaced the profile. Low-volume terms report only a
// `threshold` floor instead of an exact `value` (both stringified int64).
type InsightsValue struct {
	Value *string `json:"value"`
	Threshold *string `json:"threshold"`
}
