// Code generated by tapir. DO NOT EDIT.

package google

// A business location, thinned to the fields the read mask requests.
type Location struct {
	// Resource name, `locations/{location_id}` — no account prefix on v1.
	Name *string `json:"name"`
	Title *string `json:"title"`
	PhoneNumbers *PhoneNumbers `json:"phoneNumbers"`
	StorefrontAddress *PostalAddress `json:"storefrontAddress"`
	WebsiteUri *string `json:"websiteUri"`
	RegularHours *BusinessHours `json:"regularHours"`
	SpecialHours *SpecialHours `json:"specialHours"`
	Categories *Categories `json:"categories"`
	OpenInfo *OpenInfo `json:"openInfo"`
	Profile *BusinessProfile `json:"profile"`
	Latlng *LatLng `json:"latlng"`
	Metadata *LocationMetadata `json:"metadata"`
}
