// Code generated by tapir. DO NOT EDIT.

package google

// Offer extras layered on an `OFFER` post's event window.
type LocalPostOffer struct {
	CouponCode *string `json:"couponCode"`
	RedeemOnlineUrl *string `json:"redeemOnlineUrl"`
	TermsConditions *string `json:"termsConditions"`
}
