// Code generated by tapir. DO NOT EDIT.

package google

// A local post ("What's new" card on the profile). `topic_type` is
// `STANDARD`, `EVENT`, `OFFER` or `ALERT`; `state` and `search_url` are
// server-set.
type LocalPost struct {
	// Resource name, `accounts/{a}/locations/{l}/localPosts/{p}`.
	Name *string `json:"name"`
	LanguageCode *string `json:"languageCode"`
	Summary *string `json:"summary"`
	TopicType *string `json:"topicType"`
	CallToAction *CallToAction `json:"callToAction"`
	Event *LocalPostEvent `json:"event"`
	Offer *LocalPostOffer `json:"offer"`
	Media []PostMedia `json:"media,omitempty"`
	State *string `json:"state"`
	SearchUrl *string `json:"searchUrl"`
	CreateTime *string `json:"createTime"`
	UpdateTime *string `json:"updateTime"`
}
