// Code generated by tapir. DO NOT EDIT.

package google

// Price (proto `google.type.Money`): `units` is a stringified int64.
type Money struct {
	CurrencyCode *string `json:"currencyCode"`
	Units *string `json:"units"`
	Nanos int32 `json:"nanos"`
}
