// Code generated by tapir. DO NOT EDIT.

package google

// Media attached to a post — on create, `media_format: PHOTO` plus a public
// `source_url`; responses add the Google-hosted copy.
type PostMedia struct {
	Name *string `json:"name"`
	MediaFormat *string `json:"mediaFormat"`
	SourceUrl *string `json:"sourceUrl"`
	GoogleUrl *string `json:"googleUrl"`
}
