// Code generated by tapir. DO NOT EDIT.

package google

// Storefront address, thinned from `google.type.PostalAddress`.
type PostalAddress struct {
	RegionCode *string `json:"regionCode"`
	PostalCode *string `json:"postalCode"`
	AdministrativeArea *string `json:"administrativeArea"`
	Locality *string `json:"locality"`
	AddressLines []string `json:"addressLines,omitempty"`
}
