// Code generated by tapir. DO NOT EDIT.

package google

// Storefront address (`google.type.PostalAddress`). Every data-carrying field
// is modelled: a PATCH masking `storefrontAddress` replaces the message
// wholesale, so anything missing here would be cleared on the profile. Only
// `revision` is omitted — Google pins it to 0.
type PostalAddress struct {
	RegionCode *string `json:"regionCode"`
	LanguageCode *string `json:"languageCode"`
	PostalCode *string `json:"postalCode"`
	SortingCode *string `json:"sortingCode"`
	AdministrativeArea *string `json:"administrativeArea"`
	Locality *string `json:"locality"`
	Sublocality *string `json:"sublocality"`
	AddressLines []string `json:"addressLines,omitempty"`
	Recipients []string `json:"recipients,omitempty"`
	Organization *string `json:"organization"`
}
