// Code generated by tapir. DO NOT EDIT.

package google

type QuestionPage struct {
	Questions []Question `json:"questions"`
	TotalSize *uint32 `json:"totalSize,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}
