// Code generated by tapir. DO NOT EDIT.

package google

type Reviewer struct {
	DisplayName *string `json:"displayName"`
	ProfilePhotoUrl *string `json:"profilePhotoUrl"`
	IsAnonymous *bool `json:"isAnonymous"`
}
