// Code generated by tapir. DO NOT EDIT.

package google

// A customer review. `star_rating` is `ONE`…`FIVE`; `comment` may carry a
// `(Translated by Google)` block alongside the original text.
type Review struct {
	// Resource name, `accounts/{a}/locations/{l}/reviews/{r}`.
	Name *string `json:"name"`
	ReviewId *string `json:"reviewId"`
	Reviewer *Reviewer `json:"reviewer"`
	StarRating *string `json:"starRating"`
	Comment *string `json:"comment"`
	CreateTime *string `json:"createTime"`
	UpdateTime *string `json:"updateTime"`
	ReviewReply *ReviewReply `json:"reviewReply"`
}
