// Code generated by tapir. DO NOT EDIT.

package google

type TimeInterval struct {
	StartDate *Date `json:"startDate"`
	StartTime *TimeOfDay `json:"startTime"`
	EndDate *Date `json:"endDate"`
	EndTime *TimeOfDay `json:"endTime"`
}
