// Code generated by tapi. DO NOT EDIT.

package meta

import (
	__client "integro_sdk"
	transport "integro_sdk/types/transport"
)

// Receive Meta webhook receiver: verifies the payload signature and hands every
// messaging event and page change to the feature that owns it, which
// stores it (deduplicating redeliveries) and enqueues CRM fan-out events.
//
// Public — no authentication required; authorization comes from the `X-Hub-Signature-256` HMAC over the raw body.
func Receive(__c *__client.Client) (struct{}, error) {
	__path := "/webhook/meta"
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
// Verify Meta webhook verification handshake: echoes `hub.challenge` when
// `hub.verify_token` matches the configured token.
//
// Public — no authentication required; authorization comes from the configured webhook verify token.
func Verify(__c *__client.Client, __query transport.WebhookVerifyQuery) (string, error) {
	__path := "/webhook/meta"
	return __client.Request[string](__c, "GET", __path, __query, nil)
}
