// Code generated by tapi. DO NOT EDIT.

package search

import (
	"integro_sdk"
	database "integro_sdk/types/database"
	search "integro_sdk/types/search"
)

// Global Search groups and users in one ranked result set.
//
// Any authenticated user; the results cover the caller's own groups and the people sharing them, and every group and user for platform staff.
func Global(c *client.Client, query search.SearchQuery) ([]database.SearchHit, error) {
	__path := "/search"
	return client.Request[[]database.SearchHit](c, "GET", __path, query, nil)
}
