// Code generated by tapi. DO NOT EDIT.

package search

import (
	__client "integro_sdk"
	database "integro_sdk/types/database"
	search "integro_sdk/types/search"
)

// Global Search groups and users in one ranked result set.
//
// Any authenticated user; the results cover the caller's own groups and the people sharing them, and every group and user for platform staff.
func Global(__c *__client.Client, __query search.SearchQuery) ([]database.SearchHit, error) {
	__path := "/search"
	return __client.Request[[]database.SearchHit](__c, "GET", __path, __query, nil)
}
