// Code generated by tapir. DO NOT EDIT.

package user_mfa

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type UserMfaVerifyRequest struct {
	MfaToken primitives.Uid `json:"mfa_token"`
	Factor types.UserMfaKind `json:"factor"`
	Code primitives.Pin6 `json:"code"`
}
