// Code generated by tapir. DO NOT EDIT.

package user_mfa

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type UserMfaFactorRow struct {
	Kind domain.UserMfaKind `json:"kind"`
	ConfirmedAt *primitives.Timestamp `json:"confirmed_at"`
	LastUsedAt *primitives.Timestamp `json:"last_used_at"`
}
