// Code generated by tapir. DO NOT EDIT.

package user_mfa

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type UserMfaFactorRow struct {
	Kind types.UserMfaKind `json:"kind"`
	ConfirmedAt *primitives.Timestamp `json:"confirmed_at"`
	LastUsedAt *primitives.Timestamp `json:"last_used_at"`
}
