// Code generated by tapir. DO NOT EDIT.

package user_mfa

import (
	primitives "integro_sdk/types/primitives"
)

type UserMfaMgmtEmailStartResponse struct {
	EnrollmentToken primitives.Uid `json:"enrollment_token"`
	ExpiryMinutes int64 `json:"expiry_minutes"`
}
