// Code generated by tapir. DO NOT EDIT.

package user_mfa

import (
	primitives "integro_sdk/types/primitives"
)

type UserMfaEnrollConfirmRequest struct {
	EnrollmentToken primitives.Uid `json:"enrollment_token"`
	Code primitives.Pin6 `json:"code"`
}
