// Code generated by tapir. DO NOT EDIT.

package user_mfa

type UserMfaEnrollTotpStartResponse struct {
	SecretBase32 string `json:"secret_base32"`
	OtpauthUri string `json:"otpauth_uri"`
	QrSvg string `json:"qr_svg"`
}
