// Code generated by tapir. DO NOT EDIT.

package user_mfa

import (
	primitives "integro_sdk/types/primitives"
)

type UserMfaEnrollTotpStartRequest struct {
	EnrollmentToken primitives.Uid `json:"enrollment_token"`
}
