// Code generated by tapir. DO NOT EDIT.

package user_mfa

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type UserMfaDispatchRequest struct {
	MfaToken primitives.Uid `json:"mfa_token"`
	Factor domain.UserMfaKind `json:"factor"`
}
