// Code generated by tapir. DO NOT EDIT.

package audit_log

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type AuditLogQuery struct {
	domain.AuditLogWindow
	// Narrow to these groups, each one the caller may see; omit for everything the caller may see.
	GroupUids *[]primitives.Uid `json:"group_uids"`
	UserUid *primitives.Uid `json:"user_uid"`
	Action *domain.AuditAction `json:"action"`
	Resource *domain.AuditResource `json:"resource"`
	ResourceUid *string `json:"resource_uid"`
}
