// Code generated by tapir. DO NOT EDIT.

package audit_log

import (
	database "integro_sdk/types/database"
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type AuditLogQuery struct {
	database.AuditLogWindow
	GroupUid *primitives.Uid `json:"group_uid"`
	UserUid *primitives.Uid `json:"user_uid"`
	Action *types.AuditAction `json:"action"`
	Resource *types.AuditResource `json:"resource"`
	ResourceUid *string `json:"resource_uid"`
}
