// Code generated by tapi. DO NOT EDIT.

package gateway

import (
	__client "integro_sdk"
)

// Receive Alternate-gateway webhook receiver for the alt channels: verifies the
// payload signature and hands every message, receipt, reaction, edit,
// revoke, comment, post outcome and account event to the feature that owns
// it, which stores it (deduplicating redeliveries) and enqueues CRM fan-out
// events.
//
// Public — no authentication required; authorization comes from the gateway's signature header, an HMAC over the raw body.
func Receive(__c *__client.Client) (struct{}, error) {
	__path := "/webhook/gateway"
	return __client.Request[struct{}](__c, "POST", __path, nil, nil)
}
