// Code generated by tapir. DO NOT EDIT.

package media

import (
	primitives "integro_sdk/types/primitives"
)

type CreateUploadUrlResponse struct {
	UploadUrl string `json:"upload_url"`
	ExpiresAt primitives.Timestamp `json:"expires_at"`
	MaxBytes uint64 `json:"max_bytes"`
}
