// Code generated by tapir. DO NOT EDIT.

package media

import (
	primitives "integro_sdk/types/primitives"
)

type CreateUploadUrlRequest struct {
	// Required for users and platform keys; group-bound keys imply their group.
	GroupUid *primitives.Uid `json:"group_uid"`
	Filename *string `json:"filename"`
	ContentType *string `json:"content_type"`
}
