// Code generated by tapir. DO NOT EDIT.

package media

// A signed grant on the media URL: the hub mints one for a platform that has
// to fetch a file it is about to deliver. Absent on an ordinary fetch.
type MediaGrantQuery struct {
	Exp *int64 `json:"exp"`
	Sig *string `json:"sig"`
}
