// Code generated by tapir. DO NOT EDIT.

package media

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type UploadMediaResponse struct {
	Uid primitives.Uid `json:"uid"`
	// Public URL Meta (and CRMs) can fetch — usable anywhere the send/publish
	// APIs take a media URL.
	Url string `json:"url"`
	Kind domain.MediaKind `json:"kind"`
	ContentType string `json:"content_type"`
	Size uint64 `json:"size"`
}
