// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Email struct{ v string }

var emailSpec = validate.ValidationSpec{Preprocess: validate.PreprocessTrimLowercase, Constraints: []validate.Constraint{{Kind: "minLen", Int: 5}, {Kind: "maxLen", Int: 254}, {Kind: "regex", Source: "^[a-zA-Z0-9_%+-]+(\\.[a-zA-Z0-9_%+-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*\\.[a-zA-Z]{2,}$", Hint: ""}}}

// ParseEmail is the only producer: validates input, returns the value or the first violation.
func ParseEmail(value string) (Email, *validate.Violation) {
	if viol := validate.Check(emailSpec, value); viol != nil {
		return Email{}, viol
	}
	return Email{v: value}, nil
}

// ParseAllEmail returns every unmet rule, for a live checklist / strength meter.
func ParseAllEmail(value string) []validate.Violation { return validate.CheckAll(emailSpec, value) }

func (x Email) Value() string { return x.v }
func EmailSpec() validate.ValidationSpec { return emailSpec }
func (x Email) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Email) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
