// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Name struct{ v string }

var nameSpec = validate.ValidationSpec{Preprocess: validate.PreprocessTrim, Constraints: []validate.Constraint{{Kind: "minLen", Int: 3}, {Kind: "maxLen", Int: 100}, {Kind: "noControlChars"}}}

// ParseName is the only producer: validates input, returns the value or the first violation.
func ParseName(value string) (Name, *validate.Violation) {
	if viol := validate.Check(nameSpec, value); viol != nil {
		return Name{}, viol
	}
	return Name{v: value}, nil
}

// ParseAllName returns every unmet rule, for a live checklist / strength meter.
func ParseAllName(value string) []validate.Violation { return validate.CheckAll(nameSpec, value) }

func (x Name) Value() string { return x.v }
func NameSpec() validate.ValidationSpec { return nameSpec }
func (x Name) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Name) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
