// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Number0_1439 struct{ v int64 }

var number0_1439Spec = validate.ValidationSpec{Preprocess: validate.PreprocessNone, Constraints: []validate.Constraint{{Kind: "min", Bound: 0}, {Kind: "max", Bound: 1439}}}

// ParseNumber0_1439 is the only producer: validates input, returns the value or the first violation.
func ParseNumber0_1439(value int64) (Number0_1439, *validate.Violation) {
	if viol := validate.Check(number0_1439Spec, value); viol != nil {
		return Number0_1439{}, viol
	}
	return Number0_1439{v: value}, nil
}

// ParseAllNumber0_1439 returns every unmet rule, for a live checklist / strength meter.
func ParseAllNumber0_1439(value int64) []validate.Violation { return validate.CheckAll(number0_1439Spec, value) }

func (x Number0_1439) Value() int64 { return x.v }
func Number0_1439Spec() validate.ValidationSpec { return number0_1439Spec }
func (x Number0_1439) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Number0_1439) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
