// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Number1_365 struct{ v int64 }

var number1_365Spec = validate.ValidationSpec{Preprocess: validate.PreprocessNone, Constraints: []validate.Constraint{{Kind: "min", Bound: 1}, {Kind: "max", Bound: 365}}}

// ParseNumber1_365 is the only producer: validates input, returns the value or the first violation.
func ParseNumber1_365(value int64) (Number1_365, *validate.Violation) {
	if viol := validate.Check(number1_365Spec, value); viol != nil {
		return Number1_365{}, viol
	}
	return Number1_365{v: value}, nil
}

// ParseAllNumber1_365 returns every unmet rule, for a live checklist / strength meter.
func ParseAllNumber1_365(value int64) []validate.Violation { return validate.CheckAll(number1_365Spec, value) }

func (x Number1_365) Value() int64 { return x.v }
func Number1_365Spec() validate.ValidationSpec { return number1_365Spec }
func (x Number1_365) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Number1_365) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
