// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Number1000_86400000 struct{ v int64 }

var number1000_86400000Spec = validate.ValidationSpec{Preprocess: validate.PreprocessNone, Constraints: []validate.Constraint{{Kind: "min", Bound: 1000}, {Kind: "max", Bound: 86400000}}}

// ParseNumber1000_86400000 is the only producer: validates input, returns the value or the first violation.
func ParseNumber1000_86400000(value int64) (Number1000_86400000, *validate.Violation) {
	if viol := validate.Check(number1000_86400000Spec, value); viol != nil {
		return Number1000_86400000{}, viol
	}
	return Number1000_86400000{v: value}, nil
}

// ParseAllNumber1000_86400000 returns every unmet rule, for a live checklist / strength meter.
func ParseAllNumber1000_86400000(value int64) []validate.Violation { return validate.CheckAll(number1000_86400000Spec, value) }

func (x Number1000_86400000) Value() int64 { return x.v }
func Number1000_86400000Spec() validate.ValidationSpec { return number1000_86400000Spec }
func (x Number1000_86400000) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Number1000_86400000) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
