// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Number1_2500 struct{ v int64 }

var number1_2500Spec = validate.ValidationSpec{Preprocess: validate.PreprocessNone, Constraints: []validate.Constraint{{Kind: "min", Bound: 1}, {Kind: "max", Bound: 2500}}}

// ParseNumber1_2500 is the only producer: validates input, returns the value or the first violation.
func ParseNumber1_2500(value int64) (Number1_2500, *validate.Violation) {
	if viol := validate.Check(number1_2500Spec, value); viol != nil {
		return Number1_2500{}, viol
	}
	return Number1_2500{v: value}, nil
}

// ParseAllNumber1_2500 returns every unmet rule, for a live checklist / strength meter.
func ParseAllNumber1_2500(value int64) []validate.Violation { return validate.CheckAll(number1_2500Spec, value) }

func (x Number1_2500) Value() int64 { return x.v }
func Number1_2500Spec() validate.ValidationSpec { return number1_2500Spec }
func (x Number1_2500) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Number1_2500) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
