// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Number0_4999 struct{ v int64 }

var number0_4999Spec = validate.ValidationSpec{Preprocess: validate.PreprocessNone, Constraints: []validate.Constraint{{Kind: "min", Bound: 0}, {Kind: "max", Bound: 4999}}}

// ParseNumber0_4999 is the only producer: validates input, returns the value or the first violation.
func ParseNumber0_4999(value int64) (Number0_4999, *validate.Violation) {
	if viol := validate.Check(number0_4999Spec, value); viol != nil {
		return Number0_4999{}, viol
	}
	return Number0_4999{v: value}, nil
}

// ParseAllNumber0_4999 returns every unmet rule, for a live checklist / strength meter.
func ParseAllNumber0_4999(value int64) []validate.Violation { return validate.CheckAll(number0_4999Spec, value) }

func (x Number0_4999) Value() int64 { return x.v }
func Number0_4999Spec() validate.ValidationSpec { return number0_4999Spec }
func (x Number0_4999) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Number0_4999) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
