// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Number1024_107374182400 struct{ v int64 }

var number1024_107374182400Spec = validate.ValidationSpec{Preprocess: validate.PreprocessNone, Constraints: []validate.Constraint{{Kind: "min", Bound: 1024}, {Kind: "max", Bound: 107374182400}}}

// ParseNumber1024_107374182400 is the only producer: validates input, returns the value or the first violation.
func ParseNumber1024_107374182400(value int64) (Number1024_107374182400, *validate.Violation) {
	if viol := validate.Check(number1024_107374182400Spec, value); viol != nil {
		return Number1024_107374182400{}, viol
	}
	return Number1024_107374182400{v: value}, nil
}

// ParseAllNumber1024_107374182400 returns every unmet rule, for a live checklist / strength meter.
func ParseAllNumber1024_107374182400(value int64) []validate.Violation { return validate.CheckAll(number1024_107374182400Spec, value) }

func (x Number1024_107374182400) Value() int64 { return x.v }
func Number1024_107374182400Spec() validate.ValidationSpec { return number1024_107374182400Spec }
func (x Number1024_107374182400) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Number1024_107374182400) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
