// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Number1_50 struct{ v int64 }

var number1_50Spec = validate.ValidationSpec{Preprocess: validate.PreprocessNone, Constraints: []validate.Constraint{{Kind: "min", Bound: 1}, {Kind: "max", Bound: 50}}}

// ParseNumber1_50 is the only producer: validates input, returns the value or the first violation.
func ParseNumber1_50(value int64) (Number1_50, *validate.Violation) {
	if viol := validate.Check(number1_50Spec, value); viol != nil {
		return Number1_50{}, viol
	}
	return Number1_50{v: value}, nil
}

// ParseAllNumber1_50 returns every unmet rule, for a live checklist / strength meter.
func ParseAllNumber1_50(value int64) []validate.Violation { return validate.CheckAll(number1_50Spec, value) }

func (x Number1_50) Value() int64 { return x.v }
func Number1_50Spec() validate.ValidationSpec { return number1_50Spec }
func (x Number1_50) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Number1_50) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
