// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Password8_128_F_F_T_F struct{ v string }

var password8_128_F_F_T_FSpec = validate.ValidationSpec{Preprocess: validate.PreprocessNone, Constraints: []validate.Constraint{{Kind: "minLen", Int: 8}, {Kind: "maxLen", Int: 128}, {Kind: "requireDigit"}}}

// ParsePassword8_128_F_F_T_F is the only producer: validates input, returns the value or the first violation.
func ParsePassword8_128_F_F_T_F(value string) (Password8_128_F_F_T_F, *validate.Violation) {
	if viol := validate.Check(password8_128_F_F_T_FSpec, value); viol != nil {
		return Password8_128_F_F_T_F{}, viol
	}
	return Password8_128_F_F_T_F{v: value}, nil
}

// ParseAllPassword8_128_F_F_T_F returns every unmet rule, for a live checklist / strength meter.
func ParseAllPassword8_128_F_F_T_F(value string) []validate.Violation { return validate.CheckAll(password8_128_F_F_T_FSpec, value) }

func (x Password8_128_F_F_T_F) Value() string { return x.v }
func Password8_128_F_F_T_FSpec() validate.ValidationSpec { return password8_128_F_F_T_FSpec }
func (x Password8_128_F_F_T_F) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Password8_128_F_F_T_F) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
