// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Phone struct{ v string }

var phoneSpec = validate.ValidationSpec{Preprocess: validate.PreprocessTrim, Constraints: []validate.Constraint{{Kind: "minDigits", Int: 7}, {Kind: "maxDigits", Int: 15}, {Kind: "regex", Source: "^\\+[1-9]\\d{6,14}$", Hint: "esperado E.164: +<código do país><número>"}}}

// ParsePhone is the only producer: validates input, returns the value or the first violation.
func ParsePhone(value string) (Phone, *validate.Violation) {
	if viol := validate.Check(phoneSpec, value); viol != nil {
		return Phone{}, viol
	}
	return Phone{v: value}, nil
}

// ParseAllPhone returns every unmet rule, for a live checklist / strength meter.
func ParseAllPhone(value string) []validate.Violation { return validate.CheckAll(phoneSpec, value) }

func (x Phone) Value() string { return x.v }
func PhoneSpec() validate.ValidationSpec { return phoneSpec }
func (x Phone) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Phone) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
