// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Pin6 struct{ v string }

var pin6Spec = validate.ValidationSpec{Preprocess: validate.PreprocessTrim, Constraints: []validate.Constraint{{Kind: "exactLen", Int: 6}, {Kind: "asciiDigitsOnly"}}}

// ParsePin6 is the only producer: validates input, returns the value or the first violation.
func ParsePin6(value string) (Pin6, *validate.Violation) {
	if viol := validate.Check(pin6Spec, value); viol != nil {
		return Pin6{}, viol
	}
	return Pin6{v: value}, nil
}

// ParseAllPin6 returns every unmet rule, for a live checklist / strength meter.
func ParseAllPin6(value string) []validate.Violation { return validate.CheckAll(pin6Spec, value) }

func (x Pin6) Value() string { return x.v }
func Pin6Spec() validate.ValidationSpec { return pin6Spec }
func (x Pin6) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Pin6) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
