// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Text0_50 struct{ v string }

var text0_50Spec = validate.ValidationSpec{Preprocess: validate.PreprocessTrim, Constraints: []validate.Constraint{{Kind: "minLen", Int: 0}, {Kind: "maxLen", Int: 50}}}

// ParseText0_50 is the only producer: validates input, returns the value or the first violation.
func ParseText0_50(value string) (Text0_50, *validate.Violation) {
	if viol := validate.Check(text0_50Spec, value); viol != nil {
		return Text0_50{}, viol
	}
	return Text0_50{v: value}, nil
}

// ParseAllText0_50 returns every unmet rule, for a live checklist / strength meter.
func ParseAllText0_50(value string) []validate.Violation { return validate.CheckAll(text0_50Spec, value) }

func (x Text0_50) Value() string { return x.v }
func Text0_50Spec() validate.ValidationSpec { return text0_50Spec }
func (x Text0_50) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Text0_50) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
