// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Text0_255 struct{ v string }

var text0_255Spec = validate.ValidationSpec{Preprocess: validate.PreprocessTrim, Constraints: []validate.Constraint{{Kind: "minLen", Int: 0}, {Kind: "maxLen", Int: 255}}}

// ParseText0_255 is the only producer: validates input, returns the value or the first violation.
func ParseText0_255(value string) (Text0_255, *validate.Violation) {
	if viol := validate.Check(text0_255Spec, value); viol != nil {
		return Text0_255{}, viol
	}
	return Text0_255{v: value}, nil
}

// ParseAllText0_255 returns every unmet rule, for a live checklist / strength meter.
func ParseAllText0_255(value string) []validate.Violation { return validate.CheckAll(text0_255Spec, value) }

func (x Text0_255) Value() string { return x.v }
func Text0_255Spec() validate.ValidationSpec { return text0_255Spec }
func (x Text0_255) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Text0_255) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
