// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Text255 struct{ v string }

var text255Spec = validate.ValidationSpec{Preprocess: validate.PreprocessTrim, Constraints: []validate.Constraint{{Kind: "maxLen", Int: 255}}}

// ParseText255 is the only producer: validates input, returns the value or the first violation.
func ParseText255(value string) (Text255, *validate.Violation) {
	if viol := validate.Check(text255Spec, value); viol != nil {
		return Text255{}, viol
	}
	return Text255{v: value}, nil
}

// ParseAllText255 returns every unmet rule, for a live checklist / strength meter.
func ParseAllText255(value string) []validate.Violation { return validate.CheckAll(text255Spec, value) }

func (x Text255) Value() string { return x.v }
func Text255Spec() validate.ValidationSpec { return text255Spec }
func (x Text255) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Text255) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
