// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Text8000 struct{ v string }

var text8000Spec = validate.ValidationSpec{Preprocess: validate.PreprocessTrim, Constraints: []validate.Constraint{{Kind: "maxLen", Int: 8000}}}

// ParseText8000 is the only producer: validates input, returns the value or the first violation.
func ParseText8000(value string) (Text8000, *validate.Violation) {
	if viol := validate.Check(text8000Spec, value); viol != nil {
		return Text8000{}, viol
	}
	return Text8000{v: value}, nil
}

// ParseAllText8000 returns every unmet rule, for a live checklist / strength meter.
func ParseAllText8000(value string) []validate.Violation { return validate.CheckAll(text8000Spec, value) }

func (x Text8000) Value() string { return x.v }
func Text8000Spec() validate.ValidationSpec { return text8000Spec }
func (x Text8000) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Text8000) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
