// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Text0_2048 struct{ v string }

var text0_2048Spec = validate.ValidationSpec{Preprocess: validate.PreprocessTrim, Constraints: []validate.Constraint{{Kind: "minLen", Int: 0}, {Kind: "maxLen", Int: 2048}}}

// ParseText0_2048 is the only producer: validates input, returns the value or the first violation.
func ParseText0_2048(value string) (Text0_2048, *validate.Violation) {
	if viol := validate.Check(text0_2048Spec, value); viol != nil {
		return Text0_2048{}, viol
	}
	return Text0_2048{v: value}, nil
}

// ParseAllText0_2048 returns every unmet rule, for a live checklist / strength meter.
func ParseAllText0_2048(value string) []validate.Violation { return validate.CheckAll(text0_2048Spec, value) }

func (x Text0_2048) Value() string { return x.v }
func Text0_2048Spec() validate.ValidationSpec { return text0_2048Spec }
func (x Text0_2048) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Text0_2048) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
