// Code generated by tapir. DO NOT EDIT.

package primitives

import (
	"encoding/json"
	validate "integro_sdk/types"
)

type Text1_255 struct{ v string }

var text1_255Spec = validate.ValidationSpec{Preprocess: validate.PreprocessTrim, Constraints: []validate.Constraint{{Kind: "minLen", Int: 1}, {Kind: "maxLen", Int: 255}}}

// ParseText1_255 is the only producer: validates input, returns the value or the first violation.
func ParseText1_255(value string) (Text1_255, *validate.Violation) {
	if viol := validate.Check(text1_255Spec, value); viol != nil {
		return Text1_255{}, viol
	}
	return Text1_255{v: value}, nil
}

// ParseAllText1_255 returns every unmet rule, for a live checklist / strength meter.
func ParseAllText1_255(value string) []validate.Violation { return validate.CheckAll(text1_255Spec, value) }

func (x Text1_255) Value() string { return x.v }
func Text1_255Spec() validate.ValidationSpec { return text1_255Spec }
func (x Text1_255) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
func (x *Text1_255) UnmarshalJSON(b []byte) error { return json.Unmarshal(b, &x.v) }
