// Code generated by tapi. DO NOT EDIT.

package rate_limit

import (
	__client "integro_sdk"
	__strings "strings"
	database "integro_sdk/types/database"
	rate_limit "integro_sdk/types/rate_limit"
)

// Create Create a rate-limit rule for any target kind (HTTP scope, action, email dispatch, or channel pacing).
//
// Requires `CreateRateLimits`, which only platform staff hold.
func Create(__c *__client.Client, __body rate_limit.CreateRateLimitRuleRequest) (rate_limit.CreateRateLimitRuleResponse, error) {
	__path := "/rate-limit"
	return __client.Request[rate_limit.CreateRateLimitRuleResponse](__c, "POST", __path, nil, __body)
}
// Delete Delete a rate-limit rule by uid.
//
// Requires `DeleteRateLimits`, which only platform staff hold.
func Delete(__c *__client.Client, ruleUid string) (struct{}, error) {
	__path := "/rate-limit/{rule_uid}"
	__path = __strings.Replace(__path, "{rule_uid}", __client.EncodePath(ruleUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Get Fetch a single rate-limit rule by uid.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func Get(__c *__client.Client, ruleUid string) (database.RateLimitRule, error) {
	__path := "/rate-limit/{rule_uid}"
	__path = __strings.Replace(__path, "{rule_uid}", __client.EncodePath(ruleUid), 1)
	return __client.Request[database.RateLimitRule](__c, "GET", __path, nil, nil)
}
// List List every rate-limit rule.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func List(__c *__client.Client) ([]database.RateLimitRule, error) {
	__path := "/rate-limit"
	return __client.Request[[]database.RateLimitRule](__c, "GET", __path, nil, nil)
}
// Update Update an existing rate-limit rule's budget; the rule's target is immutable.
//
// Requires `UpdateRateLimits`, which only platform staff hold.
func Update(__c *__client.Client, ruleUid string, __body rate_limit.UpdateRateLimitRuleRequest) (struct{}, error) {
	__path := "/rate-limit/{rule_uid}"
	__path = __strings.Replace(__path, "{rule_uid}", __client.EncodePath(ruleUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
