// Code generated by tapir. DO NOT EDIT.

package message

// Channel-tagged backfill request — Meta's Conversations API covers the
// page-backed inboxes only, so no other channel's shape deserializes. The
// `channel` must match the named account's.
type BackfillRequest = interface{}
