// Code generated by tapir. DO NOT EDIT.

package message

// The largest picture the channel offers for the conversation's participant,
// hosted by the hub. `None` when the participant has none, hides it, or the
// platform could not be asked.
type ConversationAvatar struct {
	Url *string `json:"url"`
}
