// Code generated by tapir. DO NOT EDIT.

package message

import (
	domain "integro_sdk/types/domain"
)

// The largest picture the channel offers for the conversation's participant.
// `None` when the participant has none, hides it, or the platform could not
// be asked.
type ConversationAvatar struct {
	Media *domain.MediaRef `json:"media"`
}
