// Code generated by tapir. DO NOT EDIT.

package message

import (
	primitives "integro_sdk/types/primitives"
)

type ConversationMessagesQuery struct {
	// Scrollback cursor: only messages with `id` strictly smaller are returned.
	BeforeId *uint64 `json:"before_id"`
	Limit *primitives.Number1_200 `json:"limit"`
}
