// Code generated by tapir. DO NOT EDIT.

package message

import (
	types "integro_sdk/types/types"
)

type ConversationMessageCountQuery struct {
	// Only messages of these content kinds — the same narrowing as the list.
	Kinds *[]types.MessageContentKind `json:"kinds"`
}
