// Code generated by tapir. DO NOT EDIT.

package message

// Channel-tagged conversation creation — only the channels that can verify
// a number on the platform can initiate, so no other channel's shape
// deserializes.
type CreateConversationRequest = interface{}
