// Code generated by tapir. DO NOT EDIT.

package message

// Channel-tagged edit payload — only the unofficial WhatsApp flavors expose
// a platform edit call, so no other channel's shape deserializes. The
// `channel` must match the message's.
type EditMessageRequest = interface{}
