// Code generated by tapir. DO NOT EDIT.

package message

type EditMessageRequest struct {
	// The new text: replaces the body of text messages, the caption of media
	// messages.
	Text string `json:"text"`
}
