// Code generated by tapir. DO NOT EDIT.

package message

// Channel-tagged edit payload — only native WhatsApp exposes a platform
// edit call, so no other channel's shape deserializes. The `channel` must
// match the message's.
type EditMessageRequest = interface{}
