// Code generated by tapir. DO NOT EDIT.

package message

import (
	primitives "integro_sdk/types/primitives"
)

// Forward one message into other conversations. Each target is re-sent as a
// message of its own that the hub marks as forwarded; native whatsapp shows
// the recipient the forwarded label, the other channels have no such marker.
type ForwardMessageRequest struct {
	// The conversations to forward into (≤5). Each is answered separately in
	// the response; one refused target never blocks the others.
	Targets []primitives.Uid `json:"targets"`
}
