// Code generated by tapir. DO NOT EDIT.

package message

// Why one target was refused. A closed set the caller renders — per-target
// prose never rides a success body.
type ForwardRejection string

const (
	ForwardRejectionUnreachable ForwardRejection = "unreachable"
	ForwardRejectionAccountDisabled ForwardRejection = "account_disabled"
	ForwardRejectionUnsupportedContent ForwardRejection = "unsupported_content"
	ForwardRejectionWindowExpired ForwardRejection = "window_expired"
	ForwardRejectionFailed ForwardRejection = "failed"
)
