// Code generated by tapir. DO NOT EDIT.

package message

import (
	primitives "integro_sdk/types/primitives"
)

type ListMessagesQuery struct {
	// Narrow to these groups, each one the caller may see; omit for everything the caller may see.
	GroupUids *[]primitives.Uid `json:"group_uids"`
	// Narrow to these accounts, each one in scope; naming any account overrides the groups.
	SocialAccountUids *[]primitives.Uid `json:"social_account_uids"`
	// Poll cursor: only messages with `id` strictly greater are returned;
	// omit for every message. Not combinable with `uids`.
	SinceId *uint64 `json:"since_id"`
	// Exact messages to return (≤200), for resolving rows a client already
	// holds by uid — the reply targets a loaded page quotes but does not
	// contain. Not combinable with `since_id`.
	Uids *[]primitives.Uid `json:"uids"`
	Limit *primitives.Number1_500 `json:"limit"`
}
