// Code generated by tapir. DO NOT EDIT.

package message

import (
	primitives "integro_sdk/types/primitives"
)

type ListConversationsQuery struct {
	GroupUid *primitives.Uid `json:"group_uid"`
	SocialAccountUid *primitives.Uid `json:"social_account_uid"`
	// Exact conversations to return (≤200), for decorating rows a CRM already
	// holds by uid. Mutually exclusive with the keyset cursor; ordering follows
	// activity like the plain list.
	Uids *[]primitives.Uid `json:"uids"`
	// Keyset cursor: the previous page's last `(last_message_at, uid)` pair.
	// Both halves together or neither — the list reorders under live traffic,
	// so offsets would skip rows.
	BeforeActivityAt *int64 `json:"before_activity_at"`
	BeforeUid *primitives.Uid `json:"before_uid"`
	Limit *primitives.Number1_200 `json:"limit"`
}
