// Code generated by tapir. DO NOT EDIT.

package message

import (
	primitives "integro_sdk/types/primitives"
)

type ListTemplatesQuery struct {
	// Any whatsapp account of the WABA whose templates are managed.
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
}
