// Code generated by tapir. DO NOT EDIT.

package message

// The replacement text, shared by both editing flavors.
type MessageEdit struct {
	// The new text: replaces the body of text messages, the caption of media
	// messages.
	Text string `json:"text"`
}
