// Code generated by tapir. DO NOT EDIT.

package message

import (
	primitives "integro_sdk/types/primitives"
)

// Conversations-API import window, shared by both page-backed inboxes.
type MetaBackfill struct {
	SocialAccountUid primitives.Uid `json:"social_account_uid"`
	// How many conversations to import (newest first); defaults to 50.
	Conversations *primitives.Number1_200 `json:"conversations"`
	// How many messages per conversation (newest first); defaults to 50.
	MessagesPerConversation *primitives.Number1_100 `json:"messages_per_conversation"`
}
