// Code generated by tapir. DO NOT EDIT.

package message

import (
	meta "integro_sdk/types/meta"
)

// Presence on a channel with a real typing state: `typing_off` is a signal
// of its own.
type PresenceSignal struct {
	Action meta.SenderAction `json:"action"`
}
