// Code generated by tapir. DO NOT EDIT.

package message

// Channel-tagged reaction payload — the Messenger Send API has no reaction
// support, so no facebook variant exists. Must match the message's channel.
type ReactToMessageRequest = interface{}
