// Code generated by tapir. DO NOT EDIT.

package message

type SelfClearingSenderAction string

const (
	SelfClearingSenderActionMarkSeen SelfClearingSenderAction = "mark_seen"
	SelfClearingSenderActionTypingOn SelfClearingSenderAction = "typing_on"
)
