// Code generated by tapir. DO NOT EDIT.

package message

import (
	primitives "integro_sdk/types/primitives"
)

type SendMessageRequest struct {
	ConversationUid primitives.Uid `json:"conversation_uid"`
	// Client dedup key, unique per conversation. Retrying with the same key
	// never duplicates history: a failed row is retried in place, any other
	// row (sent, pending, canceled) is returned as-is without a new send.
	IdempotencyKey *string `json:"idempotency_key"`
	SendContent
}
