// Code generated by tapir. DO NOT EDIT.

package message

import (
	primitives "integro_sdk/types/primitives"
)

type SetConversationAliasRequest struct {
	// The label to set; `null` clears it, falling back to the platform name.
	Alias *primitives.Name `json:"alias"`
}
