// Code generated by tapir. DO NOT EDIT.

package message

import (
	meta "integro_sdk/types/meta"
)

// An approved template reference, the same shape the `template` send
// content takes: `components` fills the approved definition's placeholders.
type TemplateOpener struct {
	Name string `json:"name"`
	Language string `json:"language"`
	Components *[]meta.WhatsappTemplateSendComponent `json:"components"`
}
