// Code generated by tapir. DO NOT EDIT.

package message

import (
	meta "integro_sdk/types/meta"
)

type TemplateResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Language string `json:"language"`
	Category meta.WhatsappTemplateCategory `json:"category"`
	// Only `approved` templates are sendable.
	Status meta.WhatsappTemplateStatus `json:"status"`
	Components []meta.WhatsappTemplateComponent `json:"components"`
}
