// Code generated by tapir. DO NOT EDIT.

package message

type WebhookVerifyQuery struct {
	Mode *string `json:"hub.mode"`
	VerifyToken *string `json:"hub.verify_token"`
	Challenge *string `json:"hub.challenge"`
}
