// Code generated by tapir. DO NOT EDIT.

package message

type WhatsappSenderAction string

const (
	WhatsappSenderActionMarkSeen WhatsappSenderAction = "mark_seen"
	WhatsappSenderActionTypingOn WhatsappSenderAction = "typing_on"
)
