// Code generated by tapir. DO NOT EDIT.

package message

// Official whatsapp has no `typing_off` call — its indicator clears on its
// own — so the shape cannot express one.
type WhatsappPresenceSignal struct {
	Action WhatsappSenderAction `json:"action"`
}
