// Code generated by tapi. DO NOT EDIT.

package user_notification

import (
	__client "integro_sdk"
	user "integro_sdk/types/user"
)

// Get Get the caller's own notification choices that are not tied to one account: the sound a new message plays. Defaults stand until the caller changes them.
//
// Authenticated user acting on their own account.
func Get(__c *__client.Client) (user.UserNotificationResponse, error) {
	__path := "/user/me/notification"
	return __client.Request[user.UserNotificationResponse](__c, "GET", __path, nil, nil)
}
// Set Change the caller's own notification choices that are not tied to one account.
//
// Authenticated user acting on their own account.
func Set(__c *__client.Client, __body user.SetUserNotificationRequest) (struct{}, error) {
	__path := "/user/me/notification"
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
