// Code generated by tapi. DO NOT EDIT.

package version

import (
	__client "integro_sdk"
	version "integro_sdk/types/version"
)

// Get The release the server runs. A client generated from another release is
// outside its contract; the frontend reloads itself once the build being
// served matches this number.
//
// Public — no authentication required; the release number is no secret, the served frontend already states it.
func Get(__c *__client.Client) (version.VersionResponse, error) {
	__path := "/version"
	return __client.Request[version.VersionResponse](__c, "GET", __path, nil, nil)
}
