// Code generated by tapi. DO NOT EDIT.

package campaign_template

import (
	__client "integro_sdk"
	__strings "strings"
	campaign "integro_sdk/types/campaign"
)

// Add Append a template to the wheel. Draft, paused and done only.
//
// Requires `ManageCampaigns` in the campaign's group.
func Add(__c *__client.Client, campaignUid string, __body campaign.TemplateRequest) (campaign.CampaignTemplateResponse, error) {
	__path := "/campaign/{campaign_uid}/template"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[campaign.CampaignTemplateResponse](__c, "POST", __path, nil, __body)
}
// Delete Remove a template from the wheel. Draft, paused and done only.
//
// Requires `ManageCampaigns` in the campaign's group.
func Delete(__c *__client.Client, campaignUid string, templateUid string) (struct{}, error) {
	__path := "/campaign/{campaign_uid}/template/{template_uid}"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	__path = __strings.Replace(__path, "{template_uid}", __client.EncodePath(templateUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// List The template wheel, in rotation order.
//
// Requires `ViewCampaigns` in the campaign's group.
func List(__c *__client.Client, campaignUid string) ([]campaign.CampaignTemplateResponse, error) {
	__path := "/campaign/{campaign_uid}/template"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	return __client.Request[[]campaign.CampaignTemplateResponse](__c, "GET", __path, nil, nil)
}
// Update Rewrite a template in place, keeping its position in the wheel. Draft,
// paused and done only; the same checks as adding one.
//
// Requires `ManageCampaigns` in the campaign's group.
func Update(__c *__client.Client, campaignUid string, templateUid string, __body campaign.TemplateRequest) (campaign.CampaignTemplateResponse, error) {
	__path := "/campaign/{campaign_uid}/template/{template_uid}"
	__path = __strings.Replace(__path, "{campaign_uid}", __client.EncodePath(campaignUid), 1)
	__path = __strings.Replace(__path, "{template_uid}", __client.EncodePath(templateUid), 1)
	return __client.Request[campaign.CampaignTemplateResponse](__c, "PUT", __path, nil, __body)
}
