// Code generated by tapir. DO NOT EDIT.

package gif

// One catalog entry, in the renditions the composer needs.
type Gif struct {
	Id string `json:"id"`
	Title string `json:"title"`
	// The picker tile: an animated webp, or a gif when Giphy has no webp.
	PreviewUrl string `json:"preview_url"`
	PreviewWidth uint32 `json:"preview_width"`
	PreviewHeight uint32 `json:"preview_height"`
	// The clip the bubble plays — sent as `gif` natively and as a plain video
	// on the channels without a gif shape.
	Mp4Url string `json:"mp4_url"`
	// The .gif itself, for the channels that animate an image attachment.
	GifUrl string `json:"gif_url"`
}
