// Code generated by tapir. DO NOT EDIT.

package gif

import (
	primitives "integro_sdk/types/primitives"
)

type SearchGifsQuery struct {
	// Search terms; blank or absent lists the trending feed instead.
	Q *primitives.Text0_50 `json:"q"`
	// Where the page starts — the previous page's `next_offset`; 0 when absent.
	Offset *primitives.Number0_4999 `json:"offset"`
}
