// Code generated by tapir. DO NOT EDIT.

package user_password_reset

import (
	primitives "integro_sdk/types/primitives"
)

type UserPasswordResetConfirmRequest struct {
	Token primitives.Uid `json:"token"`
	NewPassword primitives.Password8_128_F_F_T_F `json:"new_password"`
}
