// Code generated by tapir. DO NOT EDIT.

package user_password_reset

import (
	primitives "integro_sdk/types/primitives"
)

type UserPasswordResetStartRequest struct {
	Email primitives.Email `json:"email"`
}
