// Code generated by tapir. DO NOT EDIT.

package ghl

// GoHighLevel's `ProviderOutboundMessage` delivery payload (SMS shape): one
// message a location placed on our conversation provider, to be sent out on
// the whatsapp account it is linked to.
//
// A delivery also carries `contactId` and `userId` (the GHL user who sent it,
// absent when a workflow did). Neither names anything on this side — the
// destination is the phone, and the attribution the bridge stores is the
// location — so both are left to serde's unknown fields.
type GhlDeliveryPayload struct {
	LocationId string `json:"locationId"`
	// GoHighLevel's id for the message, and the seed of the idempotency keys
	// that make its retries harmless.
	MessageId string `json:"messageId"`
	// The provider module the message rode; only `SMS` reaches whatsapp.
	Kind string `json:"type"`
	// The destination in `+`-prefixed E.164 — the shape a conversation opens
	// from.
	Phone *string `json:"phone"`
	Message *string `json:"message"`
	// Attachment urls, sent as their own messages after the text.
	Attachments []string `json:"attachments"`
}
