// Code generated by tapir. DO NOT EDIT.

package ghl

import (
	primitives "integro_sdk/types/primitives"
)

// The contact tag the bridge adds when a human answers; `None` turns the
// handoff off.
type SetGhlHandoffTagRequest struct {
	Tag *primitives.Name `json:"tag"`
}
