// Code generated by tapir. DO NOT EDIT.

package rate_limit

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type CreateActionRateLimitRequest struct {
	Action types.RateLimitAction `json:"action"`
	MaxRequests primitives.Number1_100000 `json:"max_requests"`
	WindowSeconds primitives.Number1_3600 `json:"window_seconds"`
}
