// Code generated by tapir. DO NOT EDIT.

package rate_limit

import (
	types "integro_sdk/types/types"
)

type UpdateRateLimitRuleRequest struct {
	// Replacement rule payload — target *and* budget, so it is sent whole
	// rather than as a field mask. Must keep the same target (`kind` plus its
	// identity fields); only the budget may change.
	Rule types.RateLimitRuleKind `json:"rule"`
}
