// Code generated by tapir. DO NOT EDIT.

package rate_limit

import (
	axumy "integro_sdk/types/axumy"
)

type UpdateActionRateLimitRequest struct {
	MaxRequests axumy.OptionalUpdate `json:"max_requests"`
	WindowSeconds axumy.OptionalUpdate `json:"window_seconds"`
}
