// Code generated by tapir. DO NOT EDIT.

package rate_limit

import (
	axumy "integro_sdk/types/axumy"
)

type UpdateChannelPacingRequest struct {
	MinDelayMs axumy.OptionalUpdate `json:"min_delay_ms"`
	MaxDelayMs axumy.OptionalUpdate `json:"max_delay_ms"`
	BatchSize axumy.OptionalUpdate `json:"batch_size"`
	BatchPauseMs axumy.OptionalUpdate `json:"batch_pause_ms"`
}
