// Code generated by tapir. DO NOT EDIT.

package pulse

import (
	database "integro_sdk/types/database"
)

type PulseInventoryResponse struct {
	Disks []database.PulseDiskInventoryRow `json:"disks"`
	Networks []database.PulseNetworkInventoryRow `json:"networks"`
	Gpus []database.PulseGpuInventoryRow `json:"gpus"`
}
