// Code generated by tapir. DO NOT EDIT.

package pulse

import (
	domain "integro_sdk/types/domain"
)

type PulseInventoryResponse struct {
	Disks []domain.PulseDiskInventoryRow `json:"disks"`
	Networks []domain.PulseNetworkInventoryRow `json:"networks"`
	Gpus []domain.PulseGpuInventoryRow `json:"gpus"`
}
