// Code generated by tapi. DO NOT EDIT.

package test

import (
	__client "integro_sdk"
)

// BadRequest Return a 400 — probe for the client's bad-request handling.
//
// Public — no authentication required.
func BadRequest(__c *__client.Client) (struct{}, error) {
	__path := "/test/bad-request"
	return __client.Request[struct{}](__c, "GET", __path, nil, nil)
}
// Conflict Return a 409 — probe for the client's conflict handling.
//
// Public — no authentication required.
func Conflict(__c *__client.Client) (struct{}, error) {
	__path := "/test/conflict"
	return __client.Request[struct{}](__c, "GET", __path, nil, nil)
}
// Forbidden Return a 403 — probe for the client's permission-denied handling.
//
// Public — no authentication required.
func Forbidden(__c *__client.Client) (struct{}, error) {
	__path := "/test/forbidden"
	return __client.Request[struct{}](__c, "GET", __path, nil, nil)
}
// Internal Return a 500 — probe for the client's server-error handling.
//
// Public — no authentication required.
func Internal(__c *__client.Client) (struct{}, error) {
	__path := "/test/internal"
	return __client.Request[struct{}](__c, "GET", __path, nil, nil)
}
// NotFound Return a 404 — probe for the client's missing-resource handling.
//
// Public — no authentication required.
func NotFound(__c *__client.Client) (struct{}, error) {
	__path := "/test/not-found"
	return __client.Request[struct{}](__c, "GET", __path, nil, nil)
}
// Ok Return a success envelope — the happy-path probe for client error handling.
//
// Public — no authentication required.
func Ok(__c *__client.Client) (string, error) {
	__path := "/test/ok"
	return __client.Request[string](__c, "GET", __path, nil, nil)
}
// Panic Panic — probe that the panic layer answers 500 instead of dropping the connection.
//
// Public — no authentication required.
func Panic(__c *__client.Client) (struct{}, error) {
	__path := "/test/panic"
	return __client.Request[struct{}](__c, "GET", __path, nil, nil)
}
// Unauthorized Return a 401 — probe for the client's session-expiry handling.
//
// Public — no authentication required.
func Unauthorized(__c *__client.Client) (struct{}, error) {
	__path := "/test/unauthorized"
	return __client.Request[struct{}](__c, "GET", __path, nil, nil)
}
// Unavailable Return a 503 — probe for the client's outage handling.
//
// Public — no authentication required.
func Unavailable(__c *__client.Client) (struct{}, error) {
	__path := "/test/unavailable"
	return __client.Request[struct{}](__c, "GET", __path, nil, nil)
}
