// Code generated by tapi. DO NOT EDIT.

package http

import (
	__client "integro_sdk"
	__strings "strings"
	database "integro_sdk/types/database"
	rate_limit "integro_sdk/types/rate_limit"
)

// Create Create an HTTP rate-limit rule scoped to a group or to the whole platform.
//
// Requires `CreateRateLimits`, which only platform staff hold; a group rule must name its group, a global or anonymous rule must not.
func Create(__c *__client.Client, __body rate_limit.CreateHttpRateLimitRequest) (rate_limit.CreateHttpRateLimitResponse, error) {
	__path := "/rate-limit/http"
	return __client.Request[rate_limit.CreateHttpRateLimitResponse](__c, "POST", __path, nil, __body)
}
// Delete Delete an HTTP rate-limit rule by uid.
//
// Requires `DeleteRateLimits`, which only platform staff hold.
func Delete(__c *__client.Client, ruleUid string) (struct{}, error) {
	__path := "/rate-limit/http/{rule_uid}"
	__path = __strings.Replace(__path, "{rule_uid}", __client.EncodePath(ruleUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Get Fetch a single HTTP rate-limit rule by uid.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func Get(__c *__client.Client, ruleUid string) (database.HttpRateLimitRule, error) {
	__path := "/rate-limit/http/{rule_uid}"
	__path = __strings.Replace(__path, "{rule_uid}", __client.EncodePath(ruleUid), 1)
	return __client.Request[database.HttpRateLimitRule](__c, "GET", __path, nil, nil)
}
// List List all HTTP rate-limit rules.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func List(__c *__client.Client) ([]database.HttpRateLimitRule, error) {
	__path := "/rate-limit/http"
	return __client.Request[[]database.HttpRateLimitRule](__c, "GET", __path, nil, nil)
}
// Update Update the limits of an existing HTTP rate-limit rule.
//
// Requires `UpdateRateLimits`, which only platform staff hold.
func Update(__c *__client.Client, ruleUid string, __body rate_limit.UpdateHttpRateLimitRequest) (struct{}, error) {
	__path := "/rate-limit/http/{rule_uid}"
	__path = __strings.Replace(__path, "{rule_uid}", __client.EncodePath(ruleUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
