// Code generated by tapi. DO NOT EDIT.

package http

import (
	"integro_sdk"
	"strings"
	database "integro_sdk/types/database"
	rate_limit "integro_sdk/types/rate_limit"
)

// Create Create an HTTP rate-limit rule scoped to a group or to the whole platform.
//
// Requires `CreateRateLimits`, which only platform staff hold; a group rule must name its group, a global or anonymous rule must not.
func Create(c *client.Client, body rate_limit.CreateHttpRateLimitRequest) (rate_limit.CreateHttpRateLimitResponse, error) {
	__path := "/rate-limit/http"
	return client.Request[rate_limit.CreateHttpRateLimitResponse](c, "POST", __path, nil, body)
}
// Delete Delete an HTTP rate-limit rule by uid.
//
// Requires `DeleteRateLimits`, which only platform staff hold.
func Delete(c *client.Client, ruleUid string) (struct{}, error) {
	__path := "/rate-limit/http/{rule_uid}"
	__path = strings.Replace(__path, "{rule_uid}", client.EncodePath(ruleUid), 1)
	return client.Request[struct{}](c, "DELETE", __path, nil, nil)
}
// Get Fetch a single HTTP rate-limit rule by uid.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func Get(c *client.Client, ruleUid string) (database.HttpRateLimitRule, error) {
	__path := "/rate-limit/http/{rule_uid}"
	__path = strings.Replace(__path, "{rule_uid}", client.EncodePath(ruleUid), 1)
	return client.Request[database.HttpRateLimitRule](c, "GET", __path, nil, nil)
}
// List List all HTTP rate-limit rules.
//
// Requires `ViewRateLimits`, which only platform staff hold.
func List(c *client.Client) ([]database.HttpRateLimitRule, error) {
	__path := "/rate-limit/http"
	return client.Request[[]database.HttpRateLimitRule](c, "GET", __path, nil, nil)
}
// Update Update the limits of an existing HTTP rate-limit rule.
//
// Requires `UpdateRateLimits`, which only platform staff hold.
func Update(c *client.Client, ruleUid string, body rate_limit.UpdateHttpRateLimitRequest) (struct{}, error) {
	__path := "/rate-limit/http/{rule_uid}"
	__path = strings.Replace(__path, "{rule_uid}", client.EncodePath(ruleUid), 1)
	return client.Request[struct{}](c, "PUT", __path, nil, body)
}
