// Code generated by tapir. DO NOT EDIT.

package call

// Client → server control frames. Everything that decides *whether* a call
// exists — placing, answering, refusing, ending — stays on REST, where it is
// audited and permission-checked; this socket only carries what a call in
// progress needs.
type CallClientMsg = interface{}
