// Code generated by tapir. DO NOT EDIT.

package call

import (
	primitives "integro_sdk/types/primitives"
)

type ConversationCallsQuery struct {
	// Scrollback cursor: only calls with `id` strictly smaller are returned.
	BeforeId *uint64 `json:"before_id"`
	Limit *primitives.Number1_200 `json:"limit"`
}
