// Code generated by tapir. DO NOT EDIT.

package call

// Channel-tagged call placement — only whatsapp_native carries calls, so no
// other channel's shape deserializes.
type PlaceCallRequest = interface{}
