// Code generated by tapir. DO NOT EDIT.

package user_session

import (
	primitives "integro_sdk/types/primitives"
)

type ListUserSessionsQuery struct {
	UserUid *primitives.Uid `json:"user_uid"`
}
