// Code generated by tapir. DO NOT EDIT.

package user_session

import (
	primitives "integro_sdk/types/primitives"
)

type UserSessionLoginRequest struct {
	Email primitives.Email `json:"email"`
	Password string `json:"password"`
}
