// Code generated by tapir. DO NOT EDIT.

package user_session

import (
	primitives "integro_sdk/types/primitives"
)

type UserSessionRow struct {
	Uid primitives.Uid `json:"uid"`
	Ip *string `json:"ip"`
	UserAgent *string `json:"user_agent"`
	Country *string `json:"country"`
	City *string `json:"city"`
	LastSeenAt *primitives.Timestamp `json:"last_seen_at"`
	ExpiresAt primitives.Timestamp `json:"expires_at"`
	CreatedAt primitives.Timestamp `json:"created_at"`
	Current bool `json:"current"`
}
