// Code generated by tapi. DO NOT EDIT.

package user

import (
	"integro_sdk"
	"strings"
	database "integro_sdk/types/database"
	user "integro_sdk/types/user"
)

// Activate Reactivate another user, re-enabling their account.
//
// Requires `ActivateUsers`, which only platform staff hold.
func Activate(c *client.Client, userUid string) (struct{}, error) {
	__path := "/user/{user_uid}/activate"
	__path = strings.Replace(__path, "{user_uid}", client.EncodePath(userUid), 1)
	return client.Request[struct{}](c, "POST", __path, nil, nil)
}
// ChangePassword Change the authenticated user's own password and revoke their other sessions.
//
// Authenticated user acting on their own account.
func ChangePassword(c *client.Client, body user.UserChangePasswordRequest) (struct{}, error) {
	__path := "/user/me/password"
	return client.Request[struct{}](c, "PUT", __path, nil, body)
}
// Count Count all users.
//
// Requires `ViewUsers`, which only platform staff hold.
func Count(c *client.Client) (uint64, error) {
	__path := "/user/count"
	return client.Request[uint64](c, "GET", __path, nil, nil)
}
// Create Create a user, who starts out belonging to no group.
//
// Requires `ProvisionUsers`, which only platform staff hold.
func Create(c *client.Client, body user.CreateUserRequest) (user.CreateUserResponse, error) {
	__path := "/user"
	return client.Request[user.CreateUserResponse](c, "POST", __path, nil, body)
}
// Deactivate Deactivate another user, disabling their account while preserving sessions.
//
// Requires `ActivateUsers`, which only platform staff hold; you cannot deactivate yourself.
func Deactivate(c *client.Client, userUid string) (struct{}, error) {
	__path := "/user/{user_uid}/deactivate"
	__path = strings.Replace(__path, "{user_uid}", client.EncodePath(userUid), 1)
	return client.Request[struct{}](c, "POST", __path, nil, nil)
}
// Delete Delete another user.
//
// Requires `DeleteUsers`, which only platform staff hold; you cannot delete yourself.
func Delete(c *client.Client, userUid string) (struct{}, error) {
	__path := "/user/{user_uid}"
	__path = strings.Replace(__path, "{user_uid}", client.EncodePath(userUid), 1)
	return client.Request[struct{}](c, "DELETE", __path, nil, nil)
}
// Get Get a single user by uid.
//
// Requires `ViewUsers`, which only platform staff hold.
func Get(c *client.Client, userUid string) (database.User, error) {
	__path := "/user/{user_uid}"
	__path = strings.Replace(__path, "{user_uid}", client.EncodePath(userUid), 1)
	return client.Request[database.User](c, "GET", __path, nil, nil)
}
// GetSelf Get the authenticated user's own account, along with the permissions and memberships every gating decision reads.
//
// Authenticated user acting on their own account.
func GetSelf(c *client.Client) (user.UserSelfResponse, error) {
	__path := "/user/me"
	return client.Request[user.UserSelfResponse](c, "GET", __path, nil, nil)
}
// List List all users.
//
// Requires `ViewUsers`, which only platform staff hold.
func List(c *client.Client) ([]database.User, error) {
	__path := "/user"
	return client.Request[[]database.User](c, "GET", __path, nil, nil)
}
// SetSuperAdmin Grant or revoke another user's platform staff standing.
//
// Requires `SetSuperAdmin`, which only platform staff hold; you can never change your own flag.
func SetSuperAdmin(c *client.Client, userUid string, body user.SetUserSuperAdminRequest) (struct{}, error) {
	__path := "/user/{user_uid}/super-admin"
	__path = strings.Replace(__path, "{user_uid}", client.EncodePath(userUid), 1)
	return client.Request[struct{}](c, "PUT", __path, nil, body)
}
// Update Update another user's profile.
//
// Requires `UpdateUsers`, which only platform staff hold.
func Update(c *client.Client, userUid string, body user.UpdateUserRequest) (struct{}, error) {
	__path := "/user/{user_uid}"
	__path = strings.Replace(__path, "{user_uid}", client.EncodePath(userUid), 1)
	return client.Request[struct{}](c, "PUT", __path, nil, body)
}
// UpdateSelf Update the authenticated user's own profile.
//
// Authenticated user acting on their own account.
func UpdateSelf(c *client.Client, body user.UpdateUserSelfRequest) (struct{}, error) {
	__path := "/user/me"
	return client.Request[struct{}](c, "PUT", __path, nil, body)
}
