// Code generated by tapi. DO NOT EDIT.

package oauth

import (
	__client "integro_sdk"
	oauth_server "integro_sdk/types/oauth_server"
)

// Approve Grant the OAuth client access as the calling user: mint the authorization code (valid 2 minutes, single use) and answer the redirect that delivers it.
//
// Authenticated user acting on their own behalf; no permission required. Only a session may approve: an API key or an OAuth token cannot mint grants.
func Approve(__c *__client.Client, __body oauth_server.ApproveRequest) (oauth_server.ApproveResponse, error) {
	__path := "/oauth/approve"
	return __client.Request[oauth_server.ApproveResponse](__c, "POST", __path, nil, __body)
}
// Consent Describe the OAuth client asking for access, for the consent page, after checking that the request is one this server would honour: registered client, a matching redirect uri, `response_type` code, PKCE `S256`, and a `resource` naming this server's MCP endpoint. A redirect uri matches its registered form exactly, except that a registered loopback http uri (`http://localhost`, `http://127.0.0.1`) matches on scheme, host and path with any port, as RFC 8252 §7.3 asks for native apps. The request is read leniently where there is only one answer: an absent `code_challenge_method` means `S256` (the only method this server supports) and an absent `resource` means this server's MCP endpoint, which is what the code is bound to either way.
//
// Authenticated user acting on their own behalf; no permission required. Only a session may ask: an API key or an OAuth token cannot reach the consent step.
func Consent(__c *__client.Client, __query oauth_server.ConsentQuery) (oauth_server.ConsentResponse, error) {
	__path := "/oauth/consent"
	return __client.Request[oauth_server.ConsentResponse](__c, "GET", __path, __query, nil)
}
