// Code generated by tapir. DO NOT EDIT.

package event

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

// The connection's base subscription. Every list is OR within itself, AND
// across fields; omitted lists don't filter. The caller's permissions and
// group scope always apply on top.
type RosterFilter struct {
	GroupUids *[]primitives.Uid `json:"group_uids"`
	SocialAccountUids *[]primitives.Uid `json:"social_account_uids"`
	Channels *[]domain.Channel `json:"channels"`
	// Event kinds and/or family aliases (`message`, `presence`, `comment`,
	// `mention`, `post`, `conversation`, `account`, `review`).
	Events *[]string `json:"events"`
}
