// Code generated by tapir. DO NOT EDIT.

package event

import (
	domain "integro_sdk/types/domain"
	primitives "integro_sdk/types/primitives"
)

type SetWebhookRequest struct {
	// Required for users and platform keys; group-bound keys imply their group.
	GroupUid *primitives.Uid `json:"group_uid"`
	Url string `json:"url"`
	// Event kinds delivered to this subscription; omit for everything. The
	// live-only kinds (the presence kinds), which reach only the event socket,
	// are refused here.
	Events *[]domain.EventKind `json:"events"`
	// Channels delivered to this subscription; omit for everything.
	Channels *[]domain.Channel `json:"channels"`
}
