// Code generated by tapir. DO NOT EDIT.

package event

import (
	primitives "integro_sdk/types/primitives"
	types "integro_sdk/types/types"
)

type SetWebhookRequest struct {
	// Required for users and platform keys; group-bound keys imply their group.
	GroupUid *primitives.Uid `json:"group_uid"`
	Url string `json:"url"`
	// Event kinds (and/or family aliases: `message`, `presence`, `comment`,
	// `mention`, `post`, `conversation`, `account`, `review`) delivered to this
	// subscription; omit for everything. Presence kinds are accepted but never
	// delivered here — they are live-stream-only by construction, so a webhook
	// filtered to presence alone receives nothing.
	Events *[]string `json:"events"`
	// Channels delivered to this subscription; omit for everything.
	Channels *[]types.Channel `json:"channels"`
}
