// Code generated by tapi. DO NOT EDIT.

package group

import (
	__client "integro_sdk"
	__strings "strings"
	group "integro_sdk/types/group"
)

// Count Count groups.
//
// Requires `ViewGroups`; the count covers only groups where the caller holds it.
func Count(__c *__client.Client) (uint64, error) {
	__path := "/group/count"
	return __client.Request[uint64](__c, "GET", __path, nil, nil)
}
// Create Create a group, optionally with a logo image.
//
// Requires `CreateGroups`, which is only ever held platform-wide — no group exists yet to scope it to. Rejected — when a logo is attached — when the caller trips the per-user file-upload throttle.
func Create(__c *__client.Client, __form *__client.MultipartForm) (group.CreateGroupResponse, error) {
	__path := "/group"
	return __client.RequestMultipart[group.CreateGroupResponse](__c, "POST", __path, nil, __form)
}
// Delete Delete a group that has no API keys and no social accounts.
//
// Requires `DeleteGroups` in the group itself; fails while the group still has API keys or social accounts.
func Delete(__c *__client.Client, groupUid string) (struct{}, error) {
	__path := "/group/{group_uid}"
	__path = __strings.Replace(__path, "{group_uid}", __client.EncodePath(groupUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// Get Fetch a single group, optionally enriched with per-group counts.
//
// Requires `ViewGroups` in the group itself; each count is filled only when the caller also holds that count's own permission there — `ViewApiKeys` for `api_key_count`, `ViewMembers` for `member_count`, `ViewSocialAccounts` for `social_account_count` — and is `null` otherwise.
func Get(__c *__client.Client, groupUid string, __query group.GroupQuery) (group.GroupResponse, error) {
	__path := "/group/{group_uid}"
	__path = __strings.Replace(__path, "{group_uid}", __client.EncodePath(groupUid), 1)
	return __client.Request[group.GroupResponse](__c, "GET", __path, __query, nil)
}
// GetLogo Serve a group's logo image.
//
// Requires `ViewGroups` in the group itself.
func GetLogo(__c *__client.Client, groupUid string) ([]byte, error) {
	__path := "/group/{group_uid}/logo"
	__path = __strings.Replace(__path, "{group_uid}", __client.EncodePath(groupUid), 1)
	return __client.RequestBytes(__c, "GET", __path, nil, nil)
}
// List List groups, optionally enriched with per-group counts.
//
// Requires `ViewGroups`; the list covers only groups where the caller holds it, and each count is filled only for those where it also holds that count's own permission — `ViewApiKeys` for `api_key_count`, `ViewMembers` for `member_count`, `ViewSocialAccounts` for `social_account_count` — `null` everywhere else.
func List(__c *__client.Client, __query group.GroupQuery) ([]group.GroupResponse, error) {
	__path := "/group"
	return __client.Request[[]group.GroupResponse](__c, "GET", __path, __query, nil)
}
// RemoveLogo Remove a group's logo image.
//
// Requires `UpdateGroups` in the group itself.
func RemoveLogo(__c *__client.Client, groupUid string) (struct{}, error) {
	__path := "/group/{group_uid}/logo"
	__path = __strings.Replace(__path, "{group_uid}", __client.EncodePath(groupUid), 1)
	return __client.Request[struct{}](__c, "DELETE", __path, nil, nil)
}
// SetEnabled Enable or disable a group; API keys bound to a disabled group are rejected.
//
// Requires `ToggleGroupEnabled` in the group itself.
func SetEnabled(__c *__client.Client, groupUid string, __body group.SetGroupEnabledRequest) (struct{}, error) {
	__path := "/group/{group_uid}/enabled"
	__path = __strings.Replace(__path, "{group_uid}", __client.EncodePath(groupUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
// SetLogo Upload or replace a group's logo image.
//
// Requires `UpdateGroups` in the group itself, and is rejected when the caller trips the per-user file-upload throttle.
func SetLogo(__c *__client.Client, groupUid string, __form *__client.MultipartForm) (struct{}, error) {
	__path := "/group/{group_uid}/logo"
	__path = __strings.Replace(__path, "{group_uid}", __client.EncodePath(groupUid), 1)
	return __client.RequestMultipart[struct{}](__c, "POST", __path, nil, __form)
}
// Update Update a group's mutable fields such as its name.
//
// Requires `UpdateGroups` in the group itself.
func Update(__c *__client.Client, groupUid string, __body group.UpdateGroupRequest) (struct{}, error) {
	__path := "/group/{group_uid}"
	__path = __strings.Replace(__path, "{group_uid}", __client.EncodePath(groupUid), 1)
	return __client.Request[struct{}](__c, "PUT", __path, nil, __body)
}
