// Code generated by tapi. DO NOT EDIT.

package uptime

import (
	"integro_sdk"
	database "integro_sdk/types/database"
	uptime "integro_sdk/types/uptime"
)

// GetLatest Get the most recent server uptime record.
//
// Requires `ViewPulse`, which only platform staff hold.
func GetLatest(c *client.Client) (*database.ServerUptime, error) {
	__path := "/uptime/latest"
	return client.Request[*database.ServerUptime](c, "GET", __path, nil, nil)
}
// GetStats Compute aggregate server uptime statistics within a time range.
//
// Requires `ViewPulse`, which only platform staff hold.
func GetStats(c *client.Client, query uptime.ServerUptimeRangeQuery) (database.ServerUptimeStats, error) {
	__path := "/uptime/stats"
	return client.Request[database.ServerUptimeStats](c, "GET", __path, query, nil)
}
// List List server uptime records within a time range.
//
// Requires `ViewPulse`, which only platform staff hold.
func List(c *client.Client, query uptime.ServerUptimeRangeQuery) ([]database.ServerUptime, error) {
	__path := "/uptime"
	return client.Request[[]database.ServerUptime](c, "GET", __path, query, nil)
}
